name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇦🇷_1"
    type: vless
    server: "38.180.186.202"
    port: 443
    uuid: "18b476f8-d1ca-4bf5-a397-c6fbf8ef4d41"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_2"
    type: vless
    server: "149.33.19.143"
    port: 443
    uuid: "049b5a3c-3331-4a16-a12a-1f79c5b52d17"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_3"
    type: vless
    server: "38.180.186.202"
    port: 443
    uuid: "ddc16e82-b242-43c3-9c9c-96c0f1cce41b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_4"
    type: vless
    server: "38.180.186.202"
    port: 443
    uuid: "8695f319-5c61-4933-afed-a17dab92d9bb"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_5"
    type: vless
    server: "38.180.186.202"
    port: 443
    uuid: "b132e352-7a63-4477-b31f-67939a886767"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_6"
    type: vless
    server: "38.180.186.202"
    port: 443
    uuid: "bbe48cb4-1a71-4a6f-a50f-eac7e36c1052"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_7"
    type: vless
    server: "38.180.186.202"
    port: 443
    uuid: "f631578d-7b57-47b6-8dd5-1d558bb54a92"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_8"
    type: vless
    server: "149.33.19.143"
    port: 443
    uuid: "b2508986-719e-4bb0-8d1e-f75bc216b48e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_9"
    type: vless
    server: "38.180.186.202"
    port: 443
    uuid: "9cacc6bf-840f-405a-991b-abef7ad86a1d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_10"
    type: vless
    server: "149.33.19.143"
    port: 443
    uuid: "6a7847c6-69e0-46c1-b685-b1a1cca9eb4c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_11"
    type: vless
    server: "38.180.186.202"
    port: 443
    uuid: "1199c55b-f7ed-451a-bcbc-387d0ed84117"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_12"
    type: vless
    server: "149.33.19.143"
    port: 443
    uuid: "732d967a-b82c-48e8-9de9-a133d8148b3d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_13"
    type: vless
    server: "38.180.186.202"
    port: 443
    uuid: "bdc97169-ccbe-41b6-8c72-adcfc57c15c0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_14"
    type: vless
    server: "149.33.19.143"
    port: 443
    uuid: "0530cbe4-d441-402a-be2e-1627beb458f5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_15"
    type: vless
    server: "149.33.19.143"
    port: 443
    uuid: "25acff7f-3aff-4c68-bc5e-bbc68589f459"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_16"
    type: vless
    server: "38.180.186.202"
    port: 443
    uuid: "d7297202-5d6f-4682-b550-ecf916b0cd01"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_17"
    type: vless
    server: "38.180.186.202"
    port: 443
    uuid: "7f32fb1f-9f6f-4e40-a359-de8f0369d981"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_18"
    type: vless
    server: "38.180.186.202"
    port: 443
    uuid: "c49e0537-9efe-4f0f-ae5d-dba2f3cc2bc4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_19"
    type: vless
    server: "38.180.186.202"
    port: 443
    uuid: "5695ff2a-d23c-45f8-85f4-19e2a80314cc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_20"
    type: vless
    server: "149.33.19.143"
    port: 443
    uuid: "5567bf8c-e870-469d-b117-770c644c2682"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_21"
    type: vless
    server: "149.33.19.143"
    port: 443
    uuid: "81dae76a-3ce4-4c5f-a5a4-ef67e4490cd6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_22"
    type: vless
    server: "38.180.186.202"
    port: 443
    uuid: "fbb2a729-592a-4d3b-9f47-8a355b7751c9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_23"
    type: vless
    server: "38.180.186.202"
    port: 443
    uuid: "8f0faee5-b051-4349-b726-d6d7b83d24e0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_24"
    type: vless
    server: "149.33.19.143"
    port: 443
    uuid: "a4101305-0901-4864-9ebf-da3c23b95307"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_25"
    type: vless
    server: "38.180.186.202"
    port: 443
    uuid: "237f5460-66a2-4c27-97e6-93b352733a3a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_26"
    type: vless
    server: "38.180.186.202"
    port: 443
    uuid: "be77dc02-5753-4018-8115-2e91f8b92823"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_27"
    type: vless
    server: "149.33.19.143"
    port: 443
    uuid: "9a40ddea-41a7-441c-9b36-6dd51ee68211"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_28"
    type: vless
    server: "38.180.186.202"
    port: 443
    uuid: "bf5a02f8-945f-4431-ba62-d949275b5aa3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_29"
    type: vless
    server: "149.33.19.143"
    port: 443
    uuid: "7554d102-a926-4ac6-9f5d-1ad2264b431c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇦🇷_30"
    type: vless
    server: "149.33.19.143"
    port: 443
    uuid: "5e5afd7c-d342-4143-940d-c57e90cc4d47"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇦🇷_1"
      - "🇦🇷_2"
      - "🇦🇷_3"
      - "🇦🇷_4"
      - "🇦🇷_5"
      - "🇦🇷_6"
      - "🇦🇷_7"
      - "🇦🇷_8"
      - "🇦🇷_9"
      - "🇦🇷_10"
      - "🇦🇷_11"
      - "🇦🇷_12"
      - "🇦🇷_13"
      - "🇦🇷_14"
      - "🇦🇷_15"
      - "🇦🇷_16"
      - "🇦🇷_17"
      - "🇦🇷_18"
      - "🇦🇷_19"
      - "🇦🇷_20"
      - "🇦🇷_21"
      - "🇦🇷_22"
      - "🇦🇷_23"
      - "🇦🇷_24"
      - "🇦🇷_25"
      - "🇦🇷_26"
      - "🇦🇷_27"
      - "🇦🇷_28"
      - "🇦🇷_29"
      - "🇦🇷_30"


rules:
  - MATCH,PROXY
