name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇦🇹_1"
    type: vless
    server: "94.228.163.241"
    port: 2053
    uuid: "c7ae1368-b6ca-4d11-beef-bb76f68d1b80"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "PsJ_TTwvE06Du6qrgNqjqb7d0A1nA4Uh5FsuapOVKCE"
      short-id: "7709f1853d63def9"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇦🇹_2"
    type: vless
    server: "152.53.1.40"
    port: 443
    uuid: "edde565e-41f5-400e-84ea-7b87a3e84488"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "at.quattro-tech.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "10rVZPoOUP1TlQviIAsQ_jAROX0fRQxH0C92nq_zGQc"
      short-id: "43dcff53849b81e6"
    flow: "xtls-rprx-vision"
  - name: "🇦🇹_3"
    type: vless
    server: "152.53.114.186"
    port: 443
    uuid: "ab7d5ea9-6eca-47c3-b14b-67378fc2d7c2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "as.tunnelx.space"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "UO3EObgU3xUrhIGEE0gfCn5ZOz8YxNcwwW6ZaYzD3SA"
      short-id: "4e9b0c2d1a3f5768"
    flow: "xtls-rprx-vision"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇦🇹_1"
      - "🇦🇹_2"
      - "🇦🇹_3"


rules:
  - MATCH,PROXY
