name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇦🇹_1"
    type: vless
    server: "159.195.244.171"
    port: 2054
    uuid: "75079a7f-75b5-418b-8a65-f7b2f438cd4a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.ibm.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "0-HIOsSIQTrTYc5PdFT0OSKGBiBUiGrJzgV6ctal8Fg"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇦🇹_2"
    type: vless
    server: "147.45.41.193"
    port: 8443
    uuid: "eec2f6a7-c10f-43b0-b133-61f9bf9bbc27"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "amazon.de"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "17riEzmqVZyqgLiJkEITsiJc0NcXDfPq6RzQJmH830c"
      short-id: "ef01859eafef126d"
    flow: "xtls-rprx-vision"
  - name: "🇦🇹_3"
    type: vless
    server: "87.251.69.114"
    port: 443
    uuid: "cf80b5fc-c445-0008-87e6-f8a22ad10d81"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "at.monkeyisland.xyz"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "2AKBmK0PMf2zUMhRo1Ad-WNf_XoRk3AN-SGo6ZdhxA4"
      short-id: "ecca56e9a9963ed7"
    flow: "xtls-rprx-vision"
  - name: "🇦🇹_4"
    type: vless
    server: "159.195.244.37"
    port: 2054
    uuid: "75079a7f-75b5-418b-8a65-f7b2f438cd4a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.ibm.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "l6_Nvc_H8uxGpNI3j3MxqlRoPBs313ENeVM4K3uP9BQ"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇦🇹_5"
    type: vless
    server: "152.53.114.186"
    port: 443
    uuid: "ab7d5ea9-6eca-47c3-b14b-67378fc2d7c2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "as.tunnelx.space"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "UO3EObgU3xUrhIGEE0gfCn5ZOz8YxNcwwW6ZaYzD3SA"
      short-id: "4e9b0c2d1a3f5768"
    flow: "xtls-rprx-vision"
  - name: "🇦🇹_6"
    type: vless
    server: "141.227.164.161"
    port: 443
    uuid: "0bc31c7f-1ee2-4dd3-929b-b61ae780eb3c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "at.sellflow.org"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇦🇹_7"
    type: vless
    server: "152.53.1.40"
    port: 443
    uuid: "edde565e-41f5-400e-84ea-7b87a3e84488"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "at.quattro-tech.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "10rVZPoOUP1TlQviIAsQ_jAROX0fRQxH0C92nq_zGQc"
      short-id: "43dcff53849b81e6"
    flow: "xtls-rprx-vision"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇦🇹_1"
      - "🇦🇹_2"
      - "🇦🇹_3"
      - "🇦🇹_4"
      - "🇦🇹_5"
      - "🇦🇹_6"
      - "🇦🇹_7"


rules:
  - MATCH,PROXY
