name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇦🇺_1"
    type: vless
    server: "103.169.142.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime38.workers.dev"
  - name: "🇦🇺_2"
    type: vless
    server: "172.105.169.70"
    port: 443
    uuid: "03fcc618-b93d-6796-6aed-8a38c975d581"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "172.105.169.70"
  - name: "🇦🇺_3"
    type: vless
    server: "16.176.42.97"
    port: 443
    uuid: "1bc380b1-cff7-446f-b13f-5c0ad29fc75a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zero.csmaster.ggff.net"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇦🇺_4"
    type: trojan
    server: "wanted-marmoset.rooster465.autos"
    port: 443
    password: "AE62539071"
    sni: "wanted-marmoset.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_5"
    type: trojan
    server: "humorous-llama.rooster465.autos"
    port: 443
    password: "AE62539071"
    sni: "humorous-llama.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇦🇺_6"
    type: ss
    server: "104.156.233.234"
    port: 27116
    cipher: "chacha20-ietf-poly1305"
    password: "bIOoi5TuImG2KccxV7-jcA7Cez+vun-c_E"
    udp: true
  - name: "🇦🇺_7"
    type: ss
    server: "103.106.231.82"
    port: 5600
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true
  - name: "🇦🇺_8"
    type: ss
    server: "45.77.232.213"
    port: 15675
    cipher: "chacha20-ietf-poly1305"
    password: "TWG7J1KR5KsPaV5qZI+rieueKxxafZSpCH"
    udp: true
  - name: "🇦🇺_9"
    type: ss
    server: "103.106.231.82"
    port: 5600
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇦🇺_1"
      - "🇦🇺_2"
      - "🇦🇺_3"
      - "🇦🇺_4"
      - "🇦🇺_5"
      - "🇦🇺_6"
      - "🇦🇺_7"
      - "🇦🇺_8"
      - "🇦🇺_9"


rules:
  - MATCH,PROXY
