name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇦🇺_1"
    type: vless
    server: "103.169.142.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime38.workers.dev"
  - name: "🇦🇺_2"
    type: vless
    server: "172.105.169.70"
    port: 443
    uuid: "03fcc618-b93d-6796-6aed-8a38c975d581"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "172.105.169.70"
  - name: "🇦🇺_3"
    type: vless
    server: "au1.gsafevpnapi.com"
    port: 20270
    uuid: "6eef3a79-22bc-4086-b5e6-95e07db73016"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.yahoo.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "RHLiKldLu3DONcQoX4Kjs7Xmd2K25ndVbw4pwxe45XE"
      short-id: "e6a5a4a9115456de"
    flow: "xtls-rprx-vision"
  - name: "🇦🇺_4"
    type: vless
    server: "51.161.204.244"
    port: 443
    uuid: "36e89875-9c53-482b-bc41-d3890e9da176"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "gCAazs5uxNuMZIxfDdw8wPE0nwKY4QfBfBkQveKAkEk"
      short-id: "0ad08b47f498efd2"
    flow: "xtls-rprx-vision"
  - name: "🇦🇺_5"
    type: vless
    server: "192.65.217.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime37.workers.dev"
  - name: "🇦🇺_6"
    type: vless
    server: "192.65.217.123"
    port: 443
    uuid: "1d16c6e0-1bbe-435b-b661-90043fee999c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "notls.lukongtou.eu.org"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇦🇺_7"
    type: vless
    server: "au1.gsafevpnapi.com"
    port: 20270
    uuid: "38b8e2fb-b9a0-40a6-b42c-335def2765cf"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.yahoo.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "RHLiKldLu3DONcQoX4Kjs7Xmd2K25ndVbw4pwxe45XE"
      short-id: "e6a5a4a9115456de"
    flow: "xtls-rprx-vision"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇦🇺_1"
      - "🇦🇺_2"
      - "🇦🇺_3"
      - "🇦🇺_4"
      - "🇦🇺_5"
      - "🇦🇺_6"
      - "🇦🇺_7"


rules:
  - MATCH,PROXY
