name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇦🇺_1"
    type: vless
    server: "34.87.229.148"
    port: 443
    uuid: "4f865f35-cf47-4e7f-a7e6-8882511a1b36"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "OgTkmAQdLjipA9oLloxbU5BAX3hPjzbvkEGHF4aZ8z4"
      short-id: "8a7d5e0248cdb1b1"
  - name: "🇦🇺_2"
    type: vless
    server: "172.105.169.70"
    port: 443
    uuid: "03fcc618-b93d-6796-6aed-8a38c975d581"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "172.105.169.70"
  - name: "🇦🇺_3"
    type: vless
    server: "152.67.101.72"
    port: 23010
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    network: ws
    ws-opts:
      path: "/books?ed=2560fp=chrome"
      headers:
        Host: "cdn8848.776676.xyz"
  - name: "🇦🇺_4"
    type: vless
    server: "192.65.217.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime37.workers.dev"
  - name: "🇦🇺_5"
    type: vless
    server: "123.51.23.113"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/event/link?ed=2560"
      headers:
        Host: "cdn8848.776676.xyz"
  - name: "🇦🇺_6"
    type: vless
    server: "103.136.146.73"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    network: ws
    ws-opts:
      path: "/url/archives?ed=2560fp=chrome"
      headers:
        Host: "cdn8848.776676.xyz"
  - name: "🇦🇺_7"
    type: vless
    server: "51.161.204.244"
    port: 443
    uuid: "36e89875-9c53-482b-bc41-d3890e9da176"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "gCAazs5uxNuMZIxfDdw8wPE0nwKY4QfBfBkQveKAkEk"
      short-id: "0ad08b47f498efd2"
    flow: "xtls-rprx-vision"
  - name: "🇦🇺_8"
    type: vless
    server: "34.87.244.111"
    port: 443
    uuid: "325bc1be-0cb7-4cf7-bd35-a79ded91bbbd"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "fsdIMU2apN1C_NbkL7mHTsBKEfhwbDhgCRcB8ICf03E"
      short-id: "d725f0dd8cce210f"
  - name: "🇦🇺_9"
    type: vless
    server: "103.169.142.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime38.workers.dev"
  - name: "🇦🇺_10"
    type: vless
    server: "192.65.217.123"
    port: 443
    uuid: "1d16c6e0-1bbe-435b-b661-90043fee999c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "notls.lukongtou.eu.org"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇦🇺_11"
    type: vless
    server: "202.166.187.132"
    port: 443
    uuid: "8be20011-59b1-4118-91ed-83e8e6b662cd"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "f.yoptybla.ru"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "f.yoptybla.ru"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇦🇺_1"
      - "🇦🇺_2"
      - "🇦🇺_3"
      - "🇦🇺_4"
      - "🇦🇺_5"
      - "🇦🇺_6"
      - "🇦🇺_7"
      - "🇦🇺_8"
      - "🇦🇺_9"
      - "🇦🇺_10"
      - "🇦🇺_11"


rules:
  - MATCH,PROXY
