name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇧🇪_1"
    type: vless
    server: "109.69.218.168"
    port: 443
    uuid: "c28ee61d-0d43-4e69-8e6a-6397ed0ffc03"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "agile-raptor.cdn.cachefleet.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "cv_KJnMzQUZruACPbH-BCgLWrYqPm2dbUymg-gW_sVc"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇧🇪_2"
    type: vless
    server: "109.69.218.164"
    port: 443
    uuid: "c28ee61d-0d43-4e69-8e6a-6397ed0ffc03"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zealous-vortex.cdn.cachefleet.com"
    client-fingerprint: "random"
    reality-opts:
      public-key: "cv_KJnMzQUZruACPbH-BCgLWrYqPm2dbUymg-gW_sVc"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇧🇪_3"
    type: vless
    server: "109.69.218.216"
    port: 443
    uuid: "2a12bb81-f3a3-41bb-99ab-36febf676b4a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "kind-wolf.cdn.cachefleet.com"
    client-fingerprint: "randomized"
    reality-opts:
      public-key: "8hse7wRRL-F66rQ-aAeetKTw0MSeJC7Rr6EaDeLzdCU"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇧🇪_4"
    type: vless
    server: "109.69.218.206"
    port: 443
    uuid: "2a12bb81-f3a3-41bb-99ab-36febf676b4a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "kind-wolf.cdn.cachefleet.com"
    client-fingerprint: "random"
    reality-opts:
      public-key: "8hse7wRRL-F66rQ-aAeetKTw0MSeJC7Rr6EaDeLzdCU"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇧🇪_5"
    type: vless
    server: "109.69.218.208"
    port: 443
    uuid: "2a12bb81-f3a3-41bb-99ab-36febf676b4a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "kind-wolf.cdn.cachefleet.com"
    client-fingerprint: "randomized"
    reality-opts:
      public-key: "8hse7wRRL-F66rQ-aAeetKTw0MSeJC7Rr6EaDeLzdCU"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇧🇪_6"
    type: trojan
    server: "94.126.225.96"
    port: 443
    password: "JaFKnqNcvnBT63t3rquidGsln"
    sni: "hl-freedom-1.undef.network"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇧🇪_1"
      - "🇧🇪_2"
      - "🇧🇪_3"
      - "🇧🇪_4"
      - "🇧🇪_5"
      - "🇧🇪_6"


rules:
  - MATCH,PROXY
