name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇧🇬_1"
    type: vless
    server: "89.117.112.40"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime11.workers.dev"
  - name: "🇧🇬_2"
    type: vless
    server: "45.142.120.40"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "vms.lifetime08.workers.dev"
  - name: "🇧🇬_3"
    type: vless
    server: "bg3.mediacorp.fyi"
    port: 443
    uuid: "c623d17f-6f69-4c32-9edc-919da41fe21a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bg3.mediacorp.fyi"
    client-fingerprint: "ios"
    network: grpc
    grpc-opts:
      grpc-service-name: "mobile.api.Event"
  - name: "🇧🇬_4"
    type: vless
    server: "89.117.112.4"
    port: 80
    uuid: "424fa201-3f94-479e-b533-d5257cf9a207"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=Telegram🇨🇳 @VPNine1"
      headers:
        Host: "floral-thunder-10d3.82-67d.workers.dev"
  - name: "🇧🇬_5"
    type: vless
    server: "srv.mediahappy.org"
    port: 443
    uuid: "c623d17f-6f69-4c32-9edc-919da41fe21a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "srv.mediahappy.org"
    client-fingerprint: "firefox"
    network: grpc
    grpc-opts:
      grpc-service-name: "edge.v1.MetricsService"
  - name: "🇧🇬_6"
    type: vless
    server: "108.165.233.223"
    port: 443
    uuid: "2388e166-3890-33ae-f77e-efac00000001"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "netlivpn4813.ddhshhshs.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN"
      headers:
        Host: "netlivpn4813.ddhshhshs.workers.dev"
  - name: "🇧🇬_7"
    type: vless
    server: "89.117.112.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "vms.lifetime11.workers.dev"
  - name: "🇧🇬_8"
    type: vless
    server: "108.165.233.223"
    port: 443
    uuid: "2388e166-3890-33ae-f77e-efac00000003"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "netlivpn4813.ddhshhshs.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN-NetliVPN"
      headers:
        Host: "netlivpn4813.ddhshhshs.workers.dev"
  - name: "🇧🇬_9"
    type: vless
    server: "45.142.120.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime08.workers.dev"
  - name: "🇧🇬_10"
    type: vless
    server: "grid.mediahappy.org"
    port: 443
    uuid: "c623d17f-6f69-4c32-9edc-919da41fe21a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "grid.mediahappy.org"
    client-fingerprint: "chrome"
    network: grpc
    grpc-opts:
      grpc-service-name: "stats.v2.SyncService"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇧🇬_1"
      - "🇧🇬_2"
      - "🇧🇬_3"
      - "🇧🇬_4"
      - "🇧🇬_5"
      - "🇧🇬_6"
      - "🇧🇬_7"
      - "🇧🇬_8"
      - "🇧🇬_9"
      - "🇧🇬_10"


rules:
  - MATCH,PROXY
