name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇧🇬_1"
    type: vless
    server: "89.117.112.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime11.workers.dev"
  - name: "🇧🇬_2"
    type: vless
    server: "89.117.112.40"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime11.workers.dev"
  - name: "🇧🇬_3"
    type: vless
    server: "45.9.156.103"
    port: 443
    uuid: "e633de28-bfc0-4aca-aa67-e2e12e2c9e58"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "mzone.bg.3cloudhost.com"
    client-fingerprint: "safari"
    reality-opts:
      public-key: "SARDrN_d46PsugT2k5ILoQAJqaA1eCOZhe1BjKMonj8"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇧🇬_4"
    type: vless
    server: "103.249.134.29"
    port: 443
    uuid: "04c808e2-0b59-47b0-a54b-32fc7ef1c902"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "free.cndyw.ggff.net"
    client-fingerprint: "random"
    network: ws
    ws-opts:
      path: "pyip=bpb.yousef.isegaro.com"
      headers:
        Host: "free.cndyw.ggff.net"
  - name: "🇧🇬_5"
    type: vless
    server: "89.117.112.4"
    port: 80
    uuid: "424fa201-3f94-479e-b533-d5257cf9a207"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=Telegram🇨🇳 @VPNine1"
      headers:
        Host: "floral-thunder-10d3.82-67d.workers.dev"
  - name: "🇧🇬_6"
    type: vless
    server: "45.142.120.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime08.workers.dev"
  - name: "🇧🇬_7"
    type: vless
    server: "45.141.235.191"
    port: 443
    uuid: "6db6b948-655f-4f68-a9e7-865050e05b31"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cats-n-dogs.rumainco.cl"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "mGPCrFElfsioK3y3nOyW66ahpIocDnnyzfUnoN7ULFc"
      short-id: "c2cdd5"
    flow: "xtls-rprx-vision"
  - name: "🇧🇬_8"
    type: vless
    server: "131.123.39.29"
    port: 443
    uuid: "54ee5e59-55a3-4599-83ff-0c67b3f411b2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sheetpeek.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "pX9uknHGLC9I26TT5kq4bIAljtX2AGWLK23EMgn6xFo"
      short-id: "84be686ea1d16478"
    flow: "xtls-rprx-vision"
  - name: "🇧🇬_9"
    type: vless
    server: "131.123.41.18"
    port: 443
    uuid: "54ee5e59-55a3-4599-83ff-0c67b3f411b2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sheetpeek.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "pX9uknHGLC9I26TT5kq4bIAljtX2AGWLK23EMgn6xFo"
      short-id: "84be686ea1d16478"
    flow: "xtls-rprx-vision"
  - name: "🇧🇬_10"
    type: vless
    server: "104.152.48.248"
    port: 443
    uuid: "b940be1b-3998-45d2-bf7b-06e7b6c4987a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "kkkk-8oc.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/?ed=2048"
      headers:
        Host: "kkkk-8oc.pages.dev"
  - name: "🇧🇬_11"
    type: vless
    server: "45.142.120.40"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime08.workers.dev"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇧🇬_1"
      - "🇧🇬_2"
      - "🇧🇬_3"
      - "🇧🇬_4"
      - "🇧🇬_5"
      - "🇧🇬_6"
      - "🇧🇬_7"
      - "🇧🇬_8"
      - "🇧🇬_9"
      - "🇧🇬_10"
      - "🇧🇬_11"


rules:
  - MATCH,PROXY
