name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇨🇭_1"
    type: vless
    server: "45.90.59.15"
    port: 443
    uuid: "3950b45e-740d-4dca-ac95-505ec8534592"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "P7S4UPFlQbmiBr4txyy8NZIMTrmO3UdxyH16WBU-YzY"
      short-id: "19253fae84102271"
    flow: "xtls-rprx-vision"
  - name: "🇨🇭_2"
    type: vless
    server: "83.228.222.203"
    port: 443
    uuid: "0b21158e-00f5-4a2f-b242-e3e5574f68a0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bunny.net"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "B-q_vYkpKjiiaHyUfr7NutnusdvsmoWEeyr0QJfTfmw"
      short-id: "447abeb4fb111a9c"
    network: grpc
    grpc-opts:
      grpc-service-name: ""
  - name: "🇨🇭_3"
    type: vless
    server: "89.127.196.71"
    port: 443
    uuid: "51a0af77-a60c-4d9b-81a4-f50e1b38d90b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cf3.schzyc.cc.cd"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/proxyip=ProxyIP.CMLiussss.net"
      headers:
        Host: "cf3.schzyc.cc.cd"
  - name: "🇨🇭_4"
    type: vless
    server: "179.237.103.152"
    port: 443
    uuid: "e0bd9dfa-0cf9-47c0-92ac-7dba08ebcff8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "8PZTYkhNhSgagVdaI-iqSCPXJwDhHU23IUwZIu08zH4"
      short-id: "9de8ae53dabf1dc2"
    flow: "xtls-rprx-vision"
  - name: "🇨🇭_5"
    type: vless
    server: "83.228.246.83"
    port: 443
    uuid: "0b21158e-00f5-4a2f-b242-e3e5574f68a0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bunny.net"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "B-q_vYkpKjiiaHyUfr7NutnusdvsmoWEeyr0QJfTfmw"
      short-id: "447abeb4fb111a9c"
    network: grpc
    grpc-opts:
      grpc-service-name: ""
  - name: "🇨🇭_6"
    type: vless
    server: "ch.zango.tech"
    port: 443
    uuid: "0b21158e-00f5-4a2f-b242-e3e5574f68a0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bunny.net"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "B-q_vYkpKjiiaHyUfr7NutnusdvsmoWEeyr0QJfTfmw"
      short-id: "447abeb4fb111a9c"
    network: grpc
    grpc-opts:
      grpc-service-name: ""
  - name: "🇨🇭_7"
    type: vless
    server: "208.69.78.217"
    port: 2053
    uuid: "c0dd6d59-1573-43af-8b70-1470b2632a6d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "A49ue7zXSusJZdErPAewg3jqGdUFIO1a9xOunEKJfC0"
      short-id: "ad86e2d52ff40ebd"
  - name: "🇨🇭_8"
    type: ss
    server: "132.243.175.144"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "e8KgS8fD0yDqYFpgN4G5piCOt9aFyqA3"
    udp: true
  - name: "🇨🇭_9"
    type: ss
    server: "132.243.175.144"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "e8KgS8fD0yDqYFpgN4G5piCOt9aFyqA3"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇨🇭_1"
      - "🇨🇭_2"
      - "🇨🇭_3"
      - "🇨🇭_4"
      - "🇨🇭_5"
      - "🇨🇭_6"
      - "🇨🇭_7"
      - "🇨🇭_8"
      - "🇨🇭_9"


rules:
  - MATCH,PROXY
