name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇨🇭_1"
    type: vless
    server: "193.151.108.186"
    port: 443
    uuid: "c245122a-f149-4e32-8eaa-e875e88a5ab6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "shop.magazinetut.online"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇨🇭_2"
    type: vless
    server: "176.65.144.248"
    port: 443
    uuid: "62a08ea5-0564-47b4-a92c-25be07ad6358"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "360.yandex.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "ne8wv6o6AYcQoVvz30PiTjSxviGa3_Kw5ClIEDdg-3A"
      short-id: "6ba85179e30d4fc2"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇨🇭_3"
    type: vless
    server: "31.76.4.103"
    port: 443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eu-central.cendora.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "b-Cm9hX-3UHsS1L_lnUB6AMjuKhlN1IDdBbZ506itjI"
      short-id: "00bca5982f82d083"
    flow: "xtls-rprx-vision"
  - name: "🇨🇭_4"
    type: vless
    server: "178.83.226.55"
    port: 443
    uuid: "2a77a470-315c-493d-b690-59b814a804cb"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sellflow.org"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇨🇭_5"
    type: vless
    server: "176.65.144.248"
    port: 443
    uuid: "fa98f221-29e1-4a7e-8797-3bf294aeda35"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "360.yandex.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "ne8wv6o6AYcQoVvz30PiTjSxviGa3_Kw5ClIEDdg-3A"
      short-id: "6ba85179e30d4fc2"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇨🇭_6"
    type: vless
    server: "45.90.56.231"
    port: 443
    uuid: "e2b8f727-c5ee-47e1-8f1b-7c5c61479ce0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "KrFnWxAwVGL6tuj1JE0qpykLzY4aOFjyK3OaymF_hT0"
      short-id: "e2e66f4537770cef"
    flow: "xtls-rprx-vision"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇨🇭_1"
      - "🇨🇭_2"
      - "🇨🇭_3"
      - "🇨🇭_4"
      - "🇨🇭_5"
      - "🇨🇭_6"


rules:
  - MATCH,PROXY
