name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇨🇿_1"
    type: vless
    server: "153.76.185.159"
    port: 3090
    uuid: "ea723504-e8df-4f23-b35f-c93961d5128a"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "vless"
  - name: "🇨🇿_2"
    type: vless
    server: "85.137.166.6"
    port: 443
    uuid: "51a0af77-a60c-4d9b-81a4-f50e1b38d90b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cf3.schzyc.cc.cd"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/proxyip=ProxyIP.CMLiussss.net"
      headers:
        Host: "cf3.schzyc.cc.cd"
  - name: "🇨🇿_3"
    type: vless
    server: "194.87.59.5"
    port: 2085
    uuid: "ea723504-e8df-4f23-b35f-c93961d5128a"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "vless"
  - name: "🇨🇿_4"
    type: vless
    server: "153.76.185.163"
    port: 3090
    uuid: "ea723504-e8df-4f23-b35f-c93961d5128a"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "vless"
  - name: "🇨🇿_5"
    type: vless
    server: "153.76.185.162"
    port: 3090
    uuid: "ea723504-e8df-4f23-b35f-c93961d5128a"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "vless"
  - name: "🇨🇿_6"
    type: vless
    server: "194.87.59.29"
    port: 2085
    uuid: "ea723504-e8df-4f23-b35f-c93961d5128a"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "vless"
  - name: "🇨🇿_7"
    type: vless
    server: "31.76.7.227"
    port: 443
    uuid: "d0e771c5-024e-4393-bb90-4a3e3c561656"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "origin.vpnoodles.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "nIL5EeUo2XUkCaLJGbzgRm6zhF-96kWvV2VmhEt3CX4"
      short-id: "4af4102cb26e59"
    flow: "xtls-rprx-vision"
  - name: "🇨🇿_8"
    type: vless
    server: "194.87.59.20"
    port: 2085
    uuid: "a641fd38-0ad7-40bf-9a56-6715c1787be3"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "vless"
  - name: "🇨🇿_9"
    type: vless
    server: "153.76.185.108"
    port: 3090
    uuid: "14e227c3-5a83-4b4d-a41a-e5f499c79415"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "vless"
  - name: "🇨🇿_10"
    type: vless
    server: "45.146.90.85"
    port: 443
    uuid: "eec2f6a7-c10f-43b0-b133-61f9bf9bbc27"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amazon.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "bPbAdn6ogLbiv5cRe5d12EL7FhooAIVrC3-fg90P-Bw"
      short-id: "72104d27a0f5f62e"
    flow: "xtls-rprx-vision"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇨🇿_1"
      - "🇨🇿_2"
      - "🇨🇿_3"
      - "🇨🇿_4"
      - "🇨🇿_5"
      - "🇨🇿_6"
      - "🇨🇿_7"
      - "🇨🇿_8"
      - "🇨🇿_9"
      - "🇨🇿_10"


rules:
  - MATCH,PROXY
