name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇩🇰_1"
    type: vless
    server: "193.181.216.117"
    port: 2053
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/payment?ed=2560"
      headers:
        Host: "cdn8848.776676.xyz"
  - name: "🇩🇰_2"
    type: vless
    server: "den-khad-nxt.ramzshadi.ir"
    port: 43312
    uuid: "8124ddbb-bf22-49d9-945d-2e72c554deb2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "play.google.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "06vBWFA7tgljTVI9N1pY6L6Ls88me171hrKzeH9-7EQ"
      short-id: "194eb312877c9c35"
    flow: "xtls-rprx-vision"
  - name: "🇩🇰_3"
    type: vless
    server: "den-khad-nxt.ramzshadi.ir"
    port: 31770
    uuid: "8124ddbb-bf22-49d9-945d-2e72c554deb2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sheets.google.com"
    client-fingerprint: "ios"
    reality-opts:
      public-key: "GZqmhFHyMfIyRUi1k-2UDeJtjUakgZRhyXLhGLfL3Ws"
      short-id: "6a2a03e809012832"
    flow: "xtls-rprx-vision"
  - name: "🇩🇰_4"
    type: vless
    server: "45.148.30.11"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/season/classify?ed=2560"
      headers:
        Host: "cdn8848.776676.xyz"
  - name: "🇩🇰_5"
    type: ss
    server: "38.180.214.110"
    port: 5600
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true
  - name: "🇩🇰_6"
    type: ss
    server: "38.180.214.110"
    port: 5600
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇩🇰_1"
      - "🇩🇰_2"
      - "🇩🇰_3"
      - "🇩🇰_4"
      - "🇩🇰_5"
      - "🇩🇰_6"


rules:
  - MATCH,PROXY
