name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇪🇪_1"
    type: vless
    server: "45.80.110.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime51.workers.dev"
  - name: "🇪🇪_2"
    type: vless
    server: "94.183.170.135"
    port: 443
    uuid: "06c4e938-2954-478f-a870-ca1b163e30e9"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "🇪🇪_3"
    type: vless
    server: "94.183.170.135"
    port: 8443
    uuid: "06c4e938-2954-478f-a870-ca1b163e30e9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "estproxy4.lockdwn.com"
    client-fingerprint: "firefox"
  - name: "🇪🇪_4"
    type: vless
    server: "45.80.110.50"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "vms.lifetime51.workers.dev"
  - name: "🇪🇪_5"
    type: vless
    server: "45.80.108.236"
    port: 443
    uuid: "ef9d2063-0140-472b-8b17-ba02ba4b4435"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "lively-resonance-4e12.electrocellco-cf-059.workers.dev"
    network: ws
    ws-opts:
      path: "/proxyip"
      headers:
        Host: "lively-resonance-4e12.electrocellco-cf-059.workers.dev"
  - name: "🇪🇪_6"
    type: vless
    server: "95.85.224.51"
    port: 443
    uuid: "342ab7e4-5a89-0001-8809-304120d4aa83"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "max.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "WWeAHWUVD-phmnjNJ823cer0c4CMIbEs08AhsuEZmDc"
      short-id: "a696de84963656de"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_7"
    type: trojan
    server: "109.206.241.10"
    port: 449
    password: "oiiaB38ywjEHCWRs_O_a_1113_Il_KeyyyHop_Bes1"
    sni: "109.206.241.10"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇪🇪_1"
      - "🇪🇪_2"
      - "🇪🇪_3"
      - "🇪🇪_4"
      - "🇪🇪_5"
      - "🇪🇪_6"
      - "🇪🇪_7"


rules:
  - MATCH,PROXY
