name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇪🇪_1"
    type: vless
    server: "5.45.117.125"
    port: 443
    uuid: "c7e9c591-2764-423a-afca-efbd010fd396"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "freeuse.firta.ru"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "freeuse.firta.ru"
  - name: "🇪🇪_2"
    type: vless
    server: "94.183.170.135"
    port: 8443
    uuid: "06c4e938-2954-478f-a870-ca1b163e30e9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "estproxy4.lockdwn.com"
    client-fingerprint: "firefox"
  - name: "🇪🇪_3"
    type: vless
    server: "2.26.129.66"
    port: 443
    uuid: "74ed2afb-e8a5-4be1-b774-53b4c593f528"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ukrop.mycdn-me.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "gPTBA-gVUWAK9yziB_v_sGSncm0LwBQvEAsTQZK4jEE"
      short-id: "5a8e1a04f3d92b67"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_4"
    type: vless
    server: "94.183.170.231"
    port: 443
    uuid: "19f54e37-5fae-47f6-bc10-e71ccbc58389"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "🇪🇪_5"
    type: vless
    server: "estproxy4.lockdwn.com"
    port: 443
    uuid: "06c4e938-2954-478f-a870-ca1b163e30e9"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "🇪🇪_6"
    type: vless
    server: "94.183.170.231"
    port: 8443
    uuid: "19f54e37-5fae-47f6-bc10-e71ccbc58389"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "estproxy2.lockdwn.com"
    client-fingerprint: "firefox"
  - name: "🇪🇪_7"
    type: vless
    server: "45.80.108.123"
    port: 443
    uuid: "1d16c6e0-1bbe-435b-b661-90043fee999c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "notls.lukongtou.eu.org"
    network: ws
    ws-opts:
      path: "Telegram-WangCai2"
      headers:
        Host: "notls.lukongtou.eu.org"
  - name: "🇪🇪_8"
    type: vless
    server: "64.188.82.152"
    port: 443
    uuid: "7836b28e-8451-4596-ad3e-e3601b2335ba"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cloudflare.vhub.pro"
    client-fingerprint: "safari"
    network: ws
    ws-opts:
      path: "/websocket?ed=2560"
      headers:
        Host: "cloudflare.vhub.pro"
  - name: "🇪🇪_9"
    type: vless
    server: "94.183.170.135"
    port: 443
    uuid: "06c4e938-2954-478f-a870-ca1b163e30e9"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "🇪🇪_10"
    type: vless
    server: "38.244.154.149"
    port: 443
    uuid: "e911c552-3a98-41e0-b5fb-0dd3879887b7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vod.ensf.top"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/api/v1/irc"
      headers:
        Host: "vod.ensf.top"
  - name: "🇪🇪_11"
    type: vless
    server: "95.85.224.51"
    port: 443
    uuid: "342ab7e4-5a89-0001-8809-304120d4aa83"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "max.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "WWeAHWUVD-phmnjNJ823cer0c4CMIbEs08AhsuEZmDc"
      short-id: "a696de84963656de"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_12"
    type: trojan
    server: "109.206.241.10"
    port: 449
    password: "oiiaB38ywjEHCWRs_O_a_1113_Il_KeyyyHop_Bes1"
    sni: "russiapower.accesscam.org"
    skip-cert-verify: true
    udp: true
  - name: "🇪🇪_13"
    type: trojan
    server: "80.77.25.142"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇪🇪_1"
      - "🇪🇪_2"
      - "🇪🇪_3"
      - "🇪🇪_4"
      - "🇪🇪_5"
      - "🇪🇪_6"
      - "🇪🇪_7"
      - "🇪🇪_8"
      - "🇪🇪_9"
      - "🇪🇪_10"
      - "🇪🇪_11"
      - "🇪🇪_12"
      - "🇪🇪_13"


rules:
  - MATCH,PROXY
