name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇪🇪_1"
    type: vless
    server: "185.155.97.58"
    port: 45176
    uuid: "dc7940e0-6bff-45e3-853d-4007561803c3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.googletagmanager.com"
    reality-opts:
      public-key: "A1Qf_rMG4KDfLzfCK-M5R9qW_0uThfeSosQnv6LBL1M"
      short-id: "8433cb66b6c3ab6d"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_2"
    type: vless
    server: "95.85.224.51"
    port: 443
    uuid: "342ab7e4-5a89-0001-8809-304120d4aa83"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "max.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "WWeAHWUVD-phmnjNJ823cer0c4CMIbEs08AhsuEZmDc"
      short-id: "a696de84963656de"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_3"
    type: vless
    server: "45.80.108.7"
    port: 8443
    uuid: "7967bf59-57e3-4cde-9898-527b0fe60022"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "speed.dulacloud.store"
    network: ws
    ws-opts:
      path: "/dula?Telegram-WangCai2"
      headers:
        Host: "speed.dulacloud.store"
  - name: "🇪🇪_4"
    type: vless
    server: "95.85.224.76"
    port: 443
    uuid: "76713d07-5a6b-49c2-abd8-bc450a2fa7fc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ee-download.spectrum.vu"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "P2MV0I11JvKg-G3wfg64YVGUEh0Wvy6C4MTVsMPWdyQ"
      short-id: "7b1c7d9a3f2a"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_5"
    type: vless
    server: "185.155.97.241"
    port: 443
    uuid: "0b9bcbc1-b289-4a64-86fa-a5b731b65384"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "web.max.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "SJkDT_L0eziQR2afDGrkN7-uRxjYu6bZxIGXlKeCvX4"
      short-id: "15aa18f971da1f81"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_6"
    type: vless
    server: "31.56.187.165"
    port: 8113
    uuid: "5c6d8045-9de9-45e4-b495-463fc3f1a828"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "westondigita.cloud"
    client-fingerprint: "edge"
    reality-opts:
      public-key: "1XNcujMbWdVkVnPV4JvvIllMFdRXToudea_mqzXcMWg"
      short-id: "a4f8c92d"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇪🇪_7"
    type: vless
    server: "45.80.110.7"
    port: 8443
    uuid: "7967bf59-57e3-4cde-9898-527b0fe60022"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "speed.dulacloud.store"
    network: ws
    ws-opts:
      path: "/dula?Telegram-WangCai2"
      headers:
        Host: "speed.dulacloud.store"
  - name: "🇪🇪_8"
    type: vless
    server: "64.188.82.57"
    port: 443
    uuid: "76713d07-5a6b-49c2-abd8-bc450a2fa7fc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ee-download.spectrum.vu"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "P2MV0I11JvKg-G3wfg64YVGUEh0Wvy6C4MTVsMPWdyQ"
      short-id: "7b1c7d9a3f2a"
    flow: "xtls-rprx-vision"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇪🇪_1"
      - "🇪🇪_2"
      - "🇪🇪_3"
      - "🇪🇪_4"
      - "🇪🇪_5"
      - "🇪🇪_6"
      - "🇪🇪_7"
      - "🇪🇪_8"


rules:
  - MATCH,PROXY
