name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇪🇸_1"
    type: vless
    server: "170.168.97.3"
    port: 8443
    uuid: "e6d41d6f-d58a-7650-bba4-d7f0dde3ba4d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "download.nvidia.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "D2SXHZRRYM0WcFChGWd57XB-U73aIsGfMpe2-Gq5XSs"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "TunService"
  - name: "🇪🇸_2"
    type: vless
    server: "170.168.97.5"
    port: 8443
    uuid: "c6f220ed-41f2-21ba-438c-80f05ebbf92a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "download.nvidia.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "D2SXHZRRYM0WcFChGWd57XB-U73aIsGfMpe2-Gq5XSs"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "TunService"
  - name: "🇪🇸_3"
    type: vless
    server: "170.168.97.3"
    port: 993
    uuid: "e6d41d6f-d58a-7650-bba4-d7f0dde3ba4d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "download.nvidia.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "D2SXHZRRYM0WcFChGWd57XB-U73aIsGfMpe2-Gq5XSs"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇪🇸_4"
    type: vless
    server: "78.17.180.110"
    port: 443
    uuid: "06d44c57-8e1a-41f4-b9c4-65d35869e078"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "isp05.skorostnet.space"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "aBNWkd8CVkuimbtzgsDNsIUIENI-PQuKkpUInLncz2o"
      short-id: "fdda9806fe5d8584"
    flow: "xtls-rprx-vision"
  - name: "🇪🇸_5"
    type: vless
    server: "85.90.217.42"
    port: 443
    uuid: "03fcc618-b93d-6796-6aed-8a38c975d581"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "85.90.217.42"
  - name: "🇪🇸_6"
    type: vless
    server: "78.17.180.106"
    port: 443
    uuid: "06d44c57-8e1a-41f4-b9c4-65d35869e078"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "isp04.skorostnet.space"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "aBNWkd8CVkuimbtzgsDNsIUIENI-PQuKkpUInLncz2o"
      short-id: "fdda9806fe5d8584"
    flow: "xtls-rprx-vision"
  - name: "🇪🇸_7"
    type: trojan
    server: "65.20.102.54"
    port: 443
    password: "842b5f9dd11e458d8613c907c4cc5723"
    sni: "www.gpt123.one"
    skip-cert-verify: true
    udp: true
  - name: "🇪🇸_8"
    type: trojan
    server: "185.18.250.252"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "🇪🇸_9"
    type: trojan
    server: "193.148.19.213"
    port: 52794
    password: "2eutknankxtbgkwcajzt"
    sni: "193.148.19.213"
    skip-cert-verify: true
    udp: true
  - name: "🇪🇸_10"
    type: trojan
    server: "193.148.19.210"
    port: 52794
    password: "2eutknankxtbgkwcajzt"
    sni: "www.vk.com"
    skip-cert-verify: true
    udp: true
  - name: "🇪🇸_11"
    type: ss
    server: "108.181.121.226"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "WSyL4XTwNsdv"
    udp: true
  - name: "🇪🇸_12"
    type: ss
    server: "108.181.121.226"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "WSyL4XTwNsdv"
    udp: true
  - name: "🇪🇸_13"
    type: ss
    server: "140.174.184.5"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "qItG8SueYQcP"
    udp: true
  - name: "🇪🇸_14"
    type: ss
    server: "82.38.31.155"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "🇪🇸_15"
    type: ss
    server: "140.174.184.5"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "qItG8SueYQcP"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇪🇸_1"
      - "🇪🇸_2"
      - "🇪🇸_3"
      - "🇪🇸_4"
      - "🇪🇸_5"
      - "🇪🇸_6"
      - "🇪🇸_7"
      - "🇪🇸_8"
      - "🇪🇸_9"
      - "🇪🇸_10"
      - "🇪🇸_11"
      - "🇪🇸_12"
      - "🇪🇸_13"
      - "🇪🇸_14"
      - "🇪🇸_15"


rules:
  - MATCH,PROXY
