name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇪🇸_1"
    type: vless
    server: "2.27.26.49"
    port: 443
    uuid: "710fc22f-06b2-4b6d-bb3e-f57c17b670a6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.ray-balance.space"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "d1NlaZfnsYjWfxRTqIBk1ldBUmdE-kRTEQ_sWd1JYwI"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇪🇸_2"
    type: vless
    server: "212.227.235.66"
    port: 2053
    uuid: "6fbdbd3c-7696-4b9a-9a10-bcecc26e0f6f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "XrPOJwmpnq8NeCXu6K68Mp59gQ56Dr4YYboxI70kqzA"
      short-id: "866af6e56606f2bc"
  - name: "🇪🇸_3"
    type: vless
    server: "185.18.250.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime47.workers.dev"
  - name: "🇪🇸_4"
    type: trojan
    server: "185.18.250.245"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "🇪🇸_5"
    type: ss
    server: "140.174.184.5"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "qItG8SueYQcP"
    udp: true
  - name: "🇪🇸_6"
    type: ss
    server: "140.174.184.5"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "qItG8SueYQcP"
    udp: true
  - name: "🇪🇸_7"
    type: ss
    server: "108.181.121.226"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "WSyL4XTwNsdv"
    udp: true
  - name: "🇪🇸_8"
    type: ss
    server: "108.181.121.226"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "WSyL4XTwNsdv"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇪🇸_1"
      - "🇪🇸_2"
      - "🇪🇸_3"
      - "🇪🇸_4"
      - "🇪🇸_5"
      - "🇪🇸_6"
      - "🇪🇸_7"
      - "🇪🇸_8"


rules:
  - MATCH,PROXY
