name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇪🇸_1"
    type: vless
    server: "196.245.52.148"
    port: 25155
    uuid: "441a29b2-d9aa-47d5-9209-0a9191479f9f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "zZb_VVAbcGA7TeSMUBuD8MB2O3yAwpDSPGEfSEIUsX4"
      short-id: "e4ba91df34fc3318"
    flow: "xtls-rprx-vision"
  - name: "🇪🇸_2"
    type: vless
    server: "45.150.195.35"
    port: 443
    uuid: "5dff1842-c02f-4dd4-b1ad-2e597b99dc31"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sp35.mech-pro.online"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "azv9I1WcbDAga3vWg62KSaRi1eRwZsDU4tg3T63al1o"
      short-id: "3ea0e22c"
    flow: "xtls-rprx-vision"
  - name: "🇪🇸_3"
    type: vless
    server: "assets-es.pleiades.codes"
    port: 443
    uuid: "e0b9fb0f-1bbd-478b-9580-c2294778338b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "assets-es.pleiades.codes"
    client-fingerprint: "firefox"
    network: grpc
    grpc-opts:
      grpc-service-name: "cdn.v1.AssetService"
  - name: "🇪🇸_4"
    type: vless
    server: "141.253.194.63"
    port: 443
    uuid: "9e3132b8-b595-444a-833a-2de44789f9d7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "shephe.dpdns.org"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "shephe.dpdns.org"
  - name: "🇪🇸_5"
    type: vless
    server: "185.218.17.127"
    port: 443
    uuid: "bc8446e7-ba8e-4dfd-92df-8681793fe31e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "corporate.amazon.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "QKaBb_u0KoNkMYbh9ljrxC9BDtnHyFoaMd4-s4xfKxQ"
      short-id: "33c0b6e213"
    flow: "xtls-rprx-vision"
  - name: "🇪🇸_6"
    type: vless
    server: "185.18.250.50"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "vms.lifetime47.workers.dev"
  - name: "🇪🇸_7"
    type: vless
    server: "92.118.127.16"
    port: 443
    uuid: "2412bd96-925b-43f2-81d1-0ed4f0793699"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sp1.extremumnews.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "Rz8XjYinCcpE7NLktJzNFL7eVSUxaFGuV2Zz82p7IRg"
      short-id: "908563a721d9bdcd"
    flow: "xtls-rprx-vision"
  - name: "🇪🇸_8"
    type: vless
    server: "185.18.250.123"
    port: 443
    uuid: "1d16c6e0-1bbe-435b-b661-90043fee999c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "notls.lukongtou.eu.org"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇪🇸_9"
    type: vless
    server: "185.18.250.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime47.workers.dev"
  - name: "🇪🇸_10"
    type: vless
    server: "sp66.mech-pro.online"
    port: 443
    uuid: "5dff1842-c02f-4dd4-b1ad-2e597b99dc31"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sp66.mech-pro.online"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "jbiddtGRgeBvlkjbuA3aU-WPjKgEX87tOVh1mFfvOUI"
      short-id: "16e0f049"
    flow: "xtls-rprx-vision"
  - name: "🇪🇸_11"
    type: vless
    server: "212.227.235.66"
    port: 2053
    uuid: "ead0dd61-d398-40ad-80d6-a0e1e516d7d3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "7Y6Xb5Ql_03K25x8yKUSOKI2JTOMyv2nyCcFza90uxk"
      short-id: "29e8dcd2b37aaa7f"
  - name: "🇪🇸_12"
    type: vless
    server: "185.232.205.66"
    port: 443
    uuid: "5dff1842-c02f-4dd4-b1ad-2e597b99dc31"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sp66.mech-pro.online"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "jbiddtGRgeBvlkjbuA3aU-WPjKgEX87tOVh1mFfvOUI"
      short-id: "16e0f049"
    flow: "xtls-rprx-vision"
  - name: "🇪🇸_13"
    type: vless
    server: "46.28.71.247"
    port: 443
    uuid: "12c53e32-e589-47d6-b857-e4132294f767"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "v4MuZIvFrTPT5GHMSaPryUAbIZlLstmsUTzmC1E-JTE"
      short-id: "0dfc23fe80778c00"
    flow: "xtls-rprx-vision"
  - name: "🇪🇸_14"
    type: vless
    server: "193.238.154.5"
    port: 443
    uuid: "e0b9fb0f-1bbd-478b-9580-c2294778338b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "assets-es.pleiades.codes"
    client-fingerprint: "firefox"
    network: grpc
    grpc-opts:
      grpc-service-name: "cdn.v1.AssetService"
  - name: "🇪🇸_15"
    type: trojan
    server: "185.18.250.252"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "🇪🇸_16"
    type: trojan
    server: "185.18.250.245"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "🇪🇸_17"
    type: trojan
    server: "185.114.72.31"
    port: 2053
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "🇪🇸_18"
    type: ss
    server: "108.181.121.226"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "WSyL4XTwNsdv"
    udp: true
  - name: "🇪🇸_19"
    type: ss
    server: "140.174.184.5"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "qItG8SueYQcP"
    udp: true
  - name: "🇪🇸_20"
    type: ss
    server: "140.174.184.5"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "qItG8SueYQcP"
    udp: true
  - name: "🇪🇸_21"
    type: ss
    server: "108.181.121.226"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "WSyL4XTwNsdv"
    udp: true
  - name: "🇪🇸_22"
    type: ss
    server: "82.38.31.155"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "🇪🇸_23"
    type: ss
    server: "108.181.121.226"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "WSyL4XTwNsdv"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇪🇸_1"
      - "🇪🇸_2"
      - "🇪🇸_3"
      - "🇪🇸_4"
      - "🇪🇸_5"
      - "🇪🇸_6"
      - "🇪🇸_7"
      - "🇪🇸_8"
      - "🇪🇸_9"
      - "🇪🇸_10"
      - "🇪🇸_11"
      - "🇪🇸_12"
      - "🇪🇸_13"
      - "🇪🇸_14"
      - "🇪🇸_15"
      - "🇪🇸_16"
      - "🇪🇸_17"
      - "🇪🇸_18"
      - "🇪🇸_19"
      - "🇪🇸_20"
      - "🇪🇸_21"
      - "🇪🇸_22"
      - "🇪🇸_23"


rules:
  - MATCH,PROXY
