name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇫🇷_1"
    type: vless
    server: "213.136.92.67"
    port: 443
    uuid: "af348651-1624-4710-b55f-0307a22d891f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "status.play.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "jvJPfOHtnr2sH79qG-rEtJHFbr36_7Ag7ARsUmtSDQo"
      short-id: "5030"
  - name: "🇫🇷_2"
    type: vless
    server: "89.208.97.226"
    port: 443
    uuid: "564082ff-cf3c-48db-9e10-8ad2312847b4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "node21.mxvpn.dev"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "TlpXTLz1Y-v8B6q9MX55U6eypjfL0LCSNE5zQP4yRHw"
      short-id: "bbc68cec8bb8d2e3"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_3"
    type: vless
    server: "89.208.113.16"
    port: 443
    uuid: "adce7c2a-3191-49ae-b61c-9b8258ea1b0e"
    udp: true
  - name: "🇫🇷_4"
    type: vless
    server: "62.210.91.10"
    port: 23576
    uuid: "48ff2b70-e180-582f-8866-d9a2edeed5f5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fuck.rkn"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s"
      short-id: "01"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_5"
    type: vless
    server: "77.221.152.100"
    port: 443
    uuid: "564082ff-cf3c-48db-9e10-8ad2312847b4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "node14.mxvpn.dev"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "TlpXTLz1Y-v8B6q9MX55U6eypjfL0LCSNE5zQP4yRHw"
      short-id: "bbc68cec8bb8d2e3"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_6"
    type: vless
    server: "usejh2.neobo-tooth.ru"
    port: 2083
    uuid: "70e20b2e-3b1f-4c25-9a3d-9240570391bb"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "usejh2.neobo-tooth.ru"
    client-fingerprint: "firefox"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇫🇷_7"
    type: vless
    server: "45.80.215.68"
    port: 443
    uuid: "03fcc618-b93d-6796-6aed-8a38c975d581"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "45.80.215.68"
  - name: "🇫🇷_8"
    type: vless
    server: "45.192.2.72"
    port: 443
    uuid: "219762a7-b918-4e2b-8a3d-d309ef98bb61"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "storage.yandex.net"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "1oUeBtHH4DskTM_jCh-6enWRkFMDX9l1OU5kWYl4kxA"
      short-id: "364994a6f61fc955"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_9"
    type: vless
    server: "node21.mxvpn.dev"
    port: 443
    uuid: "564082ff-cf3c-48db-9e10-8ad2312847b4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "node21.mxvpn.dev"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "TlpXTLz1Y-v8B6q9MX55U6eypjfL0LCSNE5zQP4yRHw"
      short-id: "bbc68cec8bb8d2e3"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_10"
    type: vless
    server: "nasnet-162191099-direct.mbghalibaf.com"
    port: 443
    uuid: "nasnet"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nasnet-162191099-direct.mbghalibaf.com"
    client-fingerprint: "chrome"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_11"
    type: vless
    server: "gr2.levikogjgfdd.ir"
    port: 443
    uuid: "25f3beef-a4b6-40bc-aa74-17a0f89f683c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "finite-node.rtxconfigz.com"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇫🇷_12"
    type: vless
    server: "162.19.10.99"
    port: 443
    uuid: "nasnet"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nasnet-162191099-direct.mbghalibaf.com"
    client-fingerprint: "chrome"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_13"
    type: vless
    server: "45.144.28.39"
    port: 2083
    uuid: "70e20b2e-3b1f-4c25-9a3d-9240570391bb"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "usejh2.neobo-tooth.ru"
    client-fingerprint: "ios"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇫🇷_14"
    type: vless
    server: "169.58.143.21"
    port: 443
    uuid: "25f3beef-a4b6-40bc-aa74-17a0f89f683c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "finite-node.rtxconfigz.com"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇫🇷_15"
    type: vless
    server: "162.19.10.99"
    port: 443
    uuid: "e8b1500b-e9e8-5492-8312-f4eadf7d0767"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nasnet-162191099-direct.mbghalibaf.com"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_16"
    type: vless
    server: "51.77.217.70"
    port: 2053
    uuid: "fae272a6-a184-4c91-83ed-771abdcff404"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "5Me9XEMwr9siyrnV5zPHYfxB3QLqw-OzNAOuzkFu1kw"
      short-id: "7af95330630a7327"
  - name: "🇫🇷_17"
    type: vless
    server: "node14.mxvpn.dev"
    port: 443
    uuid: "564082ff-cf3c-48db-9e10-8ad2312847b4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "node14.mxvpn.dev"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "TlpXTLz1Y-v8B6q9MX55U6eypjfL0LCSNE5zQP4yRHw"
      short-id: "bbc68cec8bb8d2e3"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_18"
    type: vless
    server: "node21.mxvpn.dev"
    port: 443
    uuid: "0772109c-a680-4896-b005-d86513194f96"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "node21.mxvpn.dev"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "TlpXTLz1Y-v8B6q9MX55U6eypjfL0LCSNE5zQP4yRHw"
      short-id: "bbc68cec8bb8d2e3"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_19"
    type: vless
    server: "145.223.68.58"
    port: 443
    uuid: "edb50d20-2d3e-4c1e-8a75-a17168a89aa5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "edge"
    reality-opts:
      public-key: "qc2DcqT9zPPZr6ePZ7ukxACWrYhRNIBjDIjCK7veyQg"
      short-id: "a44ff7d2e80213c2"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_20"
    type: vless
    server: "45.144.28.39"
    port: 2053
    uuid: "70e20b2e-3b1f-4c25-9a3d-9240570391bb"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vk.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "dRLd_E_GYCkCcwxLN5EcRQYsREKqisb26_ZSehxUpWY"
      short-id: "1eb8ea8dae937ae0"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_21"
    type: vless
    server: "141.101.121.158"
    port: 443
    uuid: "3bb6fd82-3a15-eaea-6168-4dac2b70079e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nahan-fog-af01.dfghttr2012.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/sync"
      headers:
        Host: "nahan-fog-af01.dfghttr2012.workers.dev"
  - name: "🇫🇷_22"
    type: vless
    server: "89.208.97.226"
    port: 443
    uuid: "0772109c-a680-4896-b005-d86513194f96"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "node21.mxvpn.dev"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "TlpXTLz1Y-v8B6q9MX55U6eypjfL0LCSNE5zQP4yRHw"
      short-id: "bbc68cec8bb8d2e3"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_23"
    type: vless
    server: "62.210.91.2"
    port: 23576
    uuid: "48ff2b70-e180-582f-8866-d9a2edeed5f5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fuck.rkn"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s"
      short-id: "01"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_24"
    type: vless
    server: "45.144.28.39"
    port: 2096
    uuid: "70e20b2e-3b1f-4c25-9a3d-9240570391bb"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "🇫🇷_25"
    type: vless
    server: "161.97.160.224"
    port: 443
    uuid: "b81b4d1b-7f20-48f1-82dc-d24bef898cab"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "passport.yandex.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "33zaT3jHXjtynSQ0Ucw9bK92-XH2zolJmuIeZ1XyZB0"
      short-id: "e6"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_26"
    type: vless
    server: "164.68.127.108"
    port: 24144
    uuid: "7e85ed3f-3829-45b1-8b1c-6a2e45ebc967"
    udp: true
  - name: "🇫🇷_27"
    type: vless
    server: "77.221.152.100"
    port: 443
    uuid: "0772109c-a680-4896-b005-d86513194f96"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "node14.mxvpn.dev"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "TlpXTLz1Y-v8B6q9MX55U6eypjfL0LCSNE5zQP4yRHw"
      short-id: "bbc68cec8bb8d2e3"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_28"
    type: vless
    server: "141.101.122.147"
    port: 443
    uuid: "c4edb87e-8544-4fa4-bd1c-b0cda9a34b46"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "a.cwvps.eu.org"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/ws"
      headers:
        Host: "a.cwvps.eu.org"
  - name: "🇫🇷_29"
    type: trojan
    server: "194.9.172.236"
    port: 1105
    password: "kakashka13222"
    sni: "194.9.172.236"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇷_30"
    type: trojan
    server: "172.239.19.94"
    port: 28443
    password: "46a9aba0-3486-4ec2-96b2-781bc9a96742"
    sni: "vpn-node.internal"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/xVpnTrojanWsSvc7f3a"
      headers:
        Host: "vpn-node.internal"
  - name: "🇫🇷_31"
    type: ss
    server: "38.180.92.242"
    port: 32245
    cipher: "chacha20-ietf-poly1305"
    password: "pFNN9jKe8jwD"
    udp: true
  - name: "🇫🇷_32"
    type: ss
    server: "51.77.225.200"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "zRZNBszYyWo5"
    udp: true
  - name: "🇫🇷_33"
    type: ss
    server: "fr3.levikogjgfdd.ir"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "BqnqToih0PbU"
    udp: true
  - name: "🇫🇷_34"
    type: ss
    server: "104.105.202.31"
    port: 1080
    cipher: "chacha20-ietf-poly1305"
    password: "Y8TaKQMncgi8nl_dNnLjQRUAmT4hZga7"
    udp: true
  - name: "🇫🇷_35"
    type: ss
    server: "fr4.levikogjgfdd.ir"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "zRZNBszYyWo5"
    udp: true
  - name: "🇫🇷_36"
    type: ss
    server: "fr4.levikogjgfdd.ir"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "zRZNBszYyWo5"
    udp: true
  - name: "🇫🇷_37"
    type: ss
    server: "51.255.13.232"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "BqnqToih0PbU"
    udp: true
  - name: "🇫🇷_38"
    type: ss
    server: "51.77.225.200"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "zRZNBszYyWo5"
    udp: true
  - name: "🇫🇷_39"
    type: ss
    server: "104.105.202.31"
    port: 1959
    cipher: "chacha20-ietf-poly1305"
    password: "Y8TaKQMncgi8nl_dNnLjQRUAmT4hZga7"
    udp: true
  - name: "🇫🇷_40"
    type: ss
    server: "141.253.107.174"
    port: 22345
    cipher: "chacha20-ietf-poly1305"
    password: "5d79906d-89ab-430b-acbc-3327568a5be3"
    udp: true
  - name: "🇫🇷_41"
    type: ss
    server: "141.253.107.174"
    port: 22345
    cipher: "chacha20-ietf-poly1305"
    password: "be6cbb46-ebb0-4726-9202-6a3bac1d0afb"
    udp: true
  - name: "🇫🇷_42"
    type: ss
    server: "51.255.13.232"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "BqnqToih0PbU"
    udp: true
  - name: "🇫🇷_43"
    type: ss
    server: "104.105.202.31"
    port: 1080
    cipher: "chacha20-ietf-poly1305"
    password: "Y8TaKQMncgi8nl_dNnLjQRUAmT4hZga7"
    udp: true
  - name: "🇫🇷_44"
    type: ss
    server: "38.180.92.242"
    port: 32245
    cipher: "chacha20-ietf-poly1305"
    password: "pFNN9jKe8jwD"
    udp: true
  - name: "🇫🇷_45"
    type: ss
    server: "104.105.202.31"
    port: 1111
    cipher: "chacha20-ietf-poly1305"
    password: "Y8TaKQMncgi8nl_dNnLjQRUAmT4hZga7"
    udp: true
  - name: "🇫🇷_46"
    type: ss
    server: "fr3.levikogjgfdd.ir"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "BqnqToih0PbU"
    udp: true
  - name: "🇫🇷_47"
    type: ss
    server: "104.105.202.31"
    port: 1111
    cipher: "chacha20-ietf-poly1305"
    password: "Y8TaKQMncgi8nl_dNnLjQRUAmT4hZga7"
    udp: true
  - name: "🇫🇷_48"
    type: ss
    server: "141.253.107.174"
    port: 22345
    cipher: "chacha20-ietf-poly1305"
    password: "be6cbb46-ebb0-4726-9202-6a3bac1d0afb"
    udp: true
  - name: "🇫🇷_49"
    type: ss
    server: "104.105.202.31"
    port: 1959
    cipher: "chacha20-ietf-poly1305"
    password: "Y8TaKQMncgi8nl_dNnLjQRUAmT4hZga7"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇫🇷_1"
      - "🇫🇷_2"
      - "🇫🇷_3"
      - "🇫🇷_4"
      - "🇫🇷_5"
      - "🇫🇷_6"
      - "🇫🇷_7"
      - "🇫🇷_8"
      - "🇫🇷_9"
      - "🇫🇷_10"
      - "🇫🇷_11"
      - "🇫🇷_12"
      - "🇫🇷_13"
      - "🇫🇷_14"
      - "🇫🇷_15"
      - "🇫🇷_16"
      - "🇫🇷_17"
      - "🇫🇷_18"
      - "🇫🇷_19"
      - "🇫🇷_20"
      - "🇫🇷_21"
      - "🇫🇷_22"
      - "🇫🇷_23"
      - "🇫🇷_24"
      - "🇫🇷_25"
      - "🇫🇷_26"
      - "🇫🇷_27"
      - "🇫🇷_28"
      - "🇫🇷_29"
      - "🇫🇷_30"
      - "🇫🇷_31"
      - "🇫🇷_32"
      - "🇫🇷_33"
      - "🇫🇷_34"
      - "🇫🇷_35"
      - "🇫🇷_36"
      - "🇫🇷_37"
      - "🇫🇷_38"
      - "🇫🇷_39"
      - "🇫🇷_40"
      - "🇫🇷_41"
      - "🇫🇷_42"
      - "🇫🇷_43"
      - "🇫🇷_44"
      - "🇫🇷_45"
      - "🇫🇷_46"
      - "🇫🇷_47"
      - "🇫🇷_48"
      - "🇫🇷_49"


rules:
  - MATCH,PROXY
