name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇭🇰_1"
    type: vless
    server: "219.76.13.181"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_2"
    type: vless
    server: "176.98.181.6"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_3"
    type: vless
    server: "45.207.210.224"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_4"
    type: vless
    server: "156.239.245.134"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_5"
    type: vless
    server: "hk3n.wxgqlfx.vip"
    port: 35193
    uuid: "35cbae61-ee10-4cb9-abb8-4950b35e9851"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "d_pn_DMaIxhCkNh80h0Mc7nP94hrlN--I8liOIREDxE"
      short-id: "e8daed2d"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_6"
    type: vless
    server: "209.33.160.61"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_7"
    type: vless
    server: "156.224.76.187"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_8"
    type: vless
    server: "47.239.4.246"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_9"
    type: vless
    server: "154.218.15.50"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "vms.lifetime47.workers.dev"
  - name: "🇭🇰_10"
    type: vless
    server: "182.16.61.2"
    port: 45647
    uuid: "caec0d8d-ab2f-4247-b97d-7fb1a34ab195"
    udp: true
  - name: "🇭🇰_11"
    type: vless
    server: "103.192.179.132"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_12"
    type: vless
    server: "42.200.176.168"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_13"
    type: vless
    server: "103.148.73.167"
    port: 8443
    uuid: "f1d247db-d7ce-4eb8-9c0d-7b10603cd0b4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ty986gfazs.cainiaohub.xyz"
    network: ws
    ws-opts:
      path: "/81574b6b-c9d7-44a0-b83d-dad56e8cb530"
      headers:
        Host: "ty986gfazs.cainiaohub.xyz"
  - name: "🇭🇰_14"
    type: vless
    server: "vj37-1936vtw.fincore.top"
    port: 443
    uuid: "5e8e81ac-a1c4-4543-b81e-651bf9872b54"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.bing.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "TP_bpIPUtjdxxGA9j7mpsHtSDfM2HMSZFNWW9MtDPT0"
      short-id: "14156e3ac23212cc"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_15"
    type: vless
    server: "162.128.157.164"
    port: 443
    uuid: "5e8e81ac-a1c4-4543-b81e-651bf9872b54"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.bing.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "TP_bpIPUtjdxxGA9j7mpsHtSDfM2HMSZFNWW9MtDPT0"
      short-id: "14156e3ac23212cc"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_16"
    type: vless
    server: "43.132.231.159"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_17"
    type: vless
    server: "103.180.20.240"
    port: 8443
    uuid: "f1d247db-d7ce-4eb8-9c0d-7b10603cd0b4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ty986gfazs.cainiaohub.xyz"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/81574b6b-c9d7-44a0-b83d-dad56e8cb530"
      headers:
        Host: "ty986gfazs.cainiaohub.xyz"
  - name: "🇭🇰_18"
    type: vless
    server: "219.76.13.169"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_19"
    type: vless
    server: "42.200.231.108"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_20"
    type: vless
    server: "209.9.200.202"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_21"
    type: vless
    server: "8.210.29.68"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_22"
    type: vless
    server: "103.149.183.198"
    port: 13779
    uuid: "928e6cce-8ced-4243-9a48-a6642edd09b0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tesla.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "llTyp52oRXnJmQ3I9UUrmlwbMA79B-wLCRHCu-8dLGg"
      short-id: "af1bdd293097b664"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_23"
    type: vless
    server: "8.218.22.14"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_24"
    type: vless
    server: "103.219.194.43"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_25"
    type: vless
    server: "219.76.13.177"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_26"
    type: vless
    server: "42.200.173.201"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_27"
    type: vless
    server: "34.96.200.38"
    port: 443
    uuid: "2058418a-7718-4050-bdd5-db7487ffdb3b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "uoXBNYcBgR-h2YmU1NFhFyASr6qh9UghWOuo1WZIikw"
      short-id: "17d824dd68e24aaf"
  - name: "🇭🇰_28"
    type: vless
    server: "54.46.62.66"
    port: 38218
    uuid: "0234cdd9-35ee-40a5-b698-9820f09a04f5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "03hWBp-xwElEmilVxbhasf1Al0MZnvARUr4zclCV6S0"
      short-id: "30752ffd01a85649"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_29"
    type: vless
    server: "82.38.46.66"
    port: 15007
    uuid: "399c4c9b-27e1-37f1-9dce-22ccc2727a86"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.bing.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "qVNutDFjEp3v2wjeUl_Yy6l9TXawXfSjAsFj3iktmRA"
      short-id: "2c4d005b"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_30"
    type: vless
    server: "35.241.98.220"
    port: 443
    uuid: "96563f88-f743-4395-a3b2-27ec462ae45e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "bSK8gtmPMlw7gP415tmh6kQzzFiwzxBsT3Kuqql6cRo"
      short-id: "ec2c7091fe76336c"
  - name: "🇭🇰_31"
    type: vless
    server: "47.79.78.40"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_32"
    type: vless
    server: "103.148.73.144"
    port: 8443
    uuid: "f1d247db-d7ce-4eb8-9c0d-7b10603cd0b4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ty986gfazs.cainiaohub.xyz"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/81574b6b-c9d7-44a0-b83d-dad56e8cb530"
      headers:
        Host: "ty986gfazs.cainiaohub.xyz"
  - name: "🇭🇰_33"
    type: vless
    server: "154.84.154.37"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_34"
    type: vless
    server: "182.16.61.5"
    port: 45647
    uuid: "6f361c37-bc54-43dd-8c8b-0f59354745a5"
    udp: true
  - name: "🇭🇰_35"
    type: vless
    server: "43.161.226.55"
    port: 443
    uuid: "04c808e2-0b59-47b0-a54b-32fc7ef1c902"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "free.cndyw.ggff.net"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇭🇰_36"
    type: vless
    server: "42.200.172.70"
    port: 36862
    uuid: "0234cdd9-35ee-40a5-b698-9820f09a04f5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "FAQExDhWlkY2S2aug1j1w9wSUduf0EPIELcF2sQ6cAo"
      short-id: "015b86bf36cc72"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_37"
    type: vless
    server: "82.38.46.66"
    port: 15003
    uuid: "399c4c9b-27e1-37f1-9dce-22ccc2727a86"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "R_3usai5pYqcc0aIzXPfaoe-VE_7JOe60fUNMicwfQ8"
      short-id: "4c517b9e"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_38"
    type: vless
    server: "47.238.210.5"
    port: 13779
    uuid: "928e6cce-8ced-4243-9a48-a6642edd09b0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tesla.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "llTyp52oRXnJmQ3I9UUrmlwbMA79B-wLCRHCu-8dLGg"
      short-id: "af1bdd293097b664"
  - name: "🇭🇰_39"
    type: vless
    server: "219.76.13.166"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_40"
    type: vless
    server: "82.38.46.66"
    port: 15006
    uuid: "399c4c9b-27e1-37f1-9dce-22ccc2727a86"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.adobe.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "g9KZONtwSL8mL772rps2nXVAuQpsgHY33K_pHpI89Rg"
      short-id: "029a6cc4"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_41"
    type: vless
    server: "219.76.13.167"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_42"
    type: vless
    server: "156.226.168.221"
    port: 35193
    uuid: "35cbae61-ee10-4cb9-abb8-4950b35e9851"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "d_pn_DMaIxhCkNh80h0Mc7nP94hrlN--I8liOIREDxE"
      short-id: "e8daed2d"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_43"
    type: vless
    server: "156.224.76.205"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_44"
    type: trojan
    server: "119.246.1.143"
    port: 443
    password: "BxceQaOe"
    sni: "119.246.1.143"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_45"
    type: ss
    server: "95.40.120.162"
    port: 8319
    cipher: "chacha20-ietf-poly1305"
    password: "ljqdalu13.."
    udp: true
  - name: "🇭🇰_46"
    type: ss
    server: "95.40.120.162"
    port: 8316
    cipher: "chacha20-ietf-poly1305"
    password: "ljqdalu13.."
    udp: true
  - name: "🇭🇰_47"
    type: ss
    server: "95.40.120.162"
    port: 8319
    cipher: "chacha20-ietf-poly1305"
    password: "ljqdalu13.."
    udp: true
  - name: "🇭🇰_48"
    type: ss
    server: "95.40.120.162"
    port: 8316
    cipher: "chacha20-ietf-poly1305"
    password: "ljqdalu13.."
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇭🇰_1"
      - "🇭🇰_2"
      - "🇭🇰_3"
      - "🇭🇰_4"
      - "🇭🇰_5"
      - "🇭🇰_6"
      - "🇭🇰_7"
      - "🇭🇰_8"
      - "🇭🇰_9"
      - "🇭🇰_10"
      - "🇭🇰_11"
      - "🇭🇰_12"
      - "🇭🇰_13"
      - "🇭🇰_14"
      - "🇭🇰_15"
      - "🇭🇰_16"
      - "🇭🇰_17"
      - "🇭🇰_18"
      - "🇭🇰_19"
      - "🇭🇰_20"
      - "🇭🇰_21"
      - "🇭🇰_22"
      - "🇭🇰_23"
      - "🇭🇰_24"
      - "🇭🇰_25"
      - "🇭🇰_26"
      - "🇭🇰_27"
      - "🇭🇰_28"
      - "🇭🇰_29"
      - "🇭🇰_30"
      - "🇭🇰_31"
      - "🇭🇰_32"
      - "🇭🇰_33"
      - "🇭🇰_34"
      - "🇭🇰_35"
      - "🇭🇰_36"
      - "🇭🇰_37"
      - "🇭🇰_38"
      - "🇭🇰_39"
      - "🇭🇰_40"
      - "🇭🇰_41"
      - "🇭🇰_42"
      - "🇭🇰_43"
      - "🇭🇰_44"
      - "🇭🇰_45"
      - "🇭🇰_46"
      - "🇭🇰_47"
      - "🇭🇰_48"


rules:
  - MATCH,PROXY
