name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇭🇰_1"
    type: vless
    server: "209.33.167.234"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇭🇰_2"
    type: vless
    server: "23.249.18.144"
    port: 8581
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "edg-2oo.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/setting/article/category?ed=2560"
      headers:
        Host: "edg-2oo.pages.dev"
  - name: "🇭🇰_3"
    type: vless
    server: "156.226.168.221"
    port: 35193
    uuid: "35cbae61-ee10-4cb9-abb8-4950b35e9851"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "d_pn_DMaIxhCkNh80h0Mc7nP94hrlN--I8liOIREDxE"
      short-id: "e8daed2d"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_4"
    type: vless
    server: "154.218.15.50"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "vms.lifetime47.workers.dev"
  - name: "🇭🇰_5"
    type: vless
    server: "219.76.13.169"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_6"
    type: vless
    server: "47.75.125.163"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "edg-2oo.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/go.php/group?ed=2560"
      headers:
        Host: "edg-2oo.pages.dev"
  - name: "🇭🇰_7"
    type: vless
    server: "156.239.245.134"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_8"
    type: vless
    server: "104.129.167.4"
    port: 80
    uuid: "424fa201-3f94-479e-b533-d5257cf9a207"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=telegram @azadweb"
      headers:
        Host: "floral-thunder-10d3.82-67d.workers.dev"
  - name: "🇭🇰_9"
    type: vless
    server: "23.147.172.135"
    port: 443
    uuid: "1864223a-8797-4244-8e72-4d2801d040e1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "thus-k.netnode.cc.cd"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/t.me/daily_free_vpn"
      headers:
        Host: "thus-k.netnode.cc.cd"
  - name: "🇭🇰_10"
    type: vless
    server: "43.159.4.80"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    network: ws
    ws-opts:
      path: "/episode/files?ed=2560fp=chrome"
      headers:
        Host: "cdn8848.776676.xyz"
  - name: "🇭🇰_11"
    type: vless
    server: "47.239.6.251"
    port: 13779
    uuid: "928e6cce-8ced-4243-9a48-a6642edd09b0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tesla.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "llTyp52oRXnJmQ3I9UUrmlwbMA79B-wLCRHCu-8dLGg"
      short-id: "af1bdd293097b664"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_12"
    type: vless
    server: "43.100.53.46"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "edg-2oo.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/channels/trade?ed=2560"
      headers:
        Host: "edg-2oo.pages.dev"
  - name: "🇭🇰_13"
    type: vless
    server: "156.224.76.205"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_14"
    type: vless
    server: "38.190.210.250"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_15"
    type: vless
    server: "34.92.123.152"
    port: 443
    uuid: "5d77df4a-0b55-4597-b0e6-ae3ef70a72c0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "ios"
    reality-opts:
      public-key: "aZfMRLVe6AAcWbF9SpJ0s1RXN-OP5bqdTJ4C74_jTi0"
      short-id: "56c35a22730a22e5"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_16"
    type: vless
    server: "38.207.184.202"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇭🇰_17"
    type: vless
    server: "8.210.29.68"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_18"
    type: vless
    server: "47.238.126.123"
    port: 443
    uuid: "bf41cc32-f0a2-4b27-ba9f-8026ce0aed84"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amazon.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "4IeLDkxPTFecGeobLaxV9XaVW7oBgcqwW2dvfFtPQD4"
      short-id: "7771265f0b109528"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_19"
    type: vless
    server: "43.168.16.112"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "edg-2oo.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/lessons/intro/library?ed=2560"
      headers:
        Host: "edg-2oo.pages.dev"
  - name: "🇭🇰_20"
    type: vless
    server: "47.242.162.186"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "edg-2oo.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/home?ed=2560"
      headers:
        Host: "edg-2oo.pages.dev"
  - name: "🇭🇰_21"
    type: vless
    server: "47.83.173.110"
    port: 443
    uuid: "bca6f15f-89db-40e2-a955-19d084229234"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.samsung.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "BqFbrSSosM7RAVvUGTRmCrZlHY6aGwq9HEJs0fMdK0s"
      short-id: "8144589880395fa1"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_22"
    type: vless
    server: "vj37-1936vtw.fincore.top"
    port: 443
    uuid: "5e8e81ac-a1c4-4543-b81e-651bf9872b54"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.bing.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "TP_bpIPUtjdxxGA9j7mpsHtSDfM2HMSZFNWW9MtDPT0"
      short-id: "14156e3ac23212cc"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_23"
    type: vless
    server: "43.168.16.112"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_24"
    type: vless
    server: "47.86.103.60"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "edg-2oo.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/task/pic/channels?ed=2560"
      headers:
        Host: "edg-2oo.pages.dev"
  - name: "🇭🇰_25"
    type: vless
    server: "47.238.155.3"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "edg-2oo.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/avatar/about/blogs?ed=2560"
      headers:
        Host: "edg-2oo.pages.dev"
  - name: "🇭🇰_26"
    type: vless
    server: "219.76.13.177"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_27"
    type: vless
    server: "68.64.179.129"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇭🇰_28"
    type: vless
    server: "27.50.48.8"
    port: 443
    uuid: "c98a16e4-0dc5-42f0-b3db-30f04525c123"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vless2-8vx.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vless2-8vx.pages.dev"
  - name: "🇭🇰_29"
    type: vless
    server: "109.66.88.158"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "edg-2oo.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/auth?ed=2560"
      headers:
        Host: "edg-2oo.pages.dev"
  - name: "🇭🇰_30"
    type: vless
    server: "219.76.13.166"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_31"
    type: vless
    server: "47.239.241.168"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "edg-2oo.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/order/members/mall?ed=2560"
      headers:
        Host: "edg-2oo.pages.dev"
  - name: "🇭🇰_32"
    type: vless
    server: "154.218.15.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime47.workers.dev"
  - name: "🇭🇰_33"
    type: vless
    server: "162.128.157.164"
    port: 443
    uuid: "5e8e81ac-a1c4-4543-b81e-651bf9872b54"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.bing.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "TP_bpIPUtjdxxGA9j7mpsHtSDfM2HMSZFNWW9MtDPT0"
      short-id: "14156e3ac23212cc"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_34"
    type: vless
    server: "68.64.182.74"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "edg-2oo.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/shows/temp/go.php?ed=2560"
      headers:
        Host: "edg-2oo.pages.dev"
  - name: "🇭🇰_35"
    type: vless
    server: "47.83.4.146"
    port: 443
    uuid: "8952ecb7-4b85-4aa5-8b22-adc9aa4d3591"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "ID53PilNajhqBP3PTJJxurZOFnZfKVs-CU5buNOaKBQ"
      short-id: "e40b98d40e53b8b9"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_36"
    type: vless
    server: "47.238.210.5"
    port: 13779
    uuid: "928e6cce-8ced-4243-9a48-a6642edd09b0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tesla.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "llTyp52oRXnJmQ3I9UUrmlwbMA79B-wLCRHCu-8dLGg"
      short-id: "af1bdd293097b664"
  - name: "🇭🇰_37"
    type: vless
    server: "43.175.131.30"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇭🇰_38"
    type: vless
    server: "103.192.179.132"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_39"
    type: vless
    server: "219.76.13.167"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_40"
    type: vless
    server: "8.218.228.242"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "edg-2oo.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/channel/channels?ed=2560"
      headers:
        Host: "edg-2oo.pages.dev"
  - name: "🇭🇰_41"
    type: vless
    server: "47.57.233.212"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "edg-2oo.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/albums/my/comic?ed=2560"
      headers:
        Host: "edg-2oo.pages.dev"
  - name: "🇭🇰_42"
    type: vless
    server: "47.75.104.211"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "edg-2oo.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/course/wenku?ed=2560"
      headers:
        Host: "edg-2oo.pages.dev"
  - name: "🇭🇰_43"
    type: vless
    server: "43.154.131.189"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_44"
    type: vless
    server: "8.210.40.146"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "edg-2oo.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/knowledge/data/film?ed=2560"
      headers:
        Host: "edg-2oo.pages.dev"
  - name: "🇭🇰_45"
    type: vless
    server: "47.76.172.190"
    port: 443
    uuid: "60baeb19-560d-402d-b9c9-c062c2350e0b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "9nukDgL8dc3PWV07DAwi-_FFj3Y25ifYnnrIp7uV0SI"
      short-id: "92ddbafbf38306f5"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_46"
    type: vless
    server: "2.27.109.236"
    port: 443
    uuid: "1864223a-8797-4244-8e72-4d2801d040e1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "thus-k.netnode.cc.cd"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/t.me/daily_free_vpn"
      headers:
        Host: "thus-k.netnode.cc.cd"
  - name: "🇭🇰_47"
    type: vless
    server: "43.161.254.71"
    port: 443
    uuid: "1864223a-8797-4244-8e72-4d2801d040e1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "thus-k.netnode.cc.cd"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/t.me/daily_free_vpn"
      headers:
        Host: "thus-k.netnode.cc.cd"
  - name: "🇭🇰_48"
    type: trojan
    server: "47.240.80.220"
    port: 2052
    password: "tFjD2X1F6i9FfWp2GDU5Vbi1conuaChDKIYbw9zMFrqvMoSz"
    sni: "vpn.12169.top"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_49"
    type: trojan
    server: "119.246.1.143"
    port: 443
    password: "BxceQaOe"
    sni: "t.me/ripaojiedian"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_50"
    type: ss
    server: "212.192.15.231"
    port: 8388
    cipher: "aes-256-gcm"
    password: "Z9TvqsEkWr7P7GXe"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇭🇰_1"
      - "🇭🇰_2"
      - "🇭🇰_3"
      - "🇭🇰_4"
      - "🇭🇰_5"
      - "🇭🇰_6"
      - "🇭🇰_7"
      - "🇭🇰_8"
      - "🇭🇰_9"
      - "🇭🇰_10"
      - "🇭🇰_11"
      - "🇭🇰_12"
      - "🇭🇰_13"
      - "🇭🇰_14"
      - "🇭🇰_15"
      - "🇭🇰_16"
      - "🇭🇰_17"
      - "🇭🇰_18"
      - "🇭🇰_19"
      - "🇭🇰_20"
      - "🇭🇰_21"
      - "🇭🇰_22"
      - "🇭🇰_23"
      - "🇭🇰_24"
      - "🇭🇰_25"
      - "🇭🇰_26"
      - "🇭🇰_27"
      - "🇭🇰_28"
      - "🇭🇰_29"
      - "🇭🇰_30"
      - "🇭🇰_31"
      - "🇭🇰_32"
      - "🇭🇰_33"
      - "🇭🇰_34"
      - "🇭🇰_35"
      - "🇭🇰_36"
      - "🇭🇰_37"
      - "🇭🇰_38"
      - "🇭🇰_39"
      - "🇭🇰_40"
      - "🇭🇰_41"
      - "🇭🇰_42"
      - "🇭🇰_43"
      - "🇭🇰_44"
      - "🇭🇰_45"
      - "🇭🇰_46"
      - "🇭🇰_47"
      - "🇭🇰_48"
      - "🇭🇰_49"
      - "🇭🇰_50"


rules:
  - MATCH,PROXY
