name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇭🇰_1"
    type: vless
    server: "103.149.183.198"
    port: 13779
    uuid: "928e6cce-8ced-4243-9a48-a6642edd09b0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tesla.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "llTyp52oRXnJmQ3I9UUrmlwbMA79B-wLCRHCu-8dLGg"
      short-id: "af1bdd293097b664"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_2"
    type: vless
    server: "182.16.61.2"
    port: 45647
    uuid: "caec0d8d-ab2f-4247-b97d-7fb1a34ab195"
    udp: true
  - name: "🇭🇰_3"
    type: vless
    server: "35.241.98.220"
    port: 443
    uuid: "96563f88-f743-4395-a3b2-27ec462ae45e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "bSK8gtmPMlw7gP415tmh6kQzzFiwzxBsT3Kuqql6cRo"
      short-id: "ec2c7091fe76336c"
  - name: "🇭🇰_4"
    type: vless
    server: "8.210.29.68"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_5"
    type: vless
    server: "156.226.168.221"
    port: 35193
    uuid: "35cbae61-ee10-4cb9-abb8-4950b35e9851"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "d_pn_DMaIxhCkNh80h0Mc7nP94hrlN--I8liOIREDxE"
      short-id: "e8daed2d"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_6"
    type: vless
    server: "209.9.200.202"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_7"
    type: vless
    server: "156.224.76.205"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_8"
    type: vless
    server: "hk3n.wxgqlfx.vip"
    port: 35193
    uuid: "35cbae61-ee10-4cb9-abb8-4950b35e9851"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "d_pn_DMaIxhCkNh80h0Mc7nP94hrlN--I8liOIREDxE"
      short-id: "e8daed2d"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_9"
    type: vless
    server: "212.192.13.233"
    port: 443
    uuid: "302cf77d-6fb7-4ac8-ae61-88e286340d59"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cathaypacific.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "O8Av8GXWVqj7FOxUyStmrTLWv5EtvQ1ZnMOVVLb1V3s"
      short-id: "1bc2c1ef1c"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_10"
    type: vless
    server: "nian.001.url111.kcloud02.top"
    port: 15003
    uuid: "399c4c9b-27e1-37f1-9dce-22ccc2727a86"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "R_3usai5pYqcc0aIzXPfaoe-VE_7JOe60fUNMicwfQ8"
      short-id: "4c517b9e"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_11"
    type: vless
    server: "219.76.13.167"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_12"
    type: vless
    server: "103.192.179.132"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_13"
    type: vless
    server: "hks.008819.xyz"
    port: 30701
    uuid: "7aa3a024-e333-4b63-99a2-3db9d3b2054e"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "hks.008819.xyz"
  - name: "🇭🇰_14"
    type: vless
    server: "82.38.46.66"
    port: 15007
    uuid: "399c4c9b-27e1-37f1-9dce-22ccc2727a86"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.bing.com"
    client-fingerprint: "ios"
    reality-opts:
      public-key: "qVNutDFjEp3v2wjeUl_Yy6l9TXawXfSjAsFj3iktmRA"
      short-id: "2c4d005b"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_15"
    type: vless
    server: "47.239.6.251"
    port: 13779
    uuid: "928e6cce-8ced-4243-9a48-a6642edd09b0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tesla.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "llTyp52oRXnJmQ3I9UUrmlwbMA79B-wLCRHCu-8dLGg"
      short-id: "af1bdd293097b664"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_16"
    type: vless
    server: "nian.001.url111.kcloud02.top"
    port: 15006
    uuid: "399c4c9b-27e1-37f1-9dce-22ccc2727a86"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.adobe.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "g9KZONtwSL8mL772rps2nXVAuQpsgHY33K_pHpI89Rg"
      short-id: "029a6cc4"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_17"
    type: vless
    server: "hk.mkdir.kdns.fr"
    port: 443
    uuid: "2cf94f4d-9d5b-49ca-81a3-ddc0529a2dac"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pwdern.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "pwdern.pages.dev"
  - name: "🇭🇰_18"
    type: vless
    server: "182.16.61.5"
    port: 45647
    uuid: "6f361c37-bc54-43dd-8c8b-0f59354745a5"
    udp: true
  - name: "🇭🇰_19"
    type: vless
    server: "176.98.181.6"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_20"
    type: vless
    server: "82.38.46.66"
    port: 15006
    uuid: "399c4c9b-27e1-37f1-9dce-22ccc2727a86"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.adobe.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "g9KZONtwSL8mL772rps2nXVAuQpsgHY33K_pHpI89Rg"
      short-id: "029a6cc4"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_21"
    type: vless
    server: "8.218.22.14"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_22"
    type: vless
    server: "82.38.46.66"
    port: 15003
    uuid: "399c4c9b-27e1-37f1-9dce-22ccc2727a86"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "R_3usai5pYqcc0aIzXPfaoe-VE_7JOe60fUNMicwfQ8"
      short-id: "4c517b9e"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_23"
    type: vless
    server: "34.96.200.38"
    port: 443
    uuid: "2058418a-7718-4050-bdd5-db7487ffdb3b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "uoXBNYcBgR-h2YmU1NFhFyASr6qh9UghWOuo1WZIikw"
      short-id: "17d824dd68e24aaf"
  - name: "🇭🇰_24"
    type: vless
    server: "219.76.13.169"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_25"
    type: vless
    server: "219.76.13.166"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_26"
    type: vless
    server: "219.76.13.177"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_27"
    type: vless
    server: "156.239.245.134"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_28"
    type: vless
    server: "162.128.157.164"
    port: 443
    uuid: "5e8e81ac-a1c4-4543-b81e-651bf9872b54"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.bing.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "TP_bpIPUtjdxxGA9j7mpsHtSDfM2HMSZFNWW9MtDPT0"
      short-id: "14156e3ac23212cc"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_29"
    type: vless
    server: "47.238.210.5"
    port: 13779
    uuid: "928e6cce-8ced-4243-9a48-a6642edd09b0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tesla.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "llTyp52oRXnJmQ3I9UUrmlwbMA79B-wLCRHCu-8dLGg"
      short-id: "af1bdd293097b664"
  - name: "🇭🇰_30"
    type: vless
    server: "103.180.20.240"
    port: 8443
    uuid: "f1d247db-d7ce-4eb8-9c0d-7b10603cd0b4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ty986gfazs.cainiaohub.xyz"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/81574b6b-c9d7-44a0-b83d-dad56e8cb530"
      headers:
        Host: "ty986gfazs.cainiaohub.xyz"
  - name: "🇭🇰_31"
    type: vless
    server: "103.219.194.43"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "🇭🇰_32"
    type: trojan
    server: "38.55.199.26"
    port: 50000
    password: "8539b07d-4a48-46ca-8ce7-f961f4e35b0c"
    sni: "hk200m.jiasu.asia"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_33"
    type: trojan
    server: "hk03.qianmoip.win"
    port: 50222
    password: "302cf77d-6fb7-4ac8-ae61-88e286340d59"
    sni: "taobao.com"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_34"
    type: trojan
    server: "119.246.1.143"
    port: 443
    password: "BxceQaOe"
    sni: "119.246.1.143"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_35"
    type: trojan
    server: "hk04.qianmoip.win"
    port: 52224
    password: "302cf77d-6fb7-4ac8-ae61-88e286340d59"
    sni: "taobao.com"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_36"
    type: trojan
    server: "hk200m.jiasu.asia"
    port: 50000
    password: "8539b07d-4a48-46ca-8ce7-f961f4e35b0c"
    sni: "hk200m.jiasu.asia"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_37"
    type: trojan
    server: "58.152.46.127"
    port: 28443
    password: "0f3963f9-0530-434d-be2c-87e9b61143c8"
    sni: "vpn-node.internal"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/xVpnTrojanWsSvc7f3a"
      headers:
        Host: "vpn-node.internal"
  - name: "🇭🇰_38"
    type: trojan
    server: "152.175.28.15"
    port: 28443
    password: "04e30e9f-661a-4a40-9973-4f2961298e99"
    sni: "vpn-node.internal"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/xVpnTrojanWsSvc7f3a"
      headers:
        Host: "vpn-node.internal"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇭🇰_1"
      - "🇭🇰_2"
      - "🇭🇰_3"
      - "🇭🇰_4"
      - "🇭🇰_5"
      - "🇭🇰_6"
      - "🇭🇰_7"
      - "🇭🇰_8"
      - "🇭🇰_9"
      - "🇭🇰_10"
      - "🇭🇰_11"
      - "🇭🇰_12"
      - "🇭🇰_13"
      - "🇭🇰_14"
      - "🇭🇰_15"
      - "🇭🇰_16"
      - "🇭🇰_17"
      - "🇭🇰_18"
      - "🇭🇰_19"
      - "🇭🇰_20"
      - "🇭🇰_21"
      - "🇭🇰_22"
      - "🇭🇰_23"
      - "🇭🇰_24"
      - "🇭🇰_25"
      - "🇭🇰_26"
      - "🇭🇰_27"
      - "🇭🇰_28"
      - "🇭🇰_29"
      - "🇭🇰_30"
      - "🇭🇰_31"
      - "🇭🇰_32"
      - "🇭🇰_33"
      - "🇭🇰_34"
      - "🇭🇰_35"
      - "🇭🇰_36"
      - "🇭🇰_37"
      - "🇭🇰_38"


rules:
  - MATCH,PROXY
