name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇮🇳_1"
    type: vless
    server: "5.253.30.99"
    port: 40443
    uuid: "511c1563-2cb6-4064-abc6-a59ee49818a8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "deepl.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "cwmcqsfS7klQlkcoUNuATEk0NiPY-NnRb9z8rCJDQw0"
      short-id: "88b6"
    flow: "xtls-rprx-vision"
  - name: "🇮🇳_2"
    type: vless
    server: "154.198.173.30"
    port: 443
    uuid: "50414e45-4c5f-5a45-5553-1f6869e9b4fb"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zeuspanel-render.onrender.com"
    network: ws
    ws-opts:
      path: "/stream/PANEL_ZEUS/1f6869e9b4fb"
      headers:
        Host: "zeuspanel-render.onrender.com"
  - name: "🇮🇳_3"
    type: vless
    server: "194.61.31.126"
    port: 2053
    uuid: "0bf89828-484f-4710-9581-12aa961e3bf1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "Gy6W0bXf2bpxoG1k3szp8X0ekzoyXlEtzT8V4mYQ3EE"
      short-id: "29fe4205ddc971a8"
  - name: "🇮🇳_4"
    type: vless
    server: "172.237.44.80"
    port: 19567
    uuid: "0faaa1ee-f3d2-49ec-92af-3228329f3000"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.nvidia.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "tzm4xWHOerooioq4QQkI7VCvIapECgody_vJGDzX3UI"
      short-id: "87714fc3c52a"
    flow: "xtls-rprx-vision"
  - name: "🇮🇳_5"
    type: vless
    server: "5.253.42.163"
    port: 40443
    uuid: "15fd22d1-8931-4d41-af37-8ba6711e93fe"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "deepl.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "d1gJntekIStCHyAwgJCuv-N4_BBx5dDQ7K6CeWmpMRo"
      short-id: "84fc"
    flow: "xtls-rprx-vision"
  - name: "🇮🇳_6"
    type: vless
    server: "5.253.42.164"
    port: 40443
    uuid: "e99ba96d-dec8-42eb-be53-19e71eef7cab"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "deepl.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "g77ZJbm18JEotapmVRjaXi133MzkbhkU2lxhVeXx8zw"
      short-id: "68a8"
    flow: "xtls-rprx-vision"
  - name: "🇮🇳_7"
    type: vless
    server: "148.113.5.44"
    port: 443
    uuid: "72ea5a91-ffcc-43d2-9297-5993c3abf186"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "QLjTpkXRB453R9fXhJzKkc_q_gSm2MZrIOuxW4uW-mI"
      short-id: "221873918e0bb74d"
    flow: "xtls-rprx-vision"
  - name: "🇮🇳_8"
    type: vless
    server: "65.20.85.14"
    port: 443
    uuid: "2eadb97f-bba4-4471-8d55-bd461525a2dc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eded-52n.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "eded-52n.pages.dev"
  - name: "🇮🇳_9"
    type: vless
    server: "20.235.220.189"
    port: 443
    uuid: "2eadb97f-bba4-4471-8d55-bd461525a2dc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eded-52n.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "eded-52n.pages.dev"
  - name: "🇮🇳_10"
    type: ss
    server: "172.105.39.124"
    port: 7002
    cipher: "aes-256-gcm"
    password: "RexnBgU7EV5ADxG"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇮🇳_1"
      - "🇮🇳_2"
      - "🇮🇳_3"
      - "🇮🇳_4"
      - "🇮🇳_5"
      - "🇮🇳_6"
      - "🇮🇳_7"
      - "🇮🇳_8"
      - "🇮🇳_9"
      - "🇮🇳_10"


rules:
  - MATCH,PROXY
