name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇮🇳_1"
    type: vless
    server: "154.198.173.7"
    port: 8443
    uuid: "7967bf59-57e3-4cde-9898-527b0fe60022"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "speed.dulacloud.store"
    network: ws
    ws-opts:
      path: "/dula?Telegram-WangCai2"
      headers:
        Host: "speed.dulacloud.store"
  - name: "🇮🇳_2"
    type: vless
    server: "185.149.135.7"
    port: 8443
    uuid: "7967bf59-57e3-4cde-9898-527b0fe60022"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "speed.dulacloud.store"
    network: ws
    ws-opts:
      path: "/dula?Telegram-WangCai2"
      headers:
        Host: "speed.dulacloud.store"
  - name: "🇮🇳_3"
    type: vless
    server: "5.253.42.164"
    port: 40443
    uuid: "e99ba96d-dec8-42eb-be53-19e71eef7cab"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "deepl.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "g77ZJbm18JEotapmVRjaXi133MzkbhkU2lxhVeXx8zw"
      short-id: "68a8"
    flow: "xtls-rprx-vision"
  - name: "🇮🇳_4"
    type: vless
    server: "194.61.31.126"
    port: 2053
    uuid: "7f1f5848-da44-47df-8581-df83e88ee2b3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "GAYlNViQ9mkjs0iTjNmijAIXOaK2h0P2opHCYOrCNy0"
      short-id: "ae3ba555edc1ba0a"
  - name: "🇮🇳_5"
    type: vless
    server: "5.253.30.99"
    port: 40443
    uuid: "511c1563-2cb6-4064-abc6-a59ee49818a8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "deepl.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "cwmcqsfS7klQlkcoUNuATEk0NiPY-NnRb9z8rCJDQw0"
      short-id: "88b6"
    flow: "xtls-rprx-vision"
  - name: "🇮🇳_6"
    type: trojan
    server: "185.67.125.119"
    port: 443
    password: "3747000103274291200"
    sni: "oriented-pug.adder289.quest"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇳_7"
    type: trojan
    server: "185.67.125.147"
    port: 443
    password: "3763495894587285504"
    sni: "optimal-owl.goat627.mom"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇳_8"
    type: trojan
    server: "64.227.131.19"
    port: 443
    password: "21c6c7cb-332b-4a0c-9ad7-dff9c3111442"
    sni: "us02web.zoom.us"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇳_9"
    type: trojan
    server: "65.20.82.177"
    port: 443
    password: "Tg3RnK7Xp8B1"
    sni: "ash.d50f6225-23b4-3a7b-9f15-a0fb2fc16803.kailib.com"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇳_10"
    type: trojan
    server: "143.110.246.228"
    port: 443
    password: "3bcd9e33-8377-4b32-af33-217158577ff3"
    sni: "kdlsupport.zendesk.com"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇳_11"
    type: trojan
    server: "139.84.133.199"
    port: 443
    password: "af4b064a9c39472fb34ad8b113acdc6b"
    sni: "139.84.133.199"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇳_12"
    type: trojan
    server: "185.67.125.147"
    port: 443
    password: "3747000103274291200"
    sni: "polished-collie.adder289.quest"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇳_13"
    type: ss
    server: "172.105.39.124"
    port: 7002
    cipher: "aes-256-gcm"
    password: "RexnBgU7EV5ADxG"
    udp: true
  - name: "🇮🇳_14"
    type: ss
    server: "103.120.178.193"
    port: 31348
    cipher: "chacha20-ietf-poly1305"
    password: "EBDRo9THx4CqiFU7h5gfov76oNwzZURAh0ZwbWjBKddtUhvz"
    udp: true
  - name: "🇮🇳_15"
    type: ss
    server: "103.120.178.193"
    port: 31348
    cipher: "chacha20-ietf-poly1305"
    password: "EBDRo9THx4CqiFU7h5gfov76oNwzZURAh0ZwbWjBKddtUhvz"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇮🇳_1"
      - "🇮🇳_2"
      - "🇮🇳_3"
      - "🇮🇳_4"
      - "🇮🇳_5"
      - "🇮🇳_6"
      - "🇮🇳_7"
      - "🇮🇳_8"
      - "🇮🇳_9"
      - "🇮🇳_10"
      - "🇮🇳_11"
      - "🇮🇳_12"
      - "🇮🇳_13"
      - "🇮🇳_14"
      - "🇮🇳_15"


rules:
  - MATCH,PROXY
