name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇮🇳_1"
    type: vless
    server: "108.165.152.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime61.workers.dev"
  - name: "🇮🇳_2"
    type: vless
    server: "4.240.110.47"
    port: 443
    uuid: "b585dc5e-55bf-4a8b-913a-27c9ccac05c3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bab-6.site"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/vws/"
      headers:
        Host: "bab-6.site"
  - name: "🇮🇳_3"
    type: vless
    server: "5.253.30.99"
    port: 40443
    uuid: "511c1563-2cb6-4064-abc6-a59ee49818a8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "deepl.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "cwmcqsfS7klQlkcoUNuATEk0NiPY-NnRb9z8rCJDQw0"
      short-id: "88b6"
    flow: "xtls-rprx-vision"
  - name: "🇮🇳_4"
    type: vless
    server: "194.61.31.126"
    port: 2053
    uuid: "7f1f5848-da44-47df-8581-df83e88ee2b3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "GAYlNViQ9mkjs0iTjNmijAIXOaK2h0P2opHCYOrCNy0"
      short-id: "ae3ba555edc1ba0a"
  - name: "🇮🇳_5"
    type: vless
    server: "5.253.42.164"
    port: 40443
    uuid: "e99ba96d-dec8-42eb-be53-19e71eef7cab"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "deepl.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "g77ZJbm18JEotapmVRjaXi133MzkbhkU2lxhVeXx8zw"
      short-id: "68a8"
    flow: "xtls-rprx-vision"
  - name: "🇮🇳_6"
    type: vless
    server: "157.20.27.44"
    port: 443
    uuid: "ff1b0b50-70dc-4bae-866e-55cff86f4d6d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "apxc.falsemirrov.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "sbl95eJz_SP1vYb8doCjAJOo0o5NveutEb9J-XKGl1w"
      short-id: "9c2378562188c3cb"
    flow: "xtls-rprx-vision"
  - name: "🇮🇳_7"
    type: vless
    server: "157.20.27.29"
    port: 443
    uuid: "ff1b0b50-70dc-4bae-866e-55cff86f4d6d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "apxc.falsemirrov.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "sbl95eJz_SP1vYb8doCjAJOo0o5NveutEb9J-XKGl1w"
      short-id: "9c2378562188c3cb"
    flow: "xtls-rprx-vision"
  - name: "🇮🇳_8"
    type: vless
    server: "157.20.27.52"
    port: 443
    uuid: "ff1b0b50-70dc-4bae-866e-55cff86f4d6d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "apxc.falsemirrov.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "sbl95eJz_SP1vYb8doCjAJOo0o5NveutEb9J-XKGl1w"
      short-id: "9c2378562188c3cb"
    flow: "xtls-rprx-vision"
  - name: "🇮🇳_9"
    type: ss
    server: "103.120.178.193"
    port: 31348
    cipher: "chacha20-ietf-poly1305"
    password: "EBDRo9THx4CqiFU7h5gfov76oNwzZURAh0ZwbWjBKddtUhvz"
    udp: true
  - name: "🇮🇳_10"
    type: ss
    server: "103.120.178.193"
    port: 31348
    cipher: "chacha20-ietf-poly1305"
    password: "EBDRo9THx4CqiFU7h5gfov76oNwzZURAh0ZwbWjBKddtUhvz"
    udp: true
  - name: "🇮🇳_11"
    type: ss
    server: "172.105.39.124"
    port: 7002
    cipher: "aes-256-gcm"
    password: "RexnBgU7EV5ADxG"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇮🇳_1"
      - "🇮🇳_2"
      - "🇮🇳_3"
      - "🇮🇳_4"
      - "🇮🇳_5"
      - "🇮🇳_6"
      - "🇮🇳_7"
      - "🇮🇳_8"
      - "🇮🇳_9"
      - "🇮🇳_10"
      - "🇮🇳_11"


rules:
  - MATCH,PROXY
