name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇮🇷_1"
    type: vless
    server: "mAiLgAtEWAy7-BAsEStREAM3-poRTnodehUb9.CloUDSYNC9.Com"
    port: 443
    uuid: "3ccbd6a4-bb95-4a93-bf7a-ad4a0bde9054"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "NodeLinkbAsE7-ApiWeBstREam3-daTAcOReNEt.cloUDsyNc9.Com"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/pdpZR63Sn1BgoYh8"
      headers:
        Host: "noDeLiNKbaSe7-ApIWEBStreaM3-dATaCoreNET.cloUDsYnc9.COM"
  - name: "🇮🇷_2"
    type: vless
    server: "45.131.4.115"
    port: 80
    uuid: "a7b22989-6c1f-4b59-b0f3-0605401813c4"
    udp: true
    network: ws
    ws-opts:
      path: "/eyJqdW5rIjoiQXoydFJwaWM0WSIsInByb3RvY29sIjoidmwiLCJtb2RlIjoicHJveHlpcCIsInBhbmVsSVBzIjpbXX0="
      headers:
        Host: "worker3.gigak25604.workers.dev"
  - name: "🇮🇷_3"
    type: trojan
    server: "45.131.4.118"
    port: 443
    password: "f18d6149-e214-8554-e737-f7523c8b2eea"
    sni: "0403.infinityconfig4.workers.dev"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/sync"
  - name: "🇮🇷_4"
    type: trojan
    server: "MAILGateWAy7-baSeSTREaM3-pORTNOdEHub9.clOUDsYNC9.Com"
    port: 443
    password: "3ccbd6a4-bb95-4a93-bf7a-ad4a0bde9054"
    sni: "nodelInKBasE7-aPIWebStrEam3-DaTAcOrENET.cloUdsYNc9.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/JqME6Sln1BgoYh8"
      headers:
        Host: "NoDeLiNkBase7-ApiwebStREam3-DatacOREnET.CLoUdSYNC9.cOM"
  - name: "🇮🇷_5"
    type: ss
    server: "51.255.13.232"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "BqnqToih0PbU"
    udp: true
  - name: "🇮🇷_6"
    type: ss
    server: "193.29.139.168"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "QCXDxuDlTTMD7jtgHUjIoj"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇮🇷_1"
      - "🇮🇷_2"
      - "🇮🇷_3"
      - "🇮🇷_4"
      - "🇮🇷_5"
      - "🇮🇷_6"


rules:
  - MATCH,PROXY
