name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇮🇷_1"
    type: vless
    server: "185.143.233.5"
    port: 80
    uuid: "38dd06a1-e1cb-492b-bb87-218ce05d0d67"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "fox-a9e04bb07a-test.apps.ir-central1.arvancaas.ir"
  - name: "🇮🇷_2"
    type: vless
    server: "fr-gra-ovh-01.sfproxy.fuck-rkn.dev"
    port: 443
    uuid: "8ff82100-8aad-4281-bf41-f318519d7182"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "jobinvest.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇮🇷_3"
    type: vless
    server: "45.131.4.115"
    port: 80
    uuid: "74ed78f1-4095-47e6-b043-094e494fb7e5"
    udp: true
    network: ws
    ws-opts:
      path: "/sVnT0vhrV7WAl52Z"
      headers:
        Host: "worker3.gisenoj224.workers.dev"
  - name: "🇮🇷_4"
    type: vless
    server: "fr-gra-ovh-02.fuck-rkn.dev"
    port: 443
    uuid: "8ff82100-8aad-4281-bf41-f318519d7182"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "jobinvest.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇮🇷_5"
    type: trojan
    server: "45.131.4.118"
    port: 443
    password: "f18d6149-e214-8554-e737-f7523c8b2eea"
    sni: "0403.infinityconfig4.workers.dev"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/sync"
  - name: "🇮🇷_6"
    type: ss
    server: "193.29.139.168"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "QCXDxuDlTTMD7jtgHUjIoj"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇮🇷_1"
      - "🇮🇷_2"
      - "🇮🇷_3"
      - "🇮🇷_4"
      - "🇮🇷_5"
      - "🇮🇷_6"


rules:
  - MATCH,PROXY
