name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇮🇹_1"
    type: vless
    server: "204.216.216.23"
    port: 1114
    uuid: "6ba2eac6-0ec9-44ca-a42b-a8e23aafb530"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yahoo.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "WfkCF0eEuIoO0MyJsKOddU89QrTzCZ4y2dzCJbH99CQ"
      short-id: "79a1e14b"
    flow: "xtls-rprx-vision"
  - name: "🇮🇹_2"
    type: vless
    server: "57.131.32.191"
    port: 8443
    uuid: "dc0d0eda-2293-4001-aa03-bd6c9431ed24"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ov-italy1.09vpn.com"
    network: ws
    ws-opts:
      path: "/vless/"
      headers:
        Host: "ov-italy1.09vpn.com"
  - name: "🇮🇹_3"
    type: vless
    server: "151.241.215.109"
    port: 443
    uuid: "699ce9a1-abbb-4525-988e-b940381352e8"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "🇮🇹_4"
    type: vless
    server: "172.232.196.241"
    port: 32396
    uuid: "bd6ebd72-25cd-4209-a418-a8c72946da90"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.sony.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "Pj1XWo01sxdH8jKJ_8DoJiZDFANHFKRAqOncP8RNkwU"
      short-id: "dd6ce6af95001a"
    flow: "xtls-rprx-vision"
  - name: "🇮🇹_5"
    type: vless
    server: "151.243.198.104"
    port: 443
    uuid: "e4737ce4-c646-44cc-9067-390e13c2a5f6"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "itproxy4.lockdwn.com"
  - name: "🇮🇹_6"
    type: vless
    server: "57.131.38.163"
    port: 2053
    uuid: "d4b08cd6-0903-411a-9dac-45dbdf5c9712"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "Ej2H5ucT7qKegYcT8wODdlxa-cLHr7F4hDVUHzAhcnc"
      short-id: "5b8a942318178e7b"
  - name: "🇮🇹_7"
    type: vless
    server: "204.216.216.23"
    port: 10086
    uuid: "9f0285ee-20ca-4953-bcdb-86a920652923"
    udp: true
  - name: "🇮🇹_8"
    type: vless
    server: "172.238.232.239"
    port: 32833
    uuid: "167ed405-7de9-4bff-b1ea-6e3d49c76b0b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.intel.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "PaTDdYBrlh1xBixdI0igvRRkf0vnUwMRzi-4oDyfS20"
      short-id: "a0a305ccc8e94aa8"
    flow: "xtls-rprx-vision"
  - name: "🇮🇹_9"
    type: vless
    server: "57.131.21.102"
    port: 8443
    uuid: "69ac162b-1643-4acb-9f49-09d8b0fad609"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "milan.adaspoloandco.com"
    client-fingerprint: "qq"
    network: ws
    ws-opts:
      path: "/RoBeRt"
  - name: "🇮🇹_10"
    type: ss
    server: "194.87.47.204"
    port: 10901
    cipher: "aes-256-gcm"
    password: "d1fa2f4b98a38bc8"
    udp: true
  - name: "🇮🇹_11"
    type: ss
    server: "57.131.48.45"
    port: 8388
    cipher: "aes-256-gcm"
    password: "itzvpn@321"
    udp: true
  - name: "🇮🇹_12"
    type: ss
    server: "194.87.47.204"
    port: 10901
    cipher: "aes-256-gcm"
    password: "d1fa2f4b98a38bc8"
    udp: true
  - name: "🇮🇹_13"
    type: ss
    server: "57.131.48.45"
    port: 8388
    cipher: "aes-256-gcm"
    password: "itzvpn@321"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇮🇹_1"
      - "🇮🇹_2"
      - "🇮🇹_3"
      - "🇮🇹_4"
      - "🇮🇹_5"
      - "🇮🇹_6"
      - "🇮🇹_7"
      - "🇮🇹_8"
      - "🇮🇹_9"
      - "🇮🇹_10"
      - "🇮🇹_11"
      - "🇮🇹_12"
      - "🇮🇹_13"


rules:
  - MATCH,PROXY
