name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇮🇹_1"
    type: vless
    server: "116.204.164.60"
    port: 7443
    uuid: "48942ced-a272-41c1-98ac-75745d83bf93"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bapj1qapjk4.0sds0li1bwcz0i76it0gjxv1.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "bapj1qapjk4.0sds0li1bwcz0i76it0gjxv1.workers.dev"
  - name: "🇮🇹_2"
    type: vless
    server: "116.204.164.5"
    port: 7443
    uuid: "32404bf4-fdba-4c77-b6be-e29b8ed54808"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "8n9qi6t-owl.gevc9s4n60cc3wzcmwhjyezydpmbchocxp.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "8n9qi6t-owl.gevc9s4n60cc3wzcmwhjyezydpmbchocxp.workers.dev"
  - name: "🇮🇹_3"
    type: vless
    server: "116.204.164.27"
    port: 7443
    uuid: "7d4f5f0d-293f-4612-98d6-01fa0c1954b4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "o-85ley6knn8ut.6nvkygqh144t7xtdyvh0y3o4gzo3ujhnk8n.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "o-85ley6knn8ut.6nvkygqh144t7xtdyvh0y3o4gzo3ujhnk8n.workers.dev"
  - name: "🇮🇹_4"
    type: vless
    server: "116.204.164.27"
    port: 7443
    uuid: "4c7480b2-d67b-4bb9-9f33-0700dfcbdee6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "jln31qtswdkut5.60kohcognywybguuq3ouc818oofnxfvn35daott.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "jln31qtswdkut5.60kohcognywybguuq3ouc818oofnxfvn35daott.workers.dev"
  - name: "🇮🇹_5"
    type: vless
    server: "116.204.164.17"
    port: 7443
    uuid: "9dd5bcab-4a60-4f97-a7a4-77e98eabf9c4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "c6dbx99g6stb418qeo.t3jmlj0r152zji4htdkm9.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "c6dbx99g6stb418qeo.t3jmlj0r152zji4htdkm9.workers.dev"
  - name: "🇮🇹_6"
    type: vless
    server: "116.204.164.60"
    port: 7443
    uuid: "fc85cf23-75e6-4b91-b468-8adc9407047b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "o-85ley6knn8ut.6nvkygqh144t7xtdyvh0y3o4gzo3ujhnk8n.workers.dev"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "o-85ley6knn8ut.6nvkygqh144t7xtdyvh0y3o4gzo3ujhnk8n.workers.dev"
  - name: "🇮🇹_7"
    type: vless
    server: "116.204.164.17"
    port: 7443
    uuid: "0baed386-770e-4e17-a6ca-24349e60903f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "8n9qi6t-owl.gevc9s4n60cc3wzcmwhjyezydpmbchocxp.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "8n9qi6t-owl.gevc9s4n60cc3wzcmwhjyezydpmbchocxp.workers.dev"
  - name: "🇮🇹_8"
    type: vless
    server: "116.204.164.60"
    port: 7443
    uuid: "cd099367-1052-42f4-8961-4d1e09144cf9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "c6dbx99g6stb418qeo.t3jmlj0r152zji4htdkm9.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "c6dbx99g6stb418qeo.t3jmlj0r152zji4htdkm9.workers.dev"
  - name: "🇮🇹_9"
    type: vless
    server: "116.204.164.30"
    port: 7443
    uuid: "8dd3f783-aa97-420b-8aaa-d8a6c9679dad"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "c6dbx99g6stb418qeo.t3jmlj0r152zji4htdkm9.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "c6dbx99g6stb418qeo.t3jmlj0r152zji4htdkm9.workers.dev"
  - name: "🇮🇹_10"
    type: vless
    server: "116.204.164.60"
    port: 7443
    uuid: "c676be7d-b481-4bba-88d0-65855e09dc67"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
  - name: "🇮🇹_11"
    type: vless
    server: "116.204.164.27"
    port: 7443
    uuid: "c9b314e9-47f1-4d4d-be52-30b538777b14"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
  - name: "🇮🇹_12"
    type: vless
    server: "204.216.216.23"
    port: 10086
    uuid: "9f0285ee-20ca-4953-bcdb-86a920652923"
    udp: true
  - name: "🇮🇹_13"
    type: vless
    server: "116.204.164.30"
    port: 7443
    uuid: "d5f29a64-da5d-4f99-b3c4-ae92cc39ad5f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
  - name: "🇮🇹_14"
    type: vless
    server: "116.204.164.17"
    port: 7443
    uuid: "ef8907eb-8bb5-4735-80f2-1d0068500d95"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
  - name: "🇮🇹_15"
    type: vless
    server: "116.204.164.30"
    port: 7443
    uuid: "329aa1be-ee6d-4d92-a8ef-c2ddac7583b1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
  - name: "🇮🇹_16"
    type: vless
    server: "116.204.164.60"
    port: 7443
    uuid: "33509502-dd58-46bf-b574-985ca9a53964"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "8n9qi6t-owl.gevc9s4n60cc3wzcmwhjyezydpmbchocxp.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "8n9qi6t-owl.gevc9s4n60cc3wzcmwhjyezydpmbchocxp.workers.dev"
  - name: "🇮🇹_17"
    type: vless
    server: "116.204.164.5"
    port: 7443
    uuid: "2416ff70-cb17-4cdc-834d-a89c00261e01"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "o-85ley6knn8ut.6nvkygqh144t7xtdyvh0y3o4gzo3ujhnk8n.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "o-85ley6knn8ut.6nvkygqh144t7xtdyvh0y3o4gzo3ujhnk8n.workers.dev"
  - name: "🇮🇹_18"
    type: vless
    server: "116.204.164.27"
    port: 7443
    uuid: "00274dd7-7cee-420d-9942-b24d047611a7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "8n9qi6t-owl.gevc9s4n60cc3wzcmwhjyezydpmbchocxp.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "8n9qi6t-owl.gevc9s4n60cc3wzcmwhjyezydpmbchocxp.workers.dev"
  - name: "🇮🇹_19"
    type: vless
    server: "185.119.19.105"
    port: 443
    uuid: "5d02517f-63d5-3e9f-b467-1bcf4d4e25d3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "u695099u8adcedd7s8746.gogocs.xyz"
    flow: "xtls-rprx-vision"
  - name: "🇮🇹_20"
    type: vless
    server: "116.204.164.5"
    port: 7443
    uuid: "6eb831ea-8829-457b-a5d1-52f640a97486"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "jln31qtswdkut5.60kohcognywybguuq3ouc818oofnxfvn35daott.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "jln31qtswdkut5.60kohcognywybguuq3ouc818oofnxfvn35daott.workers.dev"
  - name: "🇮🇹_21"
    type: vless
    server: "116.204.164.5"
    port: 7443
    uuid: "8a7f35a6-6aad-4f42-80ab-86d06f32e0a7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
  - name: "🇮🇹_22"
    type: vless
    server: "116.204.164.27"
    port: 7443
    uuid: "c82e5af9-5fef-4fdd-9454-2682873e1563"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "c6dbx99g6stb418qeo.t3jmlj0r152zji4htdkm9.workers.dev"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "c6dbx99g6stb418qeo.t3jmlj0r152zji4htdkm9.workers.dev"
  - name: "🇮🇹_23"
    type: vless
    server: "31.77.154.200"
    port: 443
    uuid: "33c150b7-c0ca-4133-9a52-6f1207da9b8b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "deepl.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "vnjp7zIK2H3CGdjSis_79KXqS6IG-opmpbETPUD-EC8"
      short-id: "15affa0af66dfc79"
    flow: "xtls-rprx-vision"
  - name: "🇮🇹_24"
    type: vless
    server: "116.204.164.5"
    port: 7443
    uuid: "d25fa7ff-f71e-4cc2-88e6-a340b86fdebf"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
  - name: "🇮🇹_25"
    type: vless
    server: "57.131.32.191"
    port: 8443
    uuid: "dc0d0eda-2293-4001-aa03-bd6c9431ed24"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ov-italy1.09vpn.com"
    network: ws
    ws-opts:
      path: "/vless/"
      headers:
        Host: "ov-italy1.09vpn.com"
  - name: "🇮🇹_26"
    type: trojan
    server: "91.193.5.121"
    port: 8443
    password: "Aimer"
    sni: "ngepz.ambercc.filegear-sg.me"
    skip-cert-verify: true
    udp: true
  - name: "🇮🇹_27"
    type: ss
    server: "185.213.20.110"
    port: 7001
    cipher: "aes-256-gcm"
    password: "RexnBgU7EV5ADxG"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇮🇹_1"
      - "🇮🇹_2"
      - "🇮🇹_3"
      - "🇮🇹_4"
      - "🇮🇹_5"
      - "🇮🇹_6"
      - "🇮🇹_7"
      - "🇮🇹_8"
      - "🇮🇹_9"
      - "🇮🇹_10"
      - "🇮🇹_11"
      - "🇮🇹_12"
      - "🇮🇹_13"
      - "🇮🇹_14"
      - "🇮🇹_15"
      - "🇮🇹_16"
      - "🇮🇹_17"
      - "🇮🇹_18"
      - "🇮🇹_19"
      - "🇮🇹_20"
      - "🇮🇹_21"
      - "🇮🇹_22"
      - "🇮🇹_23"
      - "🇮🇹_24"
      - "🇮🇹_25"
      - "🇮🇹_26"
      - "🇮🇹_27"


rules:
  - MATCH,PROXY
