name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇯🇵_1"
    type: vless
    server: "43.207.162.145"
    port: 32913
    uuid: "15836880-212b-4690-b29c-1889a749bf72"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.intel.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "iJhoNzfiPiua04PL88iAAyZz2u39su4ChSCiGVoekRQ"
      short-id: "a8f0a95931a52732"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_2"
    type: vless
    server: "3.112.47.207"
    port: 29860
    uuid: "7460547d-e83c-4843-b404-9142b22261a7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.intel.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "g7I81MzpM7J6K9WLbZdaMPS9We6GYeeNY3EKRvyiKW4"
      short-id: "c992a34f288be189"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_3"
    type: vless
    server: "3.114.220.22"
    port: 19645
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_4"
    type: vless
    server: "52.199.9.165"
    port: 15147
    uuid: "60bf43f0-dc41-42ac-8e2b-e64b73688ed2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.nvidia.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "1qBD5uOyQZ4Pj7UMgw9Fuyo7oZ8ruACjWOTwSl4sbA4"
      short-id: "91a8f64c584660c5"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_5"
    type: vless
    server: "3.112.131.211"
    port: 48086
    uuid: "620ca966-d78b-4c88-a5c9-acf13c7d252f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.nvidia.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "qq9vUmReS92PojPLpSyUY_c6CydUUtut7ffxc3V0LTo"
      short-id: "7083d685446ce576"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_6"
    type: vless
    server: "103.75.118.228"
    port: 12683
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_7"
    type: vless
    server: "31.76.91.72"
    port: 2087
    uuid: "524e00ce-ed89-481d-b4a4-6d7017f884e3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ads.x5.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "-ZTJcZ_UcqAB7LHgkUqhnlJsQs_oBafRgjsFtWZElmM"
      short-id: "c226283c4de5b1ad"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇯🇵_8"
    type: vless
    server: "152.69.195.67"
    port: 47878
    uuid: "eb8613e3-8393-4cff-a3ad-6501fd4adc63"
    udp: true
  - name: "🇯🇵_9"
    type: vless
    server: "jp.wxgqlfx.top"
    port: 26518
    uuid: "e01fcb68-3112-49da-b85d-dffb799cfc9b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "github.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "1fa6iCY7vhoQyKu91FeaK04FN-mr1qeHnrtdyLZ79mk"
      short-id: "6caead99"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_10"
    type: vless
    server: "18.177.61.231"
    port: 30203
    uuid: "0346a35f-8e11-4b33-852d-00fa9c642878"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.sony.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "dsJ2WwzENgTAgd8okJPXLpwzdsDjU67mBEnhUhgvvTk"
      short-id: "40150721499a92"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_11"
    type: vless
    server: "3.114.220.22"
    port: 18007
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_12"
    type: vless
    server: "13.230.222.139"
    port: 18384
    uuid: "50641912-a16b-4ac3-aa2f-312c88b617e1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.tesla.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "cRwzK1c65HdBluJqM3GS8YN4N-TqTCmI6X_3eEgAVms"
      short-id: "3f316a236d64c1"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_13"
    type: vless
    server: "104.105.138.244"
    port: 443
    uuid: "f5c4664b-67ab-4d92-801d-a60984e104d4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "rpROz1JNz8wRk2QT5o7jwE9CzJUWMvPNXoeWyS3c1WM"
      short-id: "09994e53af766acd"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_14"
    type: vless
    server: "35.78.59.6"
    port: 47571
    uuid: "88a67610-b7ae-42ba-8af0-29cfa54cef37"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amd.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "OyfEDzOiDM5eMvTacJ4bVhF1V0QZgvz-vP3K456l3W4"
      short-id: "4c8b46e500b0f3ad"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_15"
    type: vless
    server: "137.220.221.179"
    port: 443
    uuid: "a16a3336-c9ab-489f-9b85-c973f5e2cfa4"
    udp: true
  - name: "🇯🇵_16"
    type: vless
    server: "13.231.129.39"
    port: 29224
    uuid: "3298044a-024f-4b48-a598-ba56c75e99f3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.sony.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "HqLe_f1G54_pDZGbCnermTm-vqDiNp6cXVMaasg3NWE"
      short-id: "fcbdd08920d4c8"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_17"
    type: vless
    server: "13.114.124.85"
    port: 18614
    uuid: "926912d3-1656-4e83-9971-411b283f7998"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.tesla.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "w0jjW_RLHvQc2tk_7sbxfBawdMlJZfb7rKROwg051gA"
      short-id: "c6966bed91ecd9"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_18"
    type: vless
    server: "38.175.203.11"
    port: 443
    uuid: "1b8ec962-6e6f-4fc3-a9a4-c8a6fc907796"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "oulucloud.706666.xyz"
    client-fingerprint: "chrome"
  - name: "🇯🇵_19"
    type: vless
    server: "13.231.7.104"
    port: 24620
    uuid: "b969ef8f-7bdb-474f-9481-d8f3c5686fb8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amd.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "eZthMfn0kQJFNr_srk502fr8yUHMoHQ7Oh3v4_HfTBI"
      short-id: "db2cb3b3c2dbb711"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_20"
    type: vless
    server: "13.231.19.51"
    port: 11690
    uuid: "e2b8b217-cffb-4d66-9b8b-eca6e4334032"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.tesla.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "Bv3z0_uFRabB9C4CFpNfqepZUyeO4YTh1duJdMBNLkg"
      short-id: "034885e346fd30"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_21"
    type: vless
    server: "3.113.9.16"
    port: 48203
    uuid: "e5a9a8be-886e-4522-b11d-3edde88c9c8c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.nvidia.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "nxC5EiVCdXMnvfRa1LoNUs21ZNS2DdP36gfHayvUXRU"
      short-id: "5b63c338f69077"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_22"
    type: vless
    server: "14.137.238.193"
    port: 10000
    uuid: "8b92dfff-ddfd-4a37-841d-6f7bf7ab43b6"
    udp: true
  - name: "🇯🇵_23"
    type: vless
    server: "52.194.211.43"
    port: 56449
    uuid: "fe855f99-4eb5-4a80-ad48-354649ff1305"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.intel.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "anIR48iTD0Inl1z85396AwMvDhcx9y25DdFsVR896DE"
      short-id: "25a9435577670327"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_24"
    type: vless
    server: "156.231.113.153"
    port: 443
    uuid: "3340c44a-042e-4dfd-b82c-33192d56ba98"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "h2GGazCHLBtmIUxiCxGUvsaEF8mGi8xFeCcI14sAJTI"
      short-id: "4bbe62498d4cc3c9"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_25"
    type: vless
    server: "13.114.89.187"
    port: 16611
    uuid: "059fbe5b-21dc-413f-8f5c-dac39201914c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.intel.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "cDzA5Efsd52LehcCFXh9bS3eCuj7HQZwau-yjPqLPgQ"
      short-id: "701b0c5c9dee514d"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_26"
    type: vless
    server: "13.230.66.70"
    port: 23607
    uuid: "babf64f8-f9ee-4564-a097-16433f2ebd46"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.tesla.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "liATkHCbR_IPjdgOhHK5nZO6fgCO091bTab3v2G8Lm4"
      short-id: "701b0c5c9dee514d"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_27"
    type: vless
    server: "18.183.215.124"
    port: 28573
    uuid: "871bfce7-8440-4394-8d82-56b51f20fdad"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.sony.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "1DJr9toke7FRuSXjibBVuNvRnLnJnN5kXwUBG6Romzg"
      short-id: "03653bc03be10c97"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_28"
    type: vless
    server: "154.31.114.248"
    port: 50159
    uuid: "d56624b2-35bb-468c-9b2a-e0b0df7230c1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "j4QXngGuJkUGwRj4XIrfHRohYYuEfnJlX4cvCE-WklA"
      short-id: "091e1c5db8451757"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_29"
    type: vless
    server: "156.246.88.125"
    port: 26518
    uuid: "e01fcb68-3112-49da-b85d-dffb799cfc9b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "github.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "1fa6iCY7vhoQyKu91FeaK04FN-mr1qeHnrtdyLZ79mk"
      short-id: "6caead99"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_30"
    type: vless
    server: "103.75.118.228"
    port: 11452
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_31"
    type: vless
    server: "3.114.220.22"
    port: 10583
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_32"
    type: vless
    server: "54.249.200.131"
    port: 18921
    uuid: "fe113f0b-43fa-4662-9403-9f91b53fed1f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.nvidia.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "Ct9tvt4V8JSZ7uCbKWKuXNMG5Q7U_FMDWPHgi4YHAXw"
      short-id: "2e23c31063fcff"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_33"
    type: trojan
    server: "z-jp2.1card.cc"
    port: 10011
    password: "ultra@kWZdAzt_IH593eGLRjdxnBZ0"
    sni: "www.cloudflare.com"
    skip-cert-verify: true
    udp: true
  - name: "🇯🇵_34"
    type: trojan
    server: "z-jp2.1card.cc"
    port: 10008
    password: "ultra@kWZdAzt_IH593eGLRjdxnBZ0"
    sni: "www.cloudflare.com"
    skip-cert-verify: true
    udp: true
  - name: "🇯🇵_35"
    type: trojan
    server: "z-jp1.1card.cc"
    port: 10012
    password: "ultra@kWZdAzt_IH593eGLRjdxnBZ0"
    sni: "www.cloudflare.com"
    skip-cert-verify: true
    udp: true
  - name: "🇯🇵_36"
    type: trojan
    server: "z-jp2.1card.cc"
    port: 10012
    password: "ultra@kWZdAzt_IH593eGLRjdxnBZ0"
    sni: "www.cloudflare.com"
    skip-cert-verify: true
    udp: true
  - name: "🇯🇵_37"
    type: trojan
    server: "z-jp1.1card.cc"
    port: 10008
    password: "ultra@kWZdAzt_IH593eGLRjdxnBZ0"
    sni: "www.cloudflare.com"
    skip-cert-verify: true
    udp: true
  - name: "🇯🇵_38"
    type: trojan
    server: "z-jp2.1card.cc"
    port: 10010
    password: "ultra@kWZdAzt_IH593eGLRjdxnBZ0"
    sni: "www.cloudflare.com"
    skip-cert-verify: true
    udp: true
  - name: "🇯🇵_39"
    type: trojan
    server: "z-jp2.1card.cc"
    port: 10009
    password: "ultra@kWZdAzt_IH593eGLRjdxnBZ0"
    sni: "www.cloudflare.com"
    skip-cert-verify: true
    udp: true
  - name: "🇯🇵_40"
    type: trojan
    server: "z-jp1.1card.cc"
    port: 10010
    password: "ultra@kWZdAzt_IH593eGLRjdxnBZ0"
    sni: "www.cloudflare.com"
    skip-cert-verify: true
    udp: true
  - name: "🇯🇵_41"
    type: ss
    server: "149.22.87.204"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_42"
    type: ss
    server: "149.22.87.204"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_43"
    type: ss
    server: "149.22.87.240"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_44"
    type: ss
    server: "64.83.33.45"
    port: 443
    cipher: "aes-256-gcm"
    password: "AyqX8KynyyQLReOZorQRQbsvmiwxBQOf"
    udp: true
  - name: "🇯🇵_45"
    type: ss
    server: "84.247.155.196"
    port: 443
    cipher: "aes-256-gcm"
    password: "3eOFeNssde7PYYMv"
    udp: true
  - name: "🇯🇵_46"
    type: ss
    server: "84.247.155.196"
    port: 80
    cipher: "aes-256-gcm"
    password: "3eOFeNssde7PYYMv"
    udp: true
  - name: "🇯🇵_47"
    type: ss
    server: "149.22.87.240"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_48"
    type: ss
    server: "149.22.87.241"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_49"
    type: ss
    server: "64.83.33.45"
    port: 443
    cipher: "aes-256-gcm"
    password: "AyqX8KynyyQLReOZorQRQbsvmiwxBQOf"
    udp: true
  - name: "🇯🇵_50"
    type: ss
    server: "149.22.87.241"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_51"
    type: ss
    server: "45.32.16.53"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "uTBjZhDmOMwBVAJI"
    udp: true
  - name: "🇯🇵_52"
    type: ss
    server: "149.22.87.241"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_53"
    type: ss
    server: "149.22.87.241"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_54"
    type: ss
    server: "149.22.87.240"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_55"
    type: ss
    server: "149.22.87.204"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_56"
    type: ss
    server: "84.247.155.196"
    port: 80
    cipher: "aes-256-gcm"
    password: "3eOFeNssde7PYYMv"
    udp: true
  - name: "🇯🇵_57"
    type: ss
    server: "84.247.155.196"
    port: 443
    cipher: "aes-256-gcm"
    password: "3eOFeNssde7PYYMv"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇯🇵_1"
      - "🇯🇵_2"
      - "🇯🇵_3"
      - "🇯🇵_4"
      - "🇯🇵_5"
      - "🇯🇵_6"
      - "🇯🇵_7"
      - "🇯🇵_8"
      - "🇯🇵_9"
      - "🇯🇵_10"
      - "🇯🇵_11"
      - "🇯🇵_12"
      - "🇯🇵_13"
      - "🇯🇵_14"
      - "🇯🇵_15"
      - "🇯🇵_16"
      - "🇯🇵_17"
      - "🇯🇵_18"
      - "🇯🇵_19"
      - "🇯🇵_20"
      - "🇯🇵_21"
      - "🇯🇵_22"
      - "🇯🇵_23"
      - "🇯🇵_24"
      - "🇯🇵_25"
      - "🇯🇵_26"
      - "🇯🇵_27"
      - "🇯🇵_28"
      - "🇯🇵_29"
      - "🇯🇵_30"
      - "🇯🇵_31"
      - "🇯🇵_32"
      - "🇯🇵_33"
      - "🇯🇵_34"
      - "🇯🇵_35"
      - "🇯🇵_36"
      - "🇯🇵_37"
      - "🇯🇵_38"
      - "🇯🇵_39"
      - "🇯🇵_40"
      - "🇯🇵_41"
      - "🇯🇵_42"
      - "🇯🇵_43"
      - "🇯🇵_44"
      - "🇯🇵_45"
      - "🇯🇵_46"
      - "🇯🇵_47"
      - "🇯🇵_48"
      - "🇯🇵_49"
      - "🇯🇵_50"
      - "🇯🇵_51"
      - "🇯🇵_52"
      - "🇯🇵_53"
      - "🇯🇵_54"
      - "🇯🇵_55"
      - "🇯🇵_56"
      - "🇯🇵_57"


rules:
  - MATCH,PROXY
