name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇰🇷_1"
    type: vless
    server: "54.180.103.3"
    port: 8686
    uuid: "1a17b19d-4896-4531-af79-6e91d8ef8228"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    reality-opts:
      public-key: "A3NXnUIT-W0m1Y_leRnv5so2IeCvk9FCFgL31PulfTw"
      short-id: "628b3c90c98ead4f"
  - name: "🇰🇷_2"
    type: vless
    server: "47.80.63.187"
    port: 443
    uuid: "8c64cae9-a513-4e37-a68c-980bcaf2c591"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "kr1.hat.onl"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "me6tyn-I8IolkgJK4sggSsC9sinhkLPBdPwtVlPk5TI"
      short-id: "0d6903ea350815e1"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_3"
    type: vless
    server: "13.209.83.123"
    port: 24227
    uuid: "55c97a9c-7de4-412d-8122-633adf5c7cb7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.sony.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "DSgl9lC4xPdkstKgTvbMERFnffHCNAm5soJzGjqTPQU"
      short-id: "8f30f2fa8282cebc"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_4"
    type: vless
    server: "121.166.39.76"
    port: 12259
    uuid: "e911c552-3a98-41e0-b5fb-0dd3879887b7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vod.ensf.top"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/api/v1/irc"
      headers:
        Host: "vod.ensf.top"
  - name: "🇰🇷_5"
    type: vless
    server: "61.85.1.77"
    port: 12150
    uuid: "e911c552-3a98-41e0-b5fb-0dd3879887b7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vod.ensf.top"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/api/v1/irc"
      headers:
        Host: "vod.ensf.top"
  - name: "🇰🇷_6"
    type: vless
    server: "43.203.242.114"
    port: 12359
    uuid: "78990f64-7bc8-48b9-a127-0d5545593a38"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.tesla.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "8SUi1EG0YaPd7spjghl2QcZYvuJfEtPjqR9Vpzgc2Q4"
      short-id: "8f30f2fa8282cebc"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_7"
    type: vless
    server: "119.28.161.143"
    port: 443
    uuid: "1ebb0858-218a-4dee-8746-36a67bc64462"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "pR7MPTAA4cZsW9AO-twMzuogiWGMKPiheTg70fcWWWs"
      short-id: "0a427bc3"
  - name: "🇰🇷_8"
    type: vless
    server: "3.39.4.109"
    port: 18967
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_9"
    type: vless
    server: "3.39.4.109"
    port: 13672
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_10"
    type: vless
    server: "43.202.46.25"
    port: 28482
    uuid: "83973343-90db-423d-a5f7-2e3b56aeb8f4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.intel.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "8fsYG_Pg35aeg1E5Gc3HUaXou2OUQee4ukxVk99iR0s"
      short-id: "fa1e592603c283"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_11"
    type: vless
    server: "151.245.106.49"
    port: 2053
    uuid: "9f7dddc4-6c77-4e2c-bfa4-7e5afdfd48f8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "Wg07hKwQjSVmOsEHn7X1iLAXR2wkKRSyv8TZmq9ZsRA"
      short-id: "58186df4a95a1504"
  - name: "🇰🇷_12"
    type: vless
    server: "3.38.1.152"
    port: 19179
    uuid: "10dd7b2d-eda2-4a47-9f6e-5093a3cd7ded"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.intel.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "BabvzCKB_cqCz56qFQhOWIypFKFhEWo9Eyn_JPZIAxA"
      short-id: "fa1e592603c283"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_13"
    type: vless
    server: "43.108.86.165"
    port: 25636
    uuid: "0234cdd9-35ee-40a5-b698-9820f09a04f5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "3q6CuhLN7vMBISVK5PGjjlGKrRlub5VerIonNSL4c1o"
      short-id: "f34d0b76b7af0199"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_14"
    type: vless
    server: "47.80.63.187"
    port: 443
    uuid: "38e1c7e8-fdcd-4396-a84c-550b05737308"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "kr1.hat.onl"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "me6tyn-I8IolkgJK4sggSsC9sinhkLPBdPwtVlPk5TI"
      short-id: "0d6903ea350815e1"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_15"
    type: ss
    server: "141.164.45.187"
    port: 2376
    cipher: "aes-256-gcm"
    password: "faBAoD54k87UJG7"
    udp: true
  - name: "🇰🇷_16"
    type: ss
    server: "141.164.45.187"
    port: 8000
    cipher: "aes-256-gcm"
    password: "KixLvKzwjekG00rm"
    udp: true
  - name: "🇰🇷_17"
    type: ss
    server: "141.164.45.187"
    port: 6697
    cipher: "aes-256-gcm"
    password: "TEzjfAYq2IjtuoS"
    udp: true
  - name: "🇰🇷_18"
    type: ss
    server: "141.164.45.187"
    port: 8008
    cipher: "aes-256-gcm"
    password: "XKFKl2rULjIp74"
    udp: true
  - name: "🇰🇷_19"
    type: ss
    server: "141.164.45.187"
    port: 5498
    cipher: "aes-256-gcm"
    password: "lGqs95QkFHo2NV"
    udp: true
  - name: "🇰🇷_20"
    type: ss
    server: "141.164.45.187"
    port: 8008
    cipher: "aes-256-gcm"
    password: "XKFKl2rULjIp74"
    udp: true
  - name: "🇰🇷_21"
    type: ss
    server: "141.164.45.187"
    port: 7002
    cipher: "aes-256-gcm"
    password: "RexnBgU7EV5ADxG"
    udp: true
  - name: "🇰🇷_22"
    type: ss
    server: "141.164.45.187"
    port: 8091
    cipher: "aes-256-gcm"
    password: "PCnnH6SQSnfoS27"
    udp: true
  - name: "🇰🇷_23"
    type: ss
    server: "141.164.45.187"
    port: 5001
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true
  - name: "🇰🇷_24"
    type: ss
    server: "141.164.45.187"
    port: 7001
    cipher: "aes-256-gcm"
    password: "RexnBgU7EV5ADxG"
    udp: true
  - name: "🇰🇷_25"
    type: ss
    server: "141.164.45.187"
    port: 5498
    cipher: "aes-256-gcm"
    password: "lGqs95QkFHo2NV"
    udp: true
  - name: "🇰🇷_26"
    type: ss
    server: "141.164.45.187"
    port: 8000
    cipher: "aes-256-gcm"
    password: "KixLvKzwjekG00rm"
    udp: true
  - name: "🇰🇷_27"
    type: ss
    server: "141.164.45.187"
    port: 5001
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true
  - name: "🇰🇷_28"
    type: ss
    server: "141.164.45.187"
    port: 9090
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true
  - name: "🇰🇷_29"
    type: ss
    server: "141.164.45.187"
    port: 9090
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true
  - name: "🇰🇷_30"
    type: ss
    server: "141.164.45.187"
    port: 6679
    cipher: "aes-256-gcm"
    password: "TEzjfAYq2IjtuoS"
    udp: true
  - name: "🇰🇷_31"
    type: ss
    server: "141.164.45.187"
    port: 8119
    cipher: "aes-256-gcm"
    password: "cdBIDV42DCwnfIN"
    udp: true
  - name: "🇰🇷_32"
    type: ss
    server: "141.164.45.187"
    port: 8888
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇰🇷_1"
      - "🇰🇷_2"
      - "🇰🇷_3"
      - "🇰🇷_4"
      - "🇰🇷_5"
      - "🇰🇷_6"
      - "🇰🇷_7"
      - "🇰🇷_8"
      - "🇰🇷_9"
      - "🇰🇷_10"
      - "🇰🇷_11"
      - "🇰🇷_12"
      - "🇰🇷_13"
      - "🇰🇷_14"
      - "🇰🇷_15"
      - "🇰🇷_16"
      - "🇰🇷_17"
      - "🇰🇷_18"
      - "🇰🇷_19"
      - "🇰🇷_20"
      - "🇰🇷_21"
      - "🇰🇷_22"
      - "🇰🇷_23"
      - "🇰🇷_24"
      - "🇰🇷_25"
      - "🇰🇷_26"
      - "🇰🇷_27"
      - "🇰🇷_28"
      - "🇰🇷_29"
      - "🇰🇷_30"
      - "🇰🇷_31"
      - "🇰🇷_32"


rules:
  - MATCH,PROXY
