name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇰🇷_1"
    type: vless
    server: "3.39.4.109"
    port: 13672
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_2"
    type: vless
    server: "183.107.137.157"
    port: 36389
    uuid: "e06e0fb9-6328-4084-bfa4-2b61dc9f3068"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sxyyvihkektlx4rjxsdj.pkc73phpweu4rbxbatm444.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "sxyyvihkektlx4rjxsdj.pkc73phpweu4rbxbatm444.workers.dev"
  - name: "🇰🇷_3"
    type: vless
    server: "183.107.137.157"
    port: 36389
    uuid: "8d4cffc5-5b52-4cef-8059-2095c100a8a7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "wkytah9k8oggj60.qzfi0skkopy875xhtc0l9pwds.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "wkytah9k8oggj60.qzfi0skkopy875xhtc0l9pwds.workers.dev"
  - name: "🇰🇷_4"
    type: vless
    server: "158.247.201.96"
    port: 443
    uuid: "41f4cb15-5a3f-3934-89fe-b4177146adf4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "u643766u17cc9b82s180.kukuss.top"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_5"
    type: vless
    server: "183.107.137.157"
    port: 36389
    uuid: "ae6f014e-c539-4278-8f21-66c7ad2bbb47"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "kqjifhg9rw.tradsc8p9xp7wxyqmc1wy0ah.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "kqjifhg9rw.tradsc8p9xp7wxyqmc1wy0ah.workers.dev"
  - name: "🇰🇷_6"
    type: vless
    server: "220.72.143.166"
    port: 12016
    uuid: "9487e433-862e-4b53-893a-5a4f6bc911f0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "kqjifhg9rw.tradsc8p9xp7wxyqmc1wy0ah.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "kqjifhg9rw.tradsc8p9xp7wxyqmc1wy0ah.workers.dev"
  - name: "🇰🇷_7"
    type: vless
    server: "220.72.143.166"
    port: 12016
    uuid: "0735b6f3-fdaa-4413-9c98-9af58e8a9052"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "2-gys60wmzb6bqzd.qpsjn114hh3vlph9z60sesz0agjawpwroneg.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "2-gys60wmzb6bqzd.qpsjn114hh3vlph9z60sesz0agjawpwroneg.workers.dev"
  - name: "🇰🇷_8"
    type: vless
    server: "3.39.4.109"
    port: 18967
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_9"
    type: ss
    server: "141.164.45.187"
    port: 8888
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true
  - name: "🇰🇷_10"
    type: ss
    server: "141.164.45.187"
    port: 8091
    cipher: "aes-256-gcm"
    password: "PCnnH6SQSnfoS27"
    udp: true
  - name: "🇰🇷_11"
    type: ss
    server: "141.164.45.187"
    port: 6679
    cipher: "aes-256-gcm"
    password: "TEzjfAYq2IjtuoS"
    udp: true
  - name: "🇰🇷_12"
    type: ss
    server: "141.164.45.187"
    port: 8008
    cipher: "aes-256-gcm"
    password: "XKFKl2rULjIp74"
    udp: true
  - name: "🇰🇷_13"
    type: ss
    server: "141.164.45.187"
    port: 9101
    cipher: "aes-256-gcm"
    password: "e4FCWrgpkji3QY"
    udp: true
  - name: "🇰🇷_14"
    type: ss
    server: "141.164.45.187"
    port: 8888
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true
  - name: "🇰🇷_15"
    type: ss
    server: "141.164.45.187"
    port: 8000
    cipher: "aes-256-gcm"
    password: "KixLvKzwjekG00rm"
    udp: true
  - name: "🇰🇷_16"
    type: ss
    server: "141.164.45.187"
    port: 8000
    cipher: "aes-256-gcm"
    password: "KixLvKzwjekG00rm"
    udp: true
  - name: "🇰🇷_17"
    type: ss
    server: "141.164.45.187"
    port: 5498
    cipher: "aes-256-gcm"
    password: "lGqs95QkFHo2NV"
    udp: true
  - name: "🇰🇷_18"
    type: ss
    server: "141.164.45.187"
    port: 6697
    cipher: "aes-256-gcm"
    password: "TEzjfAYq2IjtuoS"
    udp: true
  - name: "🇰🇷_19"
    type: ss
    server: "141.164.45.187"
    port: 7002
    cipher: "aes-256-gcm"
    password: "RexnBgU7EV5ADxG"
    udp: true
  - name: "🇰🇷_20"
    type: ss
    server: "141.164.45.187"
    port: 9101
    cipher: "aes-256-gcm"
    password: "e4FCWrgpkji3QY"
    udp: true
  - name: "🇰🇷_21"
    type: ss
    server: "141.164.45.187"
    port: 2376
    cipher: "aes-256-gcm"
    password: "faBAoD54k87UJG7"
    udp: true
  - name: "🇰🇷_22"
    type: ss
    server: "141.164.45.187"
    port: 7001
    cipher: "aes-256-gcm"
    password: "RexnBgU7EV5ADxG"
    udp: true
  - name: "🇰🇷_23"
    type: ss
    server: "141.164.45.187"
    port: 5001
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true
  - name: "🇰🇷_24"
    type: ss
    server: "141.164.45.187"
    port: 5498
    cipher: "aes-256-gcm"
    password: "lGqs95QkFHo2NV"
    udp: true
  - name: "🇰🇷_25"
    type: ss
    server: "141.164.45.187"
    port: 9090
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true
  - name: "🇰🇷_26"
    type: ss
    server: "141.164.45.187"
    port: 8119
    cipher: "aes-256-gcm"
    password: "cdBIDV42DCwnfIN"
    udp: true
  - name: "🇰🇷_27"
    type: ss
    server: "141.164.45.187"
    port: 5001
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true
  - name: "🇰🇷_28"
    type: ss
    server: "141.164.45.187"
    port: 8008
    cipher: "aes-256-gcm"
    password: "XKFKl2rULjIp74"
    udp: true
  - name: "🇰🇷_29"
    type: ss
    server: "141.164.45.187"
    port: 9090
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇰🇷_1"
      - "🇰🇷_2"
      - "🇰🇷_3"
      - "🇰🇷_4"
      - "🇰🇷_5"
      - "🇰🇷_6"
      - "🇰🇷_7"
      - "🇰🇷_8"
      - "🇰🇷_9"
      - "🇰🇷_10"
      - "🇰🇷_11"
      - "🇰🇷_12"
      - "🇰🇷_13"
      - "🇰🇷_14"
      - "🇰🇷_15"
      - "🇰🇷_16"
      - "🇰🇷_17"
      - "🇰🇷_18"
      - "🇰🇷_19"
      - "🇰🇷_20"
      - "🇰🇷_21"
      - "🇰🇷_22"
      - "🇰🇷_23"
      - "🇰🇷_24"
      - "🇰🇷_25"
      - "🇰🇷_26"
      - "🇰🇷_27"
      - "🇰🇷_28"
      - "🇰🇷_29"


rules:
  - MATCH,PROXY
