name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇰🇷_1"
    type: vless
    server: "3.38.1.152"
    port: 19179
    uuid: "10dd7b2d-eda2-4a47-9f6e-5093a3cd7ded"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.intel.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "BabvzCKB_cqCz56qFQhOWIypFKFhEWo9Eyn_JPZIAxA"
      short-id: "fa1e592603c283"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_2"
    type: vless
    server: "43.202.46.25"
    port: 28482
    uuid: "83973343-90db-423d-a5f7-2e3b56aeb8f4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.intel.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "8fsYG_Pg35aeg1E5Gc3HUaXou2OUQee4ukxVk99iR0s"
      short-id: "fa1e592603c283"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_3"
    type: vless
    server: "kr.mkdir.kdns.fr"
    port: 443
    uuid: "2cf94f4d-9d5b-49ca-81a3-ddc0529a2dac"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ai-verps.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "ai-verps.pages.dev"
  - name: "🇰🇷_4"
    type: vless
    server: "151.245.106.49"
    port: 2053
    uuid: "579ac5bd-a43d-49d4-b83e-a9e3ddd1f706"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "k9narlSK7fUqy94_p0rrqKl52W35QLNsp3W8xaGq_Go"
      short-id: "37b4f3ae8bf23763"
  - name: "🇰🇷_5"
    type: vless
    server: "3.39.4.109"
    port: 13672
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_6"
    type: vless
    server: "152.67.211.233"
    port: 8899
    uuid: "ff334415-1a33-4c20-8301-07e1dd66fe8c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.lovelive-anime.jp"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "B7eELUOn0QM6fKSrr5v_AE4JPHQIxvb9-xX3WLqnLAk"
      short-id: "11d27eb4"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_7"
    type: vless
    server: "119.28.161.143"
    port: 443
    uuid: "1ebb0858-218a-4dee-8746-36a67bc64462"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "pR7MPTAA4cZsW9AO-twMzuogiWGMKPiheTg70fcWWWs"
      short-id: "0a427bc3"
  - name: "🇰🇷_8"
    type: vless
    server: "13.209.68.68"
    port: 8686
    uuid: "1a17b19d-4896-4531-af79-6e91d8ef8228"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    reality-opts:
      public-key: "A3NXnUIT-W0m1Y_leRnv5so2IeCvk9FCFgL31PulfTw"
      short-id: "628b3c90c98ead4f"
  - name: "🇰🇷_9"
    type: vless
    server: "3.39.4.109"
    port: 18967
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_10"
    type: trojan
    server: "154.90.62.70"
    port: 56127
    password: "p5jTPcffLgi4gaNOJd2KUTb9YEPBBD5B"
    sni: "154.90.62.70"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_11"
    type: ss
    server: "141.164.45.187"
    port: 8008
    cipher: "aes-256-gcm"
    password: "XKFKl2rULjIp74"
    udp: true
  - name: "🇰🇷_12"
    type: ss
    server: "141.164.45.187"
    port: 6697
    cipher: "aes-256-gcm"
    password: "TEzjfAYq2IjtuoS"
    udp: true
  - name: "🇰🇷_13"
    type: ss
    server: "141.164.45.187"
    port: 5001
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true
  - name: "🇰🇷_14"
    type: ss
    server: "141.164.45.187"
    port: 8000
    cipher: "aes-256-gcm"
    password: "KixLvKzwjekG00rm"
    udp: true
  - name: "🇰🇷_15"
    type: ss
    server: "141.164.45.187"
    port: 9101
    cipher: "aes-256-gcm"
    password: "e4FCWrgpkji3QY"
    udp: true
  - name: "🇰🇷_16"
    type: ss
    server: "141.164.45.187"
    port: 9090
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true
  - name: "🇰🇷_17"
    type: ss
    server: "141.164.45.187"
    port: 8091
    cipher: "aes-256-gcm"
    password: "PCnnH6SQSnfoS27"
    udp: true
  - name: "🇰🇷_18"
    type: ss
    server: "141.164.45.187"
    port: 8008
    cipher: "aes-256-gcm"
    password: "XKFKl2rULjIp74"
    udp: true
  - name: "🇰🇷_19"
    type: ss
    server: "141.164.45.187"
    port: 5001
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true
  - name: "🇰🇷_20"
    type: ss
    server: "141.164.45.187"
    port: 5498
    cipher: "aes-256-gcm"
    password: "lGqs95QkFHo2NV"
    udp: true
  - name: "🇰🇷_21"
    type: ss
    server: "141.164.45.187"
    port: 7001
    cipher: "aes-256-gcm"
    password: "RexnBgU7EV5ADxG"
    udp: true
  - name: "🇰🇷_22"
    type: ss
    server: "141.164.45.187"
    port: 2376
    cipher: "aes-256-gcm"
    password: "faBAoD54k87UJG7"
    udp: true
  - name: "🇰🇷_23"
    type: ss
    server: "141.164.45.187"
    port: 6679
    cipher: "aes-256-gcm"
    password: "TEzjfAYq2IjtuoS"
    udp: true
  - name: "🇰🇷_24"
    type: ss
    server: "141.164.45.187"
    port: 5498
    cipher: "aes-256-gcm"
    password: "lGqs95QkFHo2NV"
    udp: true
  - name: "🇰🇷_25"
    type: ss
    server: "141.164.45.187"
    port: 8888
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true
  - name: "🇰🇷_26"
    type: ss
    server: "141.164.45.187"
    port: 8000
    cipher: "aes-256-gcm"
    password: "KixLvKzwjekG00rm"
    udp: true
  - name: "🇰🇷_27"
    type: ss
    server: "141.164.45.187"
    port: 7002
    cipher: "aes-256-gcm"
    password: "RexnBgU7EV5ADxG"
    udp: true
  - name: "🇰🇷_28"
    type: ss
    server: "141.164.45.187"
    port: 9090
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true
  - name: "🇰🇷_29"
    type: ss
    server: "141.164.45.187"
    port: 8888
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true
  - name: "🇰🇷_30"
    type: ss
    server: "141.164.45.187"
    port: 9101
    cipher: "aes-256-gcm"
    password: "e4FCWrgpkji3QY"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇰🇷_1"
      - "🇰🇷_2"
      - "🇰🇷_3"
      - "🇰🇷_4"
      - "🇰🇷_5"
      - "🇰🇷_6"
      - "🇰🇷_7"
      - "🇰🇷_8"
      - "🇰🇷_9"
      - "🇰🇷_10"
      - "🇰🇷_11"
      - "🇰🇷_12"
      - "🇰🇷_13"
      - "🇰🇷_14"
      - "🇰🇷_15"
      - "🇰🇷_16"
      - "🇰🇷_17"
      - "🇰🇷_18"
      - "🇰🇷_19"
      - "🇰🇷_20"
      - "🇰🇷_21"
      - "🇰🇷_22"
      - "🇰🇷_23"
      - "🇰🇷_24"
      - "🇰🇷_25"
      - "🇰🇷_26"
      - "🇰🇷_27"
      - "🇰🇷_28"
      - "🇰🇷_29"
      - "🇰🇷_30"


rules:
  - MATCH,PROXY
