name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇰🇿_1"
    type: vless
    server: "77.73.232.61"
    port: 19747
    uuid: "2a9ed01e-5455-44b4-a66a-76ee8165f0ac"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yahoo.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "ZO9dTeg1slvTXgVsBsaJ1BDvz_YUImTLJjbHs-GdVyM"
      short-id: "2001"
  - name: "🇰🇿_2"
    type: vless
    server: "111.88.143.139"
    port: 51940
    uuid: "03464802-b517-404b-b15c-7750ffc5e78f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yahoo.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "uPHvFb_vZ3DKL-8Et_e9OliZskdSV5U1NZ66tHfC-2Y"
      short-id: "fd7f"
    network: grpc
    grpc-opts:
      grpc-service-name: ""
  - name: "🇰🇿_3"
    type: vless
    server: "111.88.143.139"
    port: 8443
    uuid: "2b8c0574-ff6f-4975-8a06-e24ebefa1d1c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "Ao_imnCEIGAaL1DZnjOK1SSPpjQOw_XJcgMpNLEZwg0"
      short-id: "ac4b582e"
    flow: "xtls-rprx-vision"
  - name: "🇰🇿_4"
    type: vless
    server: "kz.node.goidanet.com"
    port: 443
    uuid: "308cf8e0-e922-49bb-9b68-203e5aafcc97"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "kz.node.goidanet.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "xXxqDpB8gQjBddOHSOFb52xVS2Odmb63z1PYhMqe0Uo"
      short-id: "1a55b8fd25417fbf"
    network: grpc
    grpc-opts:
      grpc-service-name: ""
  - name: "🇰🇿_5"
    type: vless
    server: "178.236.16.98"
    port: 35728
    uuid: "a00d89f6-ab7e-4e30-a5e5-54c701d62c93"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yahoo.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "vhUFNoFcvtZAVMo8y5K5eU2V43m5q6yjmWIhp5RkFng"
      short-id: "69a2"
  - name: "🇰🇿_6"
    type: vless
    server: "83.222.23.81"
    port: 38065
    uuid: "4b9063e0-3288-44e9-9aac-80fbfce323a0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yahoo.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "dSSDPTK6AHfAdRAXD9i4rzqcNIY65RxlF25UyCKdiyo"
      short-id: "fa"
  - name: "🇰🇿_7"
    type: vless
    server: "185.176.26.2"
    port: 443
    uuid: "Telegram🇨🇳@WangCai2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "support.zoom.us.yxls.eu.cc"
    network: ws
    ws-opts:
      path: "/sg-amz"
      headers:
        Host: "support.zoom.us.yxls.eu.cc"
  - name: "🇰🇿_8"
    type: vless
    server: "193.124.204.145"
    port: 49853
    uuid: "5ed7b151-b781-4dba-800d-e3f824f1416f"
    udp: true
  - name: "🇰🇿_9"
    type: vless
    server: "185.176.26.2"
    port: 443
    uuid: "Telegram🇨🇳 @WangCai2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "support.zoom.us.yxls.eu.cc"
    network: ws
    ws-opts:
      path: "/sg-amz"
      headers:
        Host: "support.zoom.us.yxls.eu.cc"
  - name: "🇰🇿_10"
    type: vless
    server: "5.180.42.210"
    port: 443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nordic.cendora.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "YQTixaXzPVImuRc4TUbrFAekjIiaYV-t5S-HTKlH0AU"
      short-id: "2186a755ed67b034"
    flow: "xtls-rprx-vision"
  - name: "🇰🇿_11"
    type: vless
    server: "5.180.42.85"
    port: 443
    uuid: "5e19b3c8-c1dc-4163-95e2-895319c15d6c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cloud.mail.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "06GvG7PU5F3Hgq-vUH24tU0tpsbGMCCt26BSvlaBNUE"
      short-id: "dfbfa87e9f37f1f0"
    flow: "xtls-rprx-vision"
  - name: "🇰🇿_12"
    type: vless
    server: "5.180.40.9"
    port: 443
    uuid: "5e19b3c8-c1dc-4163-95e2-895319c15d6c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cloud.mail.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "06GvG7PU5F3Hgq-vUH24tU0tpsbGMCCt26BSvlaBNUE"
      short-id: "dfbfa87e9f37f1f0"
    flow: "xtls-rprx-vision"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇰🇿_1"
      - "🇰🇿_2"
      - "🇰🇿_3"
      - "🇰🇿_4"
      - "🇰🇿_5"
      - "🇰🇿_6"
      - "🇰🇿_7"
      - "🇰🇿_8"
      - "🇰🇿_9"
      - "🇰🇿_10"
      - "🇰🇿_11"
      - "🇰🇿_12"


rules:
  - MATCH,PROXY
