name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇱🇹_1"
    type: vless
    server: "84.32.215.94"
    port: 443
    uuid: "c5694dc5-39fd-4a92-8430-3837baa522a3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "lt.aether-runet.top"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "vrcsm8L_tY7sNbnCEdLCEjOthh_w9bdWS3wFPgsIomk"
      short-id: "4fa44664f6a566d3"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_2"
    type: vless
    server: "lt.aether-runet.top"
    port: 443
    uuid: "c5694dc5-39fd-4a92-8430-3837baa522a3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "lt.aether-runet.top"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "vrcsm8L_tY7sNbnCEdLCEjOthh_w9bdWS3wFPgsIomk"
      short-id: "4fa44664f6a566d3"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_3"
    type: vless
    server: "88.216.69.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime06.workers.dev"
  - name: "🇱🇹_4"
    type: vless
    server: "89.116.250.7"
    port: 8443
    uuid: "7967bf59-57e3-4cde-9898-527b0fe60022"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "speed.dulacloud.store"
    network: ws
    ws-opts:
      path: "/dula?Telegram-WangCai2fp=chrome"
      headers:
        Host: "speed.dulacloud.store"
  - name: "🇱🇹_5"
    type: vless
    server: "88.216.69.144"
    port: 443
    uuid: "50414e45-4c5f-5a45-5553-4d64f1370eeb"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "r5zenrelur2s.pqzdileiu8es.workers.dev"
    client-fingerprint: "ios"
    network: ws
    ws-opts:
      path: "/stream/PANEL_ZEUS/4d64f1370eeb/loc-0"
      headers:
        Host: "r5zenrelur2s.pqzdileiu8es.workers.dev"
  - name: "🇱🇹_6"
    type: vless
    server: "84.32.215.5"
    port: 443
    uuid: "c5694dc5-39fd-4a92-8430-3837baa522a3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "lt.aether-runet.top"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "vrcsm8L_tY7sNbnCEdLCEjOthh_w9bdWS3wFPgsIomk"
      short-id: "4fa44664f6a566d3"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_7"
    type: vless
    server: "94.176.234.161"
    port: 443
    uuid: "d448490d-4ee6-442f-80e1-5e1c186c4ce1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.intel.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "UpI0XKNUsMJ24XawPQ8g7br1faEsO7BOvmIIGg9Wrm8"
      short-id: "dbb2ef1c7c"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_8"
    type: vless
    server: "ltu-02.node.lumixnet.com"
    port: 443
    uuid: "8645697d-51c1-4e90-aca5-ba63a0392f11"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ltu-02.node.lumixnet.com"
    client-fingerprint: "hellochrome_120"
    reality-opts:
      public-key: "vEXgvoW9iQo6iiKT71cNt1CC3cAB4IWswAn-cScDz1A"
      short-id: "bd8a588cebc3395a"
    flow: "xtls-rprx-vision"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇱🇹_1"
      - "🇱🇹_2"
      - "🇱🇹_3"
      - "🇱🇹_4"
      - "🇱🇹_5"
      - "🇱🇹_6"
      - "🇱🇹_7"
      - "🇱🇹_8"


rules:
  - MATCH,PROXY
