name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇱🇹_1"
    type: vless
    server: "88.119.176.24"
    port: 443
    uuid: "ae8e0f7d-b661-41ca-b55d-d8c383adb2f8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "lit9.helper-internet.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "W-zf_ncm9sYALF5EqvUsxqTkYGdAw-tQczT2SqwVMGE"
      short-id: "ff776ff77be48b88"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_2"
    type: vless
    server: "194.135.83.166"
    port: 8443
    uuid: "2eadb97f-bba4-4471-8d55-bd461525a2dc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eded-52n.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "eded-52n.pages.dev"
  - name: "🇱🇹_3"
    type: vless
    server: "lt-2.kihsuyhf8jkiugsxb.cfd"
    port: 443
    uuid: "0dc1fc26-b8e9-4296-9870-0996de3c2333"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "lt-2.kihsuyhf8jkiugsxb.cfd"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "9-CBTMmqCCu_jcCDWZxcWZbY10RwhW8_l-pX-ugJNEQ"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_4"
    type: vless
    server: "144.31.243.249"
    port: 443
    uuid: "0dc1fc26-b8e9-4296-9870-0996de3c2333"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "lt-1.kihsuyhf8jkiugsxb.cfd"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "L3AYjn3nBIBik5EikZLg0G6GcwWUx24AxZ5rNzxD8TM"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_5"
    type: vless
    server: "144.31.243.148"
    port: 443
    uuid: "9e1d737e-f3c1-4757-84b2-3dcf66a468ed"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "3wa3ZmMniymkL-58bPtY7baWPxdJ6n2UaJMG7YiLiGo"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_6"
    type: vless
    server: "144.31.243.186"
    port: 443
    uuid: "cf80b5fc-c445-4373-87e6-f8a22ad10d81"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "lt.easyemploy.org"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_7"
    type: vless
    server: "5.199.171.91"
    port: 443
    uuid: "c6037cf7-d931-4027-af06-6bfb0f10684c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "apiv81.jarvesitw.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "m2b2LJrFWLTiy__FrxqnRKtnCK9g_eZPAz0Qnjdzbh4"
      short-id: "784aedb3"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_8"
    type: vless
    server: "lit9.helper-internet.com"
    port: 443
    uuid: "ae8e0f7d-b661-41ca-b55d-d8c383adb2f8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "lit9.helper-internet.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "W-zf_ncm9sYALF5EqvUsxqTkYGdAw-tQczT2SqwVMGE"
      short-id: "ff776ff77be48b88"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_9"
    type: vless
    server: "31.76.83.137"
    port: 443
    uuid: "0dc1fc26-b8e9-4296-9870-0996de3c2333"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "lt-2.kihsuyhf8jkiugsxb.cfd"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "9-CBTMmqCCu_jcCDWZxcWZbY10RwhW8_l-pX-ugJNEQ"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_10"
    type: vless
    server: "5.199.171.91"
    port: 443
    uuid: "5d8cf280-e0f4-4539-b35c-7ff90659c0d0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "apiv81.jarvesitw.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "m2b2LJrFWLTiy__FrxqnRKtnCK9g_eZPAz0Qnjdzbh4"
      short-id: "784aedb3"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_11"
    type: ss
    server: "144.31.243.2"
    port: 16015
    cipher: "chacha20-ietf-poly1305"
    password: "J1InuU6QRT5JOh1mQfkjU2"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇱🇹_1"
      - "🇱🇹_2"
      - "🇱🇹_3"
      - "🇱🇹_4"
      - "🇱🇹_5"
      - "🇱🇹_6"
      - "🇱🇹_7"
      - "🇱🇹_8"
      - "🇱🇹_9"
      - "🇱🇹_10"
      - "🇱🇹_11"


rules:
  - MATCH,PROXY
