name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇱🇹_1"
    type: vless
    server: "88.216.69.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime06.workers.dev"
  - name: "🇱🇹_2"
    type: vless
    server: "185.237.185.182"
    port: 2053
    uuid: "c7e9c591-2764-423a-afca-efbd010fd396"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "forfreeuse.rtqa.ru"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇱🇹_3"
    type: vless
    server: "144.31.243.148"
    port: 443
    uuid: "9e1d737e-f3c1-4757-84b2-3dcf66a468ed"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "3wa3ZmMniymkL-58bPtY7baWPxdJ6n2UaJMG7YiLiGo"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_4"
    type: vless
    server: "31.76.83.114"
    port: 443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "baltic.cendora.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "t_qv0VOfWhKZJV_giGC55-ipgHYWo44Yfvik_B8T8ik"
      short-id: "4a46213c935e2ee4"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_5"
    type: vless
    server: "84.32.209.7"
    port: 443
    uuid: "f1c496bf-d2ab-45be-bc13-051d60d227b7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dartsearch-cn.net"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "00n9LplaZ0VGvRS57548s7xe0deFC10pw2fkFHFPplM"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_6"
    type: vless
    server: "84.32.151.222"
    port: 443
    uuid: "27b16a66-95e0-4c20-b00b-5dff91d9c9f5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "auth.moktana.app"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "C6nh6hqFTbtizgSH8vGmw2XUxsQAbAW3jPylpgGvfl4"
      short-id: "8b6f2e4d7c1a5b9f"
    network: grpc
    grpc-opts:
      grpc-service-name: "moktana.net.v1.StreamService"
  - name: "🇱🇹_7"
    type: vless
    server: "31.76.83.114"
    port: 13443
    uuid: "5238521b-c5dd-42af-870e-c174a2aaaafe"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "auto.cendora.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "gc9oXe37KCCm3J1dJ03wdGsnxPBdeEkRPOvl_t-vfVM"
      short-id: "a7f3c91b2e6d84c0"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_8"
    type: vless
    server: "88.216.69.144"
    port: 443
    uuid: "50414e45-4c5f-5a45-5553-4d64f1370eeb"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "r5zenrelur2s.pqzdileiu8es.workers.dev"
    client-fingerprint: "ios"
    network: ws
    ws-opts:
      path: "/stream/PANEL_ZEUS/4d64f1370eeb/loc-0"
      headers:
        Host: "r5zenrelur2s.pqzdileiu8es.workers.dev"
  - name: "🇱🇹_9"
    type: trojan
    server: "195.181.244.216"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇱🇹_1"
      - "🇱🇹_2"
      - "🇱🇹_3"
      - "🇱🇹_4"
      - "🇱🇹_5"
      - "🇱🇹_6"
      - "🇱🇹_7"
      - "🇱🇹_8"
      - "🇱🇹_9"


rules:
  - MATCH,PROXY
