name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇱🇻_1"
    type: vless
    server: "85.159.228.250"
    port: 25703
    uuid: "7e5964d0-36b8-43ff-885b-86c4d3bfd466"
    udp: true
  - name: "🇱🇻_2"
    type: vless
    server: "pro-fi.emrata.top"
    port: 443
    uuid: "da86df16-a80c-48b1-90be-3e174fe0076d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pro-fi.emrata.top"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "F2VfBr2UmjDTErB_oruvW5aIvzH_xGfM2AW5_w-DF0I"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇱🇻_3"
    type: vless
    server: "195.123.208.92"
    port: 13443
    uuid: "fc1b3bda-b226-452a-8c5c-b0e36a1f8f88"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "auto.cendora.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "gc9oXe37KCCm3J1dJ03wdGsnxPBdeEkRPOvl_t-vfVM"
      short-id: "a7f3c91b2e6d84c0"
    flow: "xtls-rprx-vision"
  - name: "🇱🇻_4"
    type: vless
    server: "31.58.46.47"
    port: 1683
    uuid: "5c6d8045-9de9-45e4-b495-463fc3f1a828"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "celerisdigital.top"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "_fz8jpa604XXSweCCf6PU9Xmd7F4sZ1RSMqNTzwBVA0"
      short-id: "a4f8c92d"
    flow: "xtls-rprx-vision"
  - name: "🇱🇻_5"
    type: trojan
    server: "31.57.61.76"
    port: 2053
    password: "8r<[9'l6hAO#8ZQi"
    sni: "Koma-YT.PAGeS.Dev"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇱🇻_1"
      - "🇱🇻_2"
      - "🇱🇻_3"
      - "🇱🇻_4"
      - "🇱🇻_5"


rules:
  - MATCH,PROXY
