name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇲🇾_1"
    type: vless
    server: "216.173.67.119"
    port: 443
    uuid: "2eadb97f-bba4-4471-8d55-bd461525a2dc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eded-52n.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "eded-52n.pages.dev"
  - name: "🇲🇾_2"
    type: vless
    server: "149.118.158.90"
    port: 8443
    uuid: "2eadb97f-bba4-4471-8d55-bd461525a2dc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eded-52n.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "eded-52n.pages.dev"
  - name: "🇲🇾_3"
    type: vless
    server: "56.68.93.171"
    port: 59463
    uuid: "cb51e964-70a5-4522-9d04-d97b58fe509a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.nvidia.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "GNLuMPdi52lBbZ_9tz3nWOcKdQYVr4lzE4RX0tKQAEo"
      short-id: "2f92a5b7373b593c"
    flow: "xtls-rprx-vision"
  - name: "🇲🇾_4"
    type: vless
    server: "56.69.159.191"
    port: 53271
    uuid: "e8358eb5-7210-4cf8-982f-68af141b7694"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.tesla.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "1P58ZYmo81kPDnL4U7SnEUA-aT2R86l-o6dbFXoeDjc"
      short-id: "0a9bd9db19578964"
    flow: "xtls-rprx-vision"
  - name: "🇲🇾_5"
    type: vless
    server: "56.69.197.40"
    port: 22732
    uuid: "cb3c9f84-903b-4701-9107-701b6347b0aa"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amd.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "vHWs24ZHKIvNpToXCwB68TK0mybgKe1Yfq1Jdnas5TU"
      short-id: "2a2aa1d1366cef"
    flow: "xtls-rprx-vision"
  - name: "🇲🇾_6"
    type: vless
    server: "43.217.16.8"
    port: 21874
    uuid: "85dd8227-0f12-4826-a712-6313211774b5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amd.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "75sTDYJk8ylA97-aBhAlF1tU4OaCfdOaOSIBshPW7Bs"
      short-id: "42e853a5559e1032"
    flow: "xtls-rprx-vision"
  - name: "🇲🇾_7"
    type: trojan
    server: "47.250.84.25"
    port: 443
    password: "5931134d1cde66bf83a54acdfebe7ab2"
    sni: "moltbot.doctoroyy.net"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇲🇾_1"
      - "🇲🇾_2"
      - "🇲🇾_3"
      - "🇲🇾_4"
      - "🇲🇾_5"
      - "🇲🇾_6"
      - "🇲🇾_7"


rules:
  - MATCH,PROXY
