name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇳🇴_1"
    type: vless
    server: "151.242.169.119"
    port: 443
    uuid: "a34ecff0-a6bc-4bac-94ad-25e1f82afcbe"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yidio.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇳🇴_2"
    type: vless
    server: "151.242.169.119"
    port: 443
    uuid: "d2a3fdbd-386c-485c-a6d4-74dea3f970d8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yidio.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇳🇴_3"
    type: vless
    server: "31.76.5.159"
    port: 443
    uuid: "cd3bb7d9-7df3-4644-ac05-c260990ac277"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "norway-4.moritech.net"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇳🇴_4"
    type: vless
    server: "151.242.169.119"
    port: 443
    uuid: "403c3476-202d-4471-b615-40c8a2b503be"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yidio.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇳🇴_5"
    type: vless
    server: "31.76.5.158"
    port: 443
    uuid: "cd3bb7d9-7df3-4644-ac05-c260990ac277"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "norway-3.moritech.net"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇳🇴_6"
    type: vless
    server: "viper-24.moriarty-web.com"
    port: 443
    uuid: "cd3bb7d9-7df3-4644-ac05-c260990ac277"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "viper-24.moriarty-web.com"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇳🇴_7"
    type: vless
    server: "31.76.5.3"
    port: 443
    uuid: "cd3bb7d9-7df3-4644-ac05-c260990ac277"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "viper-26.moriarty-web.com"
    client-fingerprint: "chrome"
    flow: "xtls-rprx-vision"
  - name: "🇳🇴_8"
    type: vless
    server: "151.242.168.125"
    port: 390
    uuid: "7b363f9c-3df9-4b60-a789-9cd36be0bdfe"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bowandbead.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "5RCgAVjaT7hwdVIKAEULswXGqR127ZOZV6X17nEhYk8"
      short-id: "b545fe8c5e22f92d"
    flow: "xtls-rprx-vision"
  - name: "🇳🇴_9"
    type: vless
    server: "151.242.169.119"
    port: 443
    uuid: "0d4e04b1-5ab5-4525-bbd4-ffce30149bee"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yidio.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇳🇴_10"
    type: vless
    server: "46.29.238.88"
    port: 40443
    uuid: "db320947-adfb-400d-b60b-383b8324bffe"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "deepl.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "aZOpodpnifoxDqTzWgxJRffgsiGnG9-h-EZd4SvOImc"
      short-id: "f7b2"
  - name: "🇳🇴_11"
    type: vless
    server: "89.185.81.65"
    port: 40443
    uuid: "ed91e79c-f6bf-4fba-8cc0-6d45acaec22b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "deepl.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "dvx6zPztKbgHpYaW6J4OZQC74Uy0JS6HUVdDfbjG5V4"
      short-id: "7606"
  - name: "🇳🇴_12"
    type: vless
    server: "151.242.169.119"
    port: 443
    uuid: "1859decf-1af7-4a75-a461-221f5d2df6f5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yidio.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇳🇴_13"
    type: vless
    server: "31.76.5.2"
    port: 443
    uuid: "cd3bb7d9-7df3-4644-ac05-c260990ac277"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "viper-25.moriarty-web.com"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇳🇴_14"
    type: vless
    server: "151.242.168.125"
    port: 390
    uuid: "b02ff150-ee30-46e0-9ea1-adbfd7762a06"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bowandbead.com"
    client-fingerprint: "ios"
    reality-opts:
      public-key: "5RCgAVjaT7hwdVIKAEULswXGqR127ZOZV6X17nEhYk8"
      short-id: "b545fe8c5e22f92d"
    flow: "xtls-rprx-vision"
  - name: "🇳🇴_15"
    type: vless
    server: "151.242.169.119"
    port: 443
    uuid: "95900b48-01b8-44a1-a871-756ec65cb57e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yidio.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇳🇴_16"
    type: vless
    server: "151.242.169.119"
    port: 443
    uuid: "10de5732-5d62-43bd-80a2-ec678100824a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yidio.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
    flow: "xtls-rprx-vision"
  - name: "🇳🇴_17"
    type: vless
    server: "31.76.5.0"
    port: 443
    uuid: "cd3bb7d9-7df3-4644-ac05-c260990ac277"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "viper-23.moriarty-web.com"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇳🇴_18"
    type: ss
    server: "185.213.23.63"
    port: 990
    cipher: "chacha20-ietf-poly1305"
    password: "ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44="
    udp: true
  - name: "🇳🇴_19"
    type: ss
    server: "185.213.23.63"
    port: 990
    cipher: "chacha20-ietf-poly1305"
    password: "ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44="
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇳🇴_1"
      - "🇳🇴_2"
      - "🇳🇴_3"
      - "🇳🇴_4"
      - "🇳🇴_5"
      - "🇳🇴_6"
      - "🇳🇴_7"
      - "🇳🇴_8"
      - "🇳🇴_9"
      - "🇳🇴_10"
      - "🇳🇴_11"
      - "🇳🇴_12"
      - "🇳🇴_13"
      - "🇳🇴_14"
      - "🇳🇴_15"
      - "🇳🇴_16"
      - "🇳🇴_17"
      - "🇳🇴_18"
      - "🇳🇴_19"


rules:
  - MATCH,PROXY
