name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇵🇱_1"
    type: vless
    server: "83.168.95.145"
    port: 443
    uuid: "82f37352-85e5-49bb-9edc-a80997065659"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "AcuvO982QLzf76fVydfSuJIiF5520rmj7AxpaxyRwUg"
      short-id: "d345ad4657adeef9"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_2"
    type: vless
    server: "94.183.157.156"
    port: 443
    uuid: "4abdfe42-aec7-4b66-974d-3f891e2e8184"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl.gaz-service.shop"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SoMfQzFhE5QfKWMZA7ZNkYP63P5hiyWEbE9fsPIP4Go"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_3"
    type: vless
    server: "34.118.43.106"
    port: 443
    uuid: "16e310b7-659e-45ee-a4b0-10e0289b8621"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "-bjPqNKxxGTKCmH6dwsdGRTUzuatAowBWxyOPW4BiVQ"
      short-id: "7e7623474d41f032"
  - name: "🇵🇱_4"
    type: vless
    server: "50.7.248.234"
    port: 443
    uuid: "cd3bb7d9-7df3-4644-ac05-c260990ac277"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "viper-22.moriarty-web.com"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_5"
    type: vless
    server: "70.34.255.101"
    port: 80
    uuid: "a889262f-5fe3-4c93-9aaa-3721318dd389"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "🇵🇱_6"
    type: vless
    server: "bober.nightfall.best"
    port: 443
    uuid: "af2bf319-ba88-4fec-8317-2b6a8cee96d1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bober.nightfall.best"
    client-fingerprint: "firefox"
    network: grpc
    grpc-opts:
      grpc-service-name: "rdamrwhuacfl"
  - name: "🇵🇱_7"
    type: vless
    server: "149.86.227.16"
    port: 443
    uuid: "733b2a78-9306-4bbc-a3a0-b8bfb55f430a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pmv.raketa-balance.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "JaP4bhvIMW-l7T0_RkLra59DeBYI6W9XemKa8MyRPSY"
      short-id: "6c6082a2223c1d03"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_8"
    type: vless
    server: "54.37.136.194"
    port: 2053
    uuid: "e8a432c8-5d84-49a5-b822-67ed761a58f9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "Vemd9Jjk5xKO8qSC3g8VVagwcb4J1BcTvp86CswQC0A"
      short-id: "50ba05992b05c1c3"
  - name: "🇵🇱_9"
    type: vless
    server: "144.31.2.33"
    port: 443
    uuid: "cd3bb7d9-7df3-4644-ac05-c260990ac277"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl3.moritech.net"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_10"
    type: vless
    server: "2.59.253.251"
    port: 443
    uuid: "adc11f30-e4cb-4985-bf5e-f9ded69c019f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nvidia.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "fNfokzklCF4l_c8k8PciOCjm5ecNoF_sNLjEtaO-xzI"
      short-id: "db04ce8bdb8900f1"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_11"
    type: vless
    server: "83.168.71.216"
    port: 443
    uuid: "a18f7c2d-9e45-4b8a-af3c-1d5e7f9c8b2a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ads.x5.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "8h8t5eBWL9oERK7xWHQLFJE5j6sZdgNDQAs3EGnNbho"
      short-id: "2f49bccf11150ef2"
  - name: "🇵🇱_12"
    type: vless
    server: "50.7.249.66"
    port: 443
    uuid: "cd3bb7d9-7df3-4644-ac05-c260990ac277"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl-new-ded2.moritech.net"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_13"
    type: vless
    server: "82.118.22.161"
    port: 443
    uuid: "05488656-d4bf-4634-8b2e-e4ff5a56c7e2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "xY1KpNxaIGmi6jfeudYQ_aaLGQqWK_uHStnwUFd2_2E"
      short-id: "fa3ea655619a3e78"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_14"
    type: vless
    server: "185.193.31.7"
    port: 8443
    uuid: "7967bf59-57e3-4cde-9898-527b0fe60022"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "speed.dulacloud.store"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/dula?Telegram-WangCai2"
      headers:
        Host: "speed.dulacloud.store"
  - name: "🇵🇱_15"
    type: vless
    server: "83.168.68.59"
    port: 443
    uuid: "8dbcb4ef-65bf-4890-a257-c32073689ee8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "smotret.tv"
    client-fingerprint: "random"
    reality-opts:
      public-key: "UmiO58uvMjH4a9DIkUbLCy5EJYncSsraFFtiJS_oinU"
      short-id: "4e85d77e533afc1c"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_16"
    type: vless
    server: "144.31.4.193"
    port: 444
    uuid: "318c935d-c195-41d3-99ad-9bbcfdab3386"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl.srv.vbuste-bot.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "0-or5ogGhYbBgsVSrSC2Fhxyp2BN97Y9pqIdg61Qd08"
      short-id: "4be4110078ebed4a"
    network: grpc
    grpc-opts:
      grpc-service-name: ""
  - name: "🇵🇱_17"
    type: vless
    server: "185.193.30.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime09.workers.dev"
  - name: "🇵🇱_18"
    type: vless
    server: "83.168.95.145"
    port: 443
    uuid: "f28e0ce1-ed75-4e90-b069-5215a80dfb4a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "google.com"
    client-fingerprint: "safari"
    reality-opts:
      public-key: "AcuvO982QLzf76fVydfSuJIiF5520rmj7AxpaxyRwUg"
      short-id: "d345ad4657adeef9"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_19"
    type: vless
    server: "pl3.moritech.net"
    port: 443
    uuid: "cd3bb7d9-7df3-4644-ac05-c260990ac277"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl3.moritech.net"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_20"
    type: vless
    server: "141.101.120.129"
    port: 80
    uuid: "3087ca05-1a7c-45fa-aec9-805adeaedb1b"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "tianshu.kevqwkt451.workers.dev"
  - name: "🇵🇱_21"
    type: vless
    server: "83.168.107.220"
    port: 443
    uuid: "b1813cbd-831f-4cb3-baf8-5bc0cc8298bc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "s0lbZ5BO3ctZjE8DzsXkNL0NvLl6FgLG6532NQzXigo"
      short-id: "c56d4f1c"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_22"
    type: vless
    server: "150.251.113.34"
    port: 443
    uuid: "d7d724b5-17ce-4f3c-877d-dfbf0f07afa1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "8yMLSTbkpJFfbgTjNzotzz7U8OT6AERrclgKdKrXXW8"
      short-id: "150a627d15154cf2"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_23"
    type: vless
    server: "95.85.253.202"
    port: 443
    uuid: "4314a583-3a39-45e1-883e-70bf570d252a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl0001.kubservice.icu"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "z-TKWOWgZLfzQ-wNdwXQqVwaUgCmbchM2Xtrk1NGynU"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_24"
    type: vless
    server: "145.239.30.17"
    port: 2053
    uuid: "9ef61079-6f7d-4911-9608-943da85d8e6f"
    udp: true
  - name: "🇵🇱_25"
    type: vless
    server: "95.81.75.9"
    port: 57160
    uuid: "68ad9a6d-2463-4c31-92a7-31547b9d4783"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "funpay.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "Tbu7sr_pvHngDWFIa0ApL5UL9vEGxlHESd9g53KQehw"
      short-id: "77b5"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_26"
    type: trojan
    server: "cheerful-swan.rooster465.autos"
    port: 443
    password: "UX82473651"
    sni: "cheerful-swan.rooster465.autos"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇵🇱_1"
      - "🇵🇱_2"
      - "🇵🇱_3"
      - "🇵🇱_4"
      - "🇵🇱_5"
      - "🇵🇱_6"
      - "🇵🇱_7"
      - "🇵🇱_8"
      - "🇵🇱_9"
      - "🇵🇱_10"
      - "🇵🇱_11"
      - "🇵🇱_12"
      - "🇵🇱_13"
      - "🇵🇱_14"
      - "🇵🇱_15"
      - "🇵🇱_16"
      - "🇵🇱_17"
      - "🇵🇱_18"
      - "🇵🇱_19"
      - "🇵🇱_20"
      - "🇵🇱_21"
      - "🇵🇱_22"
      - "🇵🇱_23"
      - "🇵🇱_24"
      - "🇵🇱_25"
      - "🇵🇱_26"


rules:
  - MATCH,PROXY
