name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇵🇱_1"
    type: vless
    server: "194.93.63.227"
    port: 443
    uuid: "ff1b0b50-70dc-4bae-866e-55cff86f4d6d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "lbvzo.falsemirrov.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "FiGwAuKMy_5VK62hqCxDZn1jUjrplWTM1RmAwoA5o1w"
      short-id: "0d6c02fda165f38c"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_2"
    type: vless
    server: "83.168.71.216"
    port: 443
    uuid: "a18f7c2d-9e45-4b8a-af3c-1d5e7f9c8b2a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ads.x5.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "8h8t5eBWL9oERK7xWHQLFJE5j6sZdgNDQAs3EGnNbho"
      short-id: "2f49bccf11150ef2"
  - name: "🇵🇱_3"
    type: vless
    server: "31.56.188.152"
    port: 443
    uuid: "551955b3-46e9-5129-95c9-e7474c15ed6b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl11.fast-connect-service.site"
    client-fingerprint: "chrome"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_4"
    type: vless
    server: "95.85.253.134"
    port: 443
    uuid: "8033102198"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl5.fast-connect-service.site"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_5"
    type: vless
    server: "141.101.120.73"
    port: 443
    uuid: "5d8eb33a-2166-4daf-88fe-4be5799c493b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "noisy-term-e657.airdrop2014aa5168.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "noisy-term-e657.airdrop2014aa5168.workers.dev"
  - name: "🇵🇱_6"
    type: vless
    server: "95.85.227.142"
    port: 443
    uuid: "a34b5e88-cf0d-4c01-8199-2d1002d3c787"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.wikihow.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "HKpd1sbrhBds8SJSL0d22MAq_QyTR6EP6y5b5DYol3U"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_7"
    type: vless
    server: "2.59.163.45"
    port: 59992
    uuid: "9a9fe945-246a-431e-bd05-1cb981464c8d"
    udp: true
  - name: "🇵🇱_8"
    type: vless
    server: "18.244.146.94"
    port: 443
    uuid: "7ce54bb3-d612-4aa7-be08-089d3c461d53"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d1yxsk0zprgivr.cloudfront.net"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇵🇱_9"
    type: vless
    server: "95.85.253.134"
    port: 443
    uuid: "551955b3-46e9-5129-95c9-e7474c15ed6b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl5.fast-connect-service.site"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_10"
    type: vless
    server: "144.31.171.233"
    port: 443
    uuid: "551955b3-46e9-5129-95c9-e7474c15ed6b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl6.fast-connect-service.site"
    client-fingerprint: "chrome"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_11"
    type: vless
    server: "103.68.110.42"
    port: 443
    uuid: "8033102198"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl1.fast-connect-service.site"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_12"
    type: vless
    server: "62.132.117.11"
    port: 43439
    uuid: "94a5294d-1125-4139-8934-380c5de5552f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn.24cloudplay.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "b4n1pcO8ST3JkGtj8YymXVrW17LEe2EHec5wY7hMMR4"
      short-id: "ae99c61853e8a6ae"
    network: grpc
    grpc-opts:
      grpc-service-name: "streaming"
  - name: "🇵🇱_13"
    type: vless
    server: "128.204.223.94"
    port: 9815
    uuid: "37a0bd7c-8b9f-4693-8916-bd1e2da0a817"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "🇵🇱_14"
    type: vless
    server: "82.26.91.166"
    port: 26391
    uuid: "23f2fcb8-3b1c-4246-9751-0888f703e9ad"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "proxy11.h1guro.ovh"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "dxuGa3gRo3CPwx1TcaAM9GLkgVBnGcUpDjUfrX8CuiU"
      short-id: "09e67e78ad6bf369"
    network: grpc
    grpc-opts:
      grpc-service-name: ""
  - name: "🇵🇱_15"
    type: vless
    server: "82.40.62.4"
    port: 443
    uuid: "194302fe-9c53-4203-b17e-c0b30a4d79b6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.intel.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "hgQ3Wa09f9ectEos7QyC1LQ8bBq8lEAcAtGIDFTKin0"
      short-id: "c0"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_16"
    type: vless
    server: "2.26.255.36"
    port: 8443
    uuid: "8787dd0a-095a-414e-804f-a7d16a1ae166"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "po1.hys.braidx.tech"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_17"
    type: vless
    server: "144.31.112.199"
    port: 443
    uuid: "8033102198"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl2.fast-connect-service.site"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_18"
    type: vless
    server: "144.31.171.233"
    port: 443
    uuid: "8033102198"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl6.fast-connect-service.site"
    client-fingerprint: "chrome"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_19"
    type: vless
    server: "18.244.146.24"
    port: 443
    uuid: "7ce54bb3-d612-4aa7-be08-089d3c461d53"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d1yxsk0zprgivr.cloudfront.net"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇵🇱_20"
    type: vless
    server: "201.3.225.13"
    port: 443
    uuid: "76713d07-5a6b-49c2-abd8-bc450a2fa7fc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "uwu.spectrumproxy.shop"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "EyzTSZxq5qlUT2xW0l7VP-DzIh2ucabMan9ekEv9Owo"
      short-id: "143627f1"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_21"
    type: vless
    server: "103.68.110.42"
    port: 443
    uuid: "551955b3-46e9-5129-95c9-e7474c15ed6b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl1.fast-connect-service.site"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_22"
    type: vless
    server: "82.26.91.87"
    port: 443
    uuid: "7e760d89-a8f4-4a87-8f10-b4af28c61b7f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "faster.yandex-apicloud.ru"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_23"
    type: vless
    server: "18.244.146.6"
    port: 443
    uuid: "7ce54bb3-d612-4aa7-be08-089d3c461d53"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d1yxsk0zprgivr.cloudfront.net"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇵🇱_24"
    type: vless
    server: "18.244.146.80"
    port: 443
    uuid: "7ce54bb3-d612-4aa7-be08-089d3c461d53"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d1yxsk0zprgivr.cloudfront.net"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇵🇱_25"
    type: vless
    server: "54.37.136.194"
    port: 2053
    uuid: "a60bc8c8-1447-4f2c-a09c-c4293b257fd8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "JldKt40jK4uwPfwxy5RNZSvMf11bHIEphKmPNEmlRmg"
      short-id: "6c3d30b55a969136"
  - name: "🇵🇱_26"
    type: vless
    server: "83.168.108.200"
    port: 443
    uuid: "fbb74aa8-b89a-4f20-9504-6b25aadf6681"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pol3.freeinternat.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "bZpzmeWiEJyJQy0W2hHc34Nr6BuFXj1UDd80Cbwh1Fk"
      short-id: "ff776ff77be48b88"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_27"
    type: vless
    server: "141.101.120.129"
    port: 80
    uuid: "3087ca05-1a7c-45fa-aec9-805adeaedb1b"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "tianshu.kevqwkt451.workers.dev"
  - name: "🇵🇱_28"
    type: vless
    server: "31.56.188.152"
    port: 443
    uuid: "8033102198"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl11.fast-connect-service.site"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_29"
    type: vless
    server: "95.85.253.5"
    port: 443
    uuid: "551955b3-46e9-5129-95c9-e7474c15ed6b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl4.fast-connect-service.site"
    client-fingerprint: "chrome"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_30"
    type: vless
    server: "95.85.253.5"
    port: 443
    uuid: "8033102198"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl4.fast-connect-service.site"
    client-fingerprint: "chrome"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_31"
    type: trojan
    server: "202.78.163.148"
    port: 443
    password: "ND91608427"
    sni: "discrete-basilisk.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇵🇱_32"
    type: trojan
    server: "31.76.251.127"
    port: 443
    password: "32b2m2w7hsdd93z7"
    sni: "31.76.251.127.cdn-one.org"
    skip-cert-verify: true
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "/28786/4U7gXXHftA"
  - name: "🇵🇱_33"
    type: trojan
    server: "relaxed-gull.rooster465.autos"
    port: 443
    password: "ND91608427"
    sni: "relaxed-gull.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇵🇱_34"
    type: trojan
    server: "31.76.251.127"
    port: 443
    password: "581e14a5fcc14107b9326cc54f047891"
    sni: "31.76.251.127.cdn-one.org"
    skip-cert-verify: true
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "/28786/4U7gXXHftA"
  - name: "🇵🇱_35"
    type: trojan
    server: "202.78.163.248"
    port: 443
    password: "ND91608427"
    sni: "relaxed-gull.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇵🇱_36"
    type: ss
    server: "194.61.121.93"
    port: 7538
    cipher: "chacha20-ietf-poly1305"
    password: "U9YAoqBgg5VyGBc6vQv1sN"
    udp: true
  - name: "🇵🇱_37"
    type: ss
    server: "92.118.205.211"
    port: 5600
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true
  - name: "🇵🇱_38"
    type: ss
    server: "92.118.205.211"
    port: 5600
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇵🇱_1"
      - "🇵🇱_2"
      - "🇵🇱_3"
      - "🇵🇱_4"
      - "🇵🇱_5"
      - "🇵🇱_6"
      - "🇵🇱_7"
      - "🇵🇱_8"
      - "🇵🇱_9"
      - "🇵🇱_10"
      - "🇵🇱_11"
      - "🇵🇱_12"
      - "🇵🇱_13"
      - "🇵🇱_14"
      - "🇵🇱_15"
      - "🇵🇱_16"
      - "🇵🇱_17"
      - "🇵🇱_18"
      - "🇵🇱_19"
      - "🇵🇱_20"
      - "🇵🇱_21"
      - "🇵🇱_22"
      - "🇵🇱_23"
      - "🇵🇱_24"
      - "🇵🇱_25"
      - "🇵🇱_26"
      - "🇵🇱_27"
      - "🇵🇱_28"
      - "🇵🇱_29"
      - "🇵🇱_30"
      - "🇵🇱_31"
      - "🇵🇱_32"
      - "🇵🇱_33"
      - "🇵🇱_34"
      - "🇵🇱_35"
      - "🇵🇱_36"
      - "🇵🇱_37"
      - "🇵🇱_38"


rules:
  - MATCH,PROXY
