name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇵🇱_1"
    type: vless
    server: "132.243.212.205"
    port: 41503
    uuid: "62b48343-0e69-4c10-90e8-eb7516455790"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "github.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "RIGmegmuEpwjJWkWnJF_woRYpLH5h8d_3uZQrcqgeRs"
      short-id: "d66024"
  - name: "🇵🇱_2"
    type: vless
    server: "31.133.0.70"
    port: 2053
    uuid: "c7e9c591-2764-423a-afca-efbd010fd396"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "forfreeuse.rtqa.ru"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇵🇱_3"
    type: vless
    server: "38.180.50.4"
    port: 8443
    uuid: "1f113ca6-7b95-4abb-9348-adfb2187e399"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tutdesignstudio.site"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_4"
    type: vless
    server: "145.239.85.117"
    port: 2053
    uuid: "c7e9c591-2764-423a-afca-efbd010fd396"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "forfreeuse.rtqa.ru"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇵🇱_5"
    type: vless
    server: "18.244.146.94"
    port: 443
    uuid: "7ce54bb3-d612-4aa7-be08-089d3c461d53"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d1yxsk0zprgivr.cloudfront.net"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇵🇱_6"
    type: vless
    server: "128.204.223.94"
    port: 9815
    uuid: "37a0bd7c-8b9f-4693-8916-bd1e2da0a817"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "🇵🇱_7"
    type: vless
    server: "194.61.121.94"
    port: 443
    uuid: "348b1b7d-fe7b-43f9-84b5-a2917925c8a8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl3.freehiliters.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "jIq_COD-tIXTvgDn-TslFGtB_a8HVgUOOIlUByv8fkg"
      short-id: "8718c58d3d51db59"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_8"
    type: vless
    server: "95.85.227.142"
    port: 443
    uuid: "a34b5e88-cf0d-4c01-8199-2d1002d3c787"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.wikihow.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "HKpd1sbrhBds8SJSL0d22MAq_QyTR6EP6y5b5DYol3U"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_9"
    type: vless
    server: "132.243.212.154"
    port: 26417
    uuid: "48cb335c-2210-4f81-bde9-e9c8d454ed7b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "github.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "UIW5K60pwiph20ht5dLF22CmD68KphGRiYTBK0wBXXw"
      short-id: "deff65"
  - name: "🇵🇱_10"
    type: vless
    server: "178.17.59.15"
    port: 2066
    uuid: "24f8209b-6689-4e7a-b067-f886e04dfc43"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ads.x5.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "XIBKbglsQ9pI4eo26LoUkmNxnVqlKtxZRO0H91v3jF0"
      short-id: "1b2a3f"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_11"
    type: vless
    server: "18.244.146.6"
    port: 443
    uuid: "7ce54bb3-d612-4aa7-be08-089d3c461d53"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d1yxsk0zprgivr.cloudfront.net"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇵🇱_12"
    type: vless
    server: "94.183.209.43"
    port: 443
    uuid: "5e7ecc47-e424-4653-876e-c7515a2c82b4"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "🇵🇱_13"
    type: vless
    server: "150.251.113.34"
    port: 443
    uuid: "d7d724b5-17ce-4f3c-877d-dfbf0f07afa1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "8yMLSTbkpJFfbgTjNzotzz7U8OT6AERrclgKdKrXXW8"
      short-id: "150a627d15154cf2"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_14"
    type: vless
    server: "201.3.225.13"
    port: 443
    uuid: "76713d07-5a6b-49c2-abd8-bc450a2fa7fc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "uwu.spectrumproxy.shop"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "EyzTSZxq5qlUT2xW0l7VP-DzIh2ucabMan9ekEv9Owo"
      short-id: "143627f1"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_15"
    type: vless
    server: "pol4.o4ka-internet.com"
    port: 443
    uuid: "2cb6b4d9-0c74-45e2-a4fb-645bb8ac532a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pol4.o4ka-internet.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "V2JprbR_aJkS7uX6anyU3nrswGxdvDQT2HpY4WnzuC8"
      short-id: "5629431325884ff0"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_16"
    type: vless
    server: "31.133.0.133"
    port: 2053
    uuid: "c7e9c591-2764-423a-afca-efbd010fd396"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "forfreeuse.rtqa.ru"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇵🇱_17"
    type: vless
    server: "18.244.146.24"
    port: 443
    uuid: "7ce54bb3-d612-4aa7-be08-089d3c461d53"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d1yxsk0zprgivr.cloudfront.net"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇵🇱_18"
    type: vless
    server: "194.61.121.102"
    port: 443
    uuid: "348b1b7d-fe7b-43f9-84b5-a2917925c8a8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl3.freehiliters.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "jIq_COD-tIXTvgDn-TslFGtB_a8HVgUOOIlUByv8fkg"
      short-id: "8718c58d3d51db59"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_19"
    type: vless
    server: "144.31.241.47"
    port: 443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eu-central.cendora.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "b-Cm9hX-3UHsS1L_lnUB6AMjuKhlN1IDdBbZ506itjI"
      short-id: "00bca5982f82d083"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_20"
    type: vless
    server: "31.133.0.49"
    port: 2053
    uuid: "c7e9c591-2764-423a-afca-efbd010fd396"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "forfreeuse.rtqa.ru"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇵🇱_21"
    type: vless
    server: "95.85.254.114"
    port: 443
    uuid: "2cb6b4d9-0c74-45e2-a4fb-645bb8ac532a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pol4.o4ka-internet.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "V2JprbR_aJkS7uX6anyU3nrswGxdvDQT2HpY4WnzuC8"
      short-id: "5629431325884ff0"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_22"
    type: vless
    server: "2.26.255.36"
    port: 8443
    uuid: "8787dd0a-095a-414e-804f-a7d16a1ae166"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "po1.hys.braidx.tech"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_23"
    type: vless
    server: "83.168.71.216"
    port: 443
    uuid: "a18f7c2d-9e45-4b8a-af3c-1d5e7f9c8b2a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ads.x5.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "8h8t5eBWL9oERK7xWHQLFJE5j6sZdgNDQAs3EGnNbho"
      short-id: "2f49bccf11150ef2"
  - name: "🇵🇱_24"
    type: vless
    server: "pl-1.p-esmy.icu"
    port: 2066
    uuid: "24f8209b-6689-4e7a-b067-f886e04dfc43"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ads.x5.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "XIBKbglsQ9pI4eo26LoUkmNxnVqlKtxZRO0H91v3jF0"
      short-id: "1b2a3f"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_25"
    type: vless
    server: "31.133.0.103"
    port: 2053
    uuid: "c7e9c591-2764-423a-afca-efbd010fd396"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "forfreeuse.rtqa.ru"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇵🇱_26"
    type: vless
    server: "18.244.146.80"
    port: 443
    uuid: "7ce54bb3-d612-4aa7-be08-089d3c461d53"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d1yxsk0zprgivr.cloudfront.net"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇵🇱_27"
    type: vless
    server: "tutdesignstudio.site"
    port: 8443
    uuid: "38cc34e9-9973-439c-b61b-3d89b798d571"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tutdesignstudio.site"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_28"
    type: vless
    server: "94.183.157.121"
    port: 13443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "auto.cendora.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "gc9oXe37KCCm3J1dJ03wdGsnxPBdeEkRPOvl_t-vfVM"
      short-id: "a7f3c91b2e6d84c0"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_29"
    type: vless
    server: "94.183.157.121"
    port: 443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eu-central.cendora.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "b-Cm9hX-3UHsS1L_lnUB6AMjuKhlN1IDdBbZ506itjI"
      short-id: "00bca5982f82d083"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_30"
    type: vless
    server: "38.180.50.4"
    port: 8443
    uuid: "38cc34e9-9973-439c-b61b-3d89b798d571"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tutdesignstudio.site"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_31"
    type: vless
    server: "144.31.171.143"
    port: 443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eu-central.cendora.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "b-Cm9hX-3UHsS1L_lnUB6AMjuKhlN1IDdBbZ506itjI"
      short-id: "00bca5982f82d083"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_32"
    type: vless
    server: "tutdesignstudio.site"
    port: 8443
    uuid: "1f113ca6-7b95-4abb-9348-adfb2187e399"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tutdesignstudio.site"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_33"
    type: vless
    server: "31.133.0.240"
    port: 2053
    uuid: "c7e9c591-2764-423a-afca-efbd010fd396"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "forfreeuse.rtqa.ru"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇵🇱_34"
    type: vless
    server: "54.37.136.194"
    port: 2053
    uuid: "a60bc8c8-1447-4f2c-a09c-c4293b257fd8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "JldKt40jK4uwPfwxy5RNZSvMf11bHIEphKmPNEmlRmg"
      short-id: "6c3d30b55a969136"
  - name: "🇵🇱_35"
    type: trojan
    server: "202.78.163.89"
    port: 443
    password: "AE62539071"
    sni: "tolerant-mosquito.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇵🇱_36"
    type: trojan
    server: "202.78.163.19"
    port: 443
    password: "AE62539071"
    sni: "game-firefly.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇵🇱_37"
    type: trojan
    server: "202.78.163.233"
    port: 443
    password: "FH72359861"
    sni: "magnetic-caiman.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇵🇱_38"
    type: trojan
    server: "more-trout.rooster465.autos"
    port: 443
    password: "PQ05174892"
    sni: "more-trout.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇵🇱_39"
    type: trojan
    server: "202.78.163.132"
    port: 443
    password: "AE62539071"
    sni: "relative-locust.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇵🇱_40"
    type: trojan
    server: "202.78.163.100"
    port: 443
    password: "AE62539071"
    sni: "enough-basilisk.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇵🇱_41"
    type: trojan
    server: "game-firefly.rooster465.autos"
    port: 443
    password: "AE62539071"
    sni: "game-firefly.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇵🇱_42"
    type: trojan
    server: "game-firefly.rooster465.autos"
    port: 443
    password: "FH72359861"
    sni: "game-firefly.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇵🇱_43"
    type: trojan
    server: "electric-sturgeon.rooster465.autos"
    port: 443
    password: "PQ05174892"
    sni: "electric-sturgeon.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇵🇱_44"
    type: trojan
    server: "202.78.163.148"
    port: 443
    password: "ND91608427"
    sni: "discrete-basilisk.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇵🇱_45"
    type: trojan
    server: "relaxed-gull.rooster465.autos"
    port: 443
    password: "ND91608427"
    sni: "relaxed-gull.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇵🇱_46"
    type: trojan
    server: "202.78.163.156"
    port: 443
    password: "FH72359861"
    sni: "primary-leech.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇵🇱_47"
    type: trojan
    server: "202.78.163.248"
    port: 443
    password: "ND91608427"
    sni: "relaxed-gull.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇵🇱_48"
    type: ss
    server: "64.176.73.160"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "VJtsgllDDJfNmaTe"
    udp: true
  - name: "🇵🇱_49"
    type: ss
    server: "54.36.174.134"
    port: 443
    cipher: "chacha20-ietf-poly1305"
    password: "ytw2awn"
    udp: true
  - name: "🇵🇱_50"
    type: ss
    server: "92.118.205.211"
    port: 5600
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true
  - name: "🇵🇱_51"
    type: ss
    server: "92.118.205.211"
    port: 5600
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true
  - name: "🇵🇱_52"
    type: ss
    server: "194.61.121.93"
    port: 7538
    cipher: "chacha20-ietf-poly1305"
    password: "U9YAoqBgg5VyGBc6vQv1sN"
    udp: true
  - name: "🇵🇱_53"
    type: ss
    server: "54.36.174.140"
    port: 443
    cipher: "chacha20-ietf-poly1305"
    password: "ytw2awn"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇵🇱_1"
      - "🇵🇱_2"
      - "🇵🇱_3"
      - "🇵🇱_4"
      - "🇵🇱_5"
      - "🇵🇱_6"
      - "🇵🇱_7"
      - "🇵🇱_8"
      - "🇵🇱_9"
      - "🇵🇱_10"
      - "🇵🇱_11"
      - "🇵🇱_12"
      - "🇵🇱_13"
      - "🇵🇱_14"
      - "🇵🇱_15"
      - "🇵🇱_16"
      - "🇵🇱_17"
      - "🇵🇱_18"
      - "🇵🇱_19"
      - "🇵🇱_20"
      - "🇵🇱_21"
      - "🇵🇱_22"
      - "🇵🇱_23"
      - "🇵🇱_24"
      - "🇵🇱_25"
      - "🇵🇱_26"
      - "🇵🇱_27"
      - "🇵🇱_28"
      - "🇵🇱_29"
      - "🇵🇱_30"
      - "🇵🇱_31"
      - "🇵🇱_32"
      - "🇵🇱_33"
      - "🇵🇱_34"
      - "🇵🇱_35"
      - "🇵🇱_36"
      - "🇵🇱_37"
      - "🇵🇱_38"
      - "🇵🇱_39"
      - "🇵🇱_40"
      - "🇵🇱_41"
      - "🇵🇱_42"
      - "🇵🇱_43"
      - "🇵🇱_44"
      - "🇵🇱_45"
      - "🇵🇱_46"
      - "🇵🇱_47"
      - "🇵🇱_48"
      - "🇵🇱_49"
      - "🇵🇱_50"
      - "🇵🇱_51"
      - "🇵🇱_52"
      - "🇵🇱_53"


rules:
  - MATCH,PROXY
