name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇵🇹_1"
    type: vless
    server: "171.22.129.56"
    port: 8443
    uuid: "b2744db0-1c64-4218-a93b-9eba0e5f811f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "de-two.quiet-rogue.site"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "QMJRGTqZRbpeLpIAdvn6dhftuzrpwbtwmVG2s5IuuU0"
      short-id: "00a02855ba568c29"
    flow: "xtls-rprx-vision"
  - name: "🇵🇹_2"
    type: vless
    server: "171.22.129.56"
    port: 8443
    uuid: "9f5b9ca7-d0bb-4e50-a3ca-acf5968027fc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "de-two.quiet-rogue.site"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "QMJRGTqZRbpeLpIAdvn6dhftuzrpwbtwmVG2s5IuuU0"
      short-id: "00a02855ba568c29"
    flow: "xtls-rprx-vision"
  - name: "🇵🇹_3"
    type: vless
    server: "171.22.129.56"
    port: 2083
    uuid: "b2744db0-1c64-4218-a93b-9eba0e5f811f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "swe-one.quiet-rogue.site"
    client-fingerprint: "edge"
    reality-opts:
      public-key: "40eDnye2AHCQqgM2_ikKzRayZ4Vlu4rnnkHmLmNalQc"
      short-id: "32a37218722f0081"
    flow: "xtls-rprx-vision"
  - name: "🇵🇹_4"
    type: vless
    server: "171.22.129.56"
    port: 2053
    uuid: "9f5b9ca7-d0bb-4e50-a3ca-acf5968027fc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fi-one.quiet-rogue.site"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "AKUQO-fKsD19FFBxNq5XTFCRXWDZfes4zJjRINY1KUI"
      short-id: "beff3ff061a64cfd"
    flow: "xtls-rprx-vision"
  - name: "🇵🇹_5"
    type: vless
    server: "156.243.83.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime54.workers.dev"
  - name: "🇵🇹_6"
    type: vless
    server: "171.22.129.56"
    port: 2083
    uuid: "9f5b9ca7-d0bb-4e50-a3ca-acf5968027fc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "swe-one.quiet-rogue.site"
    client-fingerprint: "edge"
    reality-opts:
      public-key: "40eDnye2AHCQqgM2_ikKzRayZ4Vlu4rnnkHmLmNalQc"
      short-id: "32a37218722f0081"
    flow: "xtls-rprx-vision"
  - name: "🇵🇹_7"
    type: vless
    server: "171.22.129.56"
    port: 2053
    uuid: "b2744db0-1c64-4218-a93b-9eba0e5f811f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fi-one.quiet-rogue.site"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "AKUQO-fKsD19FFBxNq5XTFCRXWDZfes4zJjRINY1KUI"
      short-id: "beff3ff061a64cfd"
    flow: "xtls-rprx-vision"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇵🇹_1"
      - "🇵🇹_2"
      - "🇵🇹_3"
      - "🇵🇹_4"
      - "🇵🇹_5"
      - "🇵🇹_6"
      - "🇵🇹_7"


rules:
  - MATCH,PROXY
