name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇷🇴_1"
    type: vless
    server: "196.245.156.30"
    port: 443
    uuid: "f5e98e30-28b8-468a-a5a5-c6c22be64055"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "rm2.magazinnarubeva.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "hyOYRfDSIYyqALQt3N2H0RjK8gbV1JvPTkNACC4PJF8"
      short-id: "8718c58d3d51db59"
    flow: "xtls-rprx-vision"
  - name: "🇷🇴_2"
    type: vless
    server: "rm-n1.gsupport.support"
    port: 443
    uuid: "f5e98e30-28b8-468a-a5a5-c6c22be64055"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "rm2.magazinnarubeva.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "hyOYRfDSIYyqALQt3N2H0RjK8gbV1JvPTkNACC4PJF8"
      short-id: "8718c58d3d51db59"
    flow: "xtls-rprx-vision"
  - name: "🇷🇴_3"
    type: vless
    server: "82.117.255.26"
    port: 443
    uuid: "ee9e2135-c444-4adb-aaa5-a0efa1a74fdf"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "gMcijHp0RNZF6l556BaOxu1bKNIFON0_JjXhJzpioAk"
      short-id: "b395baf965957d93"
    flow: "xtls-rprx-vision"
  - name: "🇷🇴_4"
    type: vless
    server: "185.39.30.18"
    port: 8443
    uuid: "2eadb97f-bba4-4471-8d55-bd461525a2dc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eded-52n.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "eded-52n.pages.dev"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇷🇴_1"
      - "🇷🇴_2"
      - "🇷🇴_3"
      - "🇷🇴_4"


rules:
  - MATCH,PROXY
