name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇷🇴_1"
    type: vless
    server: "72.5.42.70"
    port: 40443
    uuid: "000f16e8-cc68-4951-b336-acd81996efde"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "deepl.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "6AOnobBShzL_N96JRBNMfbL84_3myz8ZbKfZUEqRXiY"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇷🇴_2"
    type: vless
    server: "87.58.205.109"
    port: 443
    uuid: "53db95fa-4ebe-4450-8013-a2b0a5827f3f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.googletagmanager.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "GUYDQKGvNl3_YozhbqG8bvecxjQ7HL5A8iqbuYBUUkw"
      short-id: "01c1bb79d6a7c6cf"
    flow: "xtls-rprx-vision"
  - name: "🇷🇴_3"
    type: vless
    server: "82.117.255.87"
    port: 443
    uuid: "b748a230-b157-4401-8423-f8e44df31b5e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "1xxZM10W-A8nuj6MOXFd1kA9lS7bEy-5SO5j-jrd_Cg"
      short-id: "b70076439f4a1340"
    flow: "xtls-rprx-vision"
  - name: "🇷🇴_4"
    type: vless
    server: "72.5.43.45"
    port: 8443
    uuid: "2c532831-127d-45d7-a84e-11ce36a6b1af"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.intel.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "gyKPxwQBhJUGVHE2t4R2pOf64NkdSNgu3DqMxOzKtGU"
      short-id: "5b"
    flow: "xtls-rprx-vision"
  - name: "🇷🇴_5"
    type: vless
    server: "94.198.190.22"
    port: 8443
    uuid: "47388561-cf0c-4cfc-91f8-fdfd9fa3d756"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amazon.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "B5F8h8tpeZ-1ydiT0uFgdc30jJyw8H89Y8e-p_VV6yw"
      short-id: "7b"
    flow: "xtls-rprx-vision"
  - name: "🇷🇴_6"
    type: vless
    server: "node14.fastdatastream.com"
    port: 8443
    uuid: "2c532831-127d-45d7-a84e-11ce36a6b1af"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.intel.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "gyKPxwQBhJUGVHE2t4R2pOf64NkdSNgu3DqMxOzKtGU"
      short-id: "5b"
    flow: "xtls-rprx-vision"
  - name: "🇷🇴_7"
    type: ss
    server: "154.46.31.106"
    port: 443
    cipher: "chacha20-ietf-poly1305"
    password: "QFWzCw2uX9B9i6qAYeFBIE"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇷🇴_1"
      - "🇷🇴_2"
      - "🇷🇴_3"
      - "🇷🇴_4"
      - "🇷🇴_5"
      - "🇷🇴_6"
      - "🇷🇴_7"


rules:
  - MATCH,PROXY
