name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇸🇨_1"
    type: vless
    server: "200.165.228.114"
    port: 9871
    uuid: "f4685d27-73e3-4588-9622-add50b84046a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "Dfgu8Ey0M8Hz4gXGZAwQ3H9jLt2HByVsjAOTWiuKDB0"
      short-id: "aa"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇸🇨_2"
    type: vless
    server: "45.130.125.114"
    port: 8443
    uuid: "f47ac10b-58cc-4372-a567-0e02b2c3d479"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ssl.soren-app.com."
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "free-hzr113-cdn.soren-app.com."
  - name: "🇸🇨_3"
    type: vless
    server: "45.130.125.158"
    port: 2053
    uuid: "e7961655-9674-4cbd-a36f-ec0d5d7d660c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "po.fastbrokencompony.com"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇸🇨_4"
    type: vless
    server: "45.130.125.207"
    port: 8443
    uuid: "31aa0950-eb19-45ff-94a2-af416deb3b90"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "square-salad-ebde.zdfgvccfguuyggg.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/eyJqdW5rIjoiZm5INktPV0lGcHI1NjNSOSIsInByb3RvY29sIjoidmwiLCJtb2RlIjoicHJveHlpcCIsInBhbmVsSVBzIjpbXX0"
      headers:
        Host: "square-salad-ebde.zdfgvccfguuyggg.workers.dev"
  - name: "🇸🇨_5"
    type: vless
    server: "45.130.125.138"
    port: 2053
    uuid: "e7961655-9674-4cbd-a36f-ec0d5d7d660c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "po.fastbrokencompony.com"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇸🇨_6"
    type: vless
    server: "200.165.228.114"
    port: 9871
    uuid: "2a650f3b-d95b-4bd6-aadf-16ccc0717155"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "Dfgu8Ey0M8Hz4gXGZAwQ3H9jLt2HByVsjAOTWiuKDB0"
      short-id: "aabb"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇸🇨_7"
    type: vless
    server: "45.130.125.126"
    port: 443
    uuid: "b69b43d1-091d-4d7c-90b2-7a8bbad9d6a9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "BItter-CreDIT-61b8.b76EbA0aBb.wORkerS.dEv"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/eyJqdW5rIjoiY0U2T212Y21yeEhUZHRKYSIsInByb3RvY29sIjoidmwiLCJtb2RlIjoicHJveHlpcCIsInBhbmVsSVBzIjpbXX0"
      headers:
        Host: "BItter-CreDIT-61b8.b76EbA0aBb.wORkerS.dEv"
  - name: "🇸🇨_8"
    type: vless
    server: "45.130.125.200"
    port: 2053
    uuid: "e7961655-9674-4cbd-a36f-ec0d5d7d660c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "po.fastbrokencompony.com"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇸🇨_9"
    type: vless
    server: "45.130.125.50"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "vms.lifetime58.workers.dev"
  - name: "🇸🇨_10"
    type: vless
    server: "45.130.125.162"
    port: 2053
    uuid: "e7961655-9674-4cbd-a36f-ec0d5d7d660c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "po.fastbrokencompony.com"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇸🇨_11"
    type: trojan
    server: "45.130.125.190"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "🇸🇨_12"
    type: trojan
    server: "45.130.125.18"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇸🇨_1"
      - "🇸🇨_2"
      - "🇸🇨_3"
      - "🇸🇨_4"
      - "🇸🇨_5"
      - "🇸🇨_6"
      - "🇸🇨_7"
      - "🇸🇨_8"
      - "🇸🇨_9"
      - "🇸🇨_10"
      - "🇸🇨_11"
      - "🇸🇨_12"


rules:
  - MATCH,PROXY
