name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇸🇪_1"
    type: vless
    server: "143.246.193.215"
    port: 443
    uuid: "77da6e30-ad4e-11f1-94d5-525400d1d4f7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.blocket.se"
    client-fingerprint: "randomized"
    reality-opts:
      public-key: "wSjV1yR_rhDUdoNbM9zIXNGLASLp9RorComnyoayo2c"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_2"
    type: vless
    server: "5.157.10.148"
    port: 443
    uuid: "4bdeee92-97e8-414d-bef6-ec1d5e2ab73b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "surstreming.vvzzkontaktezzvv.garden"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "x6p656szvu_3CKLsJ4NtkooRvdTVGx7IoPca_p58_jA"
      short-id: "fb442438e2223836"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_3"
    type: vless
    server: "109.120.155.155"
    port: 444
    uuid: "99ab6748-3d57-4562-9451-843c15960b9b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
  - name: "🇸🇪_4"
    type: vless
    server: "109.120.155.155"
    port: 444
    uuid: "c325206e-0f0c-4472-9d76-43e9b9b2ef63"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bapj1qapjk4.0sds0li1bwcz0i76it0gjxv1.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "bapj1qapjk4.0sds0li1bwcz0i76it0gjxv1.workers.dev"
  - name: "🇸🇪_5"
    type: vless
    server: "62.60.152.1"
    port: 56328
    uuid: "ce230b9c-0531-40da-bc3f-f27a8e059db1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "table.vkroom-it-service.xyz"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "iI1pc8k9-mIPHL2Dga-4n4h3KoBT68lN434nglpgm2M"
      short-id: "f3a9c21e8b6d4571"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_6"
    type: vless
    server: "89.22.224.146"
    port: 43788
    uuid: "6fbd9bd1-ccd4-4e2f-a918-a0f871965763"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
  - name: "🇸🇪_7"
    type: vless
    server: "109.120.134.243"
    port: 443
    uuid: "04c808e2-0b59-47b0-a54b-32fc7ef1c902"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "free.cndyw.ggff.net"
    client-fingerprint: "random"
    network: ws
    ws-opts:
      path: "pyip=bpb.yousef.isegaro.com"
      headers:
        Host: "free.cndyw.ggff.net"
  - name: "🇸🇪_8"
    type: vless
    server: "89.22.224.146"
    port: 43788
    uuid: "acc10ba5-a222-44b3-8a1a-4f247ffc6466"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "c6dbx99g6stb418qeo.t3jmlj0r152zji4htdkm9.workers.dev"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "c6dbx99g6stb418qeo.t3jmlj0r152zji4htdkm9.workers.dev"
  - name: "🇸🇪_9"
    type: vless
    server: "89.22.224.146"
    port: 43788
    uuid: "49a6eeaf-7dbf-4aa5-ba21-b36cd47e724e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "kqjifhg9rw.tradsc8p9xp7wxyqmc1wy0ah.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "kqjifhg9rw.tradsc8p9xp7wxyqmc1wy0ah.workers.dev"
  - name: "🇸🇪_10"
    type: vless
    server: "132.243.231.23"
    port: 443
    uuid: "17f388d7-1fa2-440f-a8f4-720b72d19195"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "se.global-cdn.org"
    client-fingerprint: "safari"
    reality-opts:
      public-key: "nF_kEdHan2dgl2tlQ_dtNaKZ4oORhuiFrXHbtEDcT2Q"
      short-id: "2d6d073dc88f22a8"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_11"
    type: vless
    server: "79.141.174.147"
    port: 33743
    uuid: "b3a11068-1a7e-4643-85de-7c82cce46943"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "wGMBs7bvzyzA0-OUiwSkOOTDEMdxEOsSdRzxiP8GGQY"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "TunService"
  - name: "🇸🇪_12"
    type: vless
    server: "31.76.3.34"
    port: 443
    uuid: "0d628b17-8ac4-49b9-a422-6b99077bfdf6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tradingview.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "CetY_ReGID1LBH275yWlxxOctI82PtgxR-fjYSRTKzM"
      short-id: "8a2b3c4d5e6f7012"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_13"
    type: vless
    server: "no.cnd.sweden.myfilecdn.com"
    port: 443
    uuid: "0d628b17-8ac4-49b9-a422-6b99077bfdf6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tradingview.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "CetY_ReGID1LBH275yWlxxOctI82PtgxR-fjYSRTKzM"
      short-id: "8a2b3c4d5e6f7012"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_14"
    type: vless
    server: "193.148.59.178"
    port: 443
    uuid: "20d7c485-5d24-49b5-a5cc-bb7a7daf9908"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "-GMpCber8qtrKzJbwvpLcwlIhOy-5zS66u_x9lLvIjE"
      short-id: "e3daad69"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_15"
    type: vless
    server: "193.42.39.10"
    port: 33743
    uuid: "b3a11068-1a7e-4643-85de-7c82cce46943"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.google.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "wGMBs7bvzyzA0-OUiwSkOOTDEMdxEOsSdRzxiP8GGQY"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "TunService"
  - name: "🇸🇪_16"
    type: ss
    server: "45.138.103.4"
    port: 1443
    cipher: "chacha20-ietf-poly1305"
    password: "N2YzM"
    udp: true
  - name: "🇸🇪_17"
    type: ss
    server: "172.238.244.13"
    port: 17000
    cipher: "aes-256-gcm"
    password: "pX0uhU3ZjUcLWYs0Vez55BO3JoQrRlL"
    udp: true
  - name: "🇸🇪_18"
    type: ss
    server: "se1.auronvpn.site"
    port: 1443
    cipher: "chacha20-ietf-poly1305"
    password: "N2YzM"
    udp: true
  - name: "🇸🇪_19"
    type: ss
    server: "172.238.244.13"
    port: 17000
    cipher: "aes-256-gcm"
    password: "pX0uhU3ZjUcLWYs0Vez55BO3JoQrRlL"
    udp: true
  - name: "🇸🇪_20"
    type: ss
    server: "se1.auronvpn.site"
    port: 1443
    cipher: "chacha20-ietf-poly1305"
    password: "N2YzM"
    udp: true
  - name: "🇸🇪_21"
    type: ss
    server: "70.34.212.124"
    port: 8388
    cipher: "aes-256-gcm"
    password: "AxIYWtskJWIIaefW"
    udp: true
  - name: "🇸🇪_22"
    type: ss
    server: "70.34.212.124"
    port: 8388
    cipher: "aes-256-gcm"
    password: "AxIYWtskJWIIaefW"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇸🇪_1"
      - "🇸🇪_2"
      - "🇸🇪_3"
      - "🇸🇪_4"
      - "🇸🇪_5"
      - "🇸🇪_6"
      - "🇸🇪_7"
      - "🇸🇪_8"
      - "🇸🇪_9"
      - "🇸🇪_10"
      - "🇸🇪_11"
      - "🇸🇪_12"
      - "🇸🇪_13"
      - "🇸🇪_14"
      - "🇸🇪_15"
      - "🇸🇪_16"
      - "🇸🇪_17"
      - "🇸🇪_18"
      - "🇸🇪_19"
      - "🇸🇪_20"
      - "🇸🇪_21"
      - "🇸🇪_22"


rules:
  - MATCH,PROXY
