name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇹🇷_1"
    type: vless
    server: "91.228.227.112"
    port: 110
    uuid: "87f91f87-9077-4414-99ff-26eb8309284b"
    udp: true
  - name: "🇹🇷_2"
    type: vless
    server: "144.225.65.111"
    port: 46142
    uuid: "255386a8-aec5-4425-bfe7-ca49b7448deb"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.yahoo.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "l-OE7EwER1Z_jAifGE_UZ3FqHDMGzaR0jQHFYj5RNAk"
      short-id: "39feeba3085c"
  - name: "🇹🇷_3"
    type: vless
    server: "155.103.69.93"
    port: 443
    uuid: "133f016d-81ad-4ed3-8fe1-e431a4134dca"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "plan.tabrizonlinemaku.ir"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇹🇷_4"
    type: vless
    server: "201.50.115.175"
    port: 443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eu-central.cendora.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "b-Cm9hX-3UHsS1L_lnUB6AMjuKhlN1IDdBbZ506itjI"
      short-id: "00bca5982f82d083"
    flow: "xtls-rprx-vision"
  - name: "🇹🇷_5"
    type: vless
    server: "212.87.199.76"
    port: 2053
    uuid: "e2c6905e-46ec-434b-8400-0bc5bf0363e6"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "v-grpc"
  - name: "🇹🇷_6"
    type: vless
    server: "151.241.226.201"
    port: 2053
    uuid: "52b1aca9-a2ba-4249-9e9f-d488f89c1445"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "dUFJ3jZPMH9WvjtAnUc9wYhO_IX1czIi-CidF_HdFDA"
      short-id: "c267be657e1539ea"
  - name: "🇹🇷_7"
    type: vless
    server: "91.228.227.112"
    port: 110
    uuid: "889732ce-171c-4aa6-8b17-d2646d7a8974"
    udp: true
  - name: "🇹🇷_8"
    type: vless
    server: "45.74.178.12"
    port: 1824
    uuid: "9c62ffbf-1f35-4108-b444-81835e6d3be1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "amp-api-edge.apps.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "JIv_D-Lpo1cosiCUgu-qzGSJwOCGciyXSZ8ucNn6aBo"
      short-id: "8390ee7a5996648b"
  - name: "🇹🇷_9"
    type: vless
    server: "91.228.227.112"
    port: 110
    uuid: "4003d537-6128-4206-b86a-3444f88990c4"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇹🇷_1"
      - "🇹🇷_2"
      - "🇹🇷_3"
      - "🇹🇷_4"
      - "🇹🇷_5"
      - "🇹🇷_6"
      - "🇹🇷_7"
      - "🇹🇷_8"
      - "🇹🇷_9"


rules:
  - MATCH,PROXY
