name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇹🇷_1"
    type: vless
    server: "144.225.65.166"
    port: 26109
    uuid: "8d0a82ca-41cf-4661-a9d7-ea2e192c5f64"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "amp-api-edge.apps.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "0EgMUSL26mD_WAqkFmwMXXWSoWRthDKePFxCvfyu3CU"
      short-id: ""
  - name: "🇹🇷_2"
    type: vless
    server: "107.161.174.96"
    port: 443
    uuid: "97ecaad4-452c-45ec-b591-d68d3308aad4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "partaa2.api3-max.ru"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇹🇷_3"
    type: vless
    server: "206.1.97.81"
    port: 443
    uuid: "c6fb2ef9-eb07-49da-b218-353da511f5ea"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.upwork.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "GFREEsH4rFLnXKDLKXk0iTZNP5_d1zfKTj8DUE0L6RE"
      short-id: "d7397feef49deef9"
  - name: "🇹🇷_4"
    type: vless
    server: "188.132.237.20"
    port: 2095
    uuid: "3b9e513e-30d9-4ca8-8340-8f33fc6710de"
    udp: true
  - name: "🇹🇷_5"
    type: vless
    server: "tr2.rockblack.site"
    port: 8443
    uuid: "6be01e14-b937-4ed5-9d2c-074a0da22ffc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ads.x5.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "fXsQV_dib6rKGAl6EncN6Pm-fTb6TqOa3uTCQWe86Dg"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇹🇷_6"
    type: vless
    server: "45.74.159.233"
    port: 56659
    uuid: "12af43c3-84b4-4248-878b-b75f35835487"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "amp-api-edge.apps.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "qLggZ7qospn6X7UEO1zSoohNXK4Y1EX7Hx2sJeWfvw0"
      short-id: "9aa3a3f599f3d5d0"
    flow: "xtls-rprx-vision"
  - name: "🇹🇷_7"
    type: vless
    server: "158.94.216.50"
    port: 32306
    uuid: "f1505323-ecb6-4152-9a5b-d37b3ae1cacf"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "play-apps-features.googleusercontent.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "5iqitmx5fd71pubTxlrX0sd-ei7palcgVL7vtKToJGA"
      short-id: "61614f026070554f"
  - name: "🇹🇷_8"
    type: vless
    server: "156.67.63.231"
    port: 443
    uuid: "b052df40-d51c-456c-9bd6-57af01a87e4e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sync-bridge.org"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "PTqeBbbr2xJ1L3V1PyYjKjxanMKKqJHU-wtnpYmFQCI"
      short-id: "5606d4a25c99e7af"
    flow: "xtls-rprx-vision"
  - name: "🇹🇷_9"
    type: vless
    server: "83.217.9.252"
    port: 8443
    uuid: "6be01e14-b937-4ed5-9d2c-074a0da22ffc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ads.x5.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "fXsQV_dib6rKGAl6EncN6Pm-fTb6TqOa3uTCQWe86Dg"
      short-id: ""
    flow: "xtls-rprx-vision"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇹🇷_1"
      - "🇹🇷_2"
      - "🇹🇷_3"
      - "🇹🇷_4"
      - "🇹🇷_5"
      - "🇹🇷_6"
      - "🇹🇷_7"
      - "🇹🇷_8"
      - "🇹🇷_9"


rules:
  - MATCH,PROXY
