name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇹🇼_1"
    type: vless
    server: "220.130.75.247"
    port: 10000
    uuid: "431fe973-a43a-4fac-bf83-2a772e0d0625"
    udp: true
  - name: "🇹🇼_2"
    type: vless
    server: "35.187.156.27"
    port: 443
    uuid: "b8ca2900-3ed7-4b58-970e-060d0a6cbf99"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "HsoG0C19O-NY_EcFpK0ybZv9lFol0MjDJLzjDzWAGXs"
      short-id: "d79d3dc3816c329d"
  - name: "🇹🇼_3"
    type: vless
    server: "60.248.219.52"
    port: 443
    uuid: "f265b49a-70a3-407a-b17b-e45dfb9f255c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ty986gfazs.cainiaohub.xyz"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/81574b6b-c9d7-44a0-b83d-dad56e8cb530"
      headers:
        Host: "ty986gfazs.cainiaohub.xyz"
  - name: "🇹🇼_4"
    type: vless
    server: "220.130.75.248"
    port: 10000
    uuid: "431fe973-a43a-4fac-bf83-2a772e0d0625"
    udp: true
  - name: "🇹🇼_5"
    type: vless
    server: "45.121.50.241"
    port: 50159
    uuid: "47a97b7f-044d-43d6-86b0-8b256873d1b5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "E9gCs_C_mSDcHmlCZSMk1kSXpmua48DhgsT_aDpZ1WE"
      short-id: "4c3f80051030ba1b"
    flow: "xtls-rprx-vision"
  - name: "🇹🇼_6"
    type: vless
    server: "60.248.219.78"
    port: 443
    uuid: "c1c04450-bf71-4049-ad0c-9cf6d94d9f1f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ty986gfazs.cainiaohub.xyz"
    network: ws
    ws-opts:
      path: "/81574b6b-c9d7-44a0-b83d-dad56e8cb530"
      headers:
        Host: "ty986gfazs.cainiaohub.xyz"
  - name: "🇹🇼_7"
    type: vless
    server: "141.11.87.48"
    port: 443
    uuid: "601e4ca5-df0a-43a1-97c2-0b1f5c0ae413"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "hZvWDPjsxTSrNSqFXUFgNnXn44vKdr5uirPsie6RGBk"
      short-id: "16ba1b6178a4bdde"
    flow: "xtls-rprx-vision"
  - name: "🇹🇼_8"
    type: trojan
    server: "125.227.86.46"
    port: 443
    password: "3f5bc61547b1f0d9"
    sni: "TG.freecodes"
    skip-cert-verify: true
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "db"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇹🇼_1"
      - "🇹🇼_2"
      - "🇹🇼_3"
      - "🇹🇼_4"
      - "🇹🇼_5"
      - "🇹🇼_6"
      - "🇹🇼_7"
      - "🇹🇼_8"


rules:
  - MATCH,PROXY
