name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇹🇼_1"
    type: vless
    server: "141.11.87.48"
    port: 8443
    uuid: "fdc48be3-a615-41ac-8bd1-ed844c931048"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "edgetunnel-4uw.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "edgetunnel-4uw.pages.dev"
  - name: "🇹🇼_2"
    type: vless
    server: "59.125.69.24"
    port: 443
    uuid: "06e177f7-240d-4687-bd85-235505801a5e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ty986gfazs.cainiaohub.xyz"
    network: ws
    ws-opts:
      path: "/81574b6b-c9d7-44a0-b83d-dad56e8cb530"
      headers:
        Host: "ty986gfazs.cainiaohub.xyz"
  - name: "🇹🇼_3"
    type: vless
    server: "60.248.219.78"
    port: 443
    uuid: "c1c04450-bf71-4049-ad0c-9cf6d94d9f1f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ty986gfazs.cainiaohub.xyz"
    network: ws
    ws-opts:
      path: "/81574b6b-c9d7-44a0-b83d-dad56e8cb530"
      headers:
        Host: "ty986gfazs.cainiaohub.xyz"
  - name: "🇹🇼_4"
    type: vless
    server: "35.201.181.122"
    port: 443
    uuid: "22a0b0bd-1cd0-43fa-a7c3-73b24eae44e2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "PLslPQOBA3bfWO5hXLv7jioCTuNR8vCxa_axi0dC7C0"
      short-id: "32f66f37df3f58d2"
  - name: "🇹🇼_5"
    type: vless
    server: "118.167.207.194"
    port: 24215
    uuid: "19d5a678-8396-4e3b-93da-ece618d0e83a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "addons.mozilla.org"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "mdWKUPMVTtTbDqK10BPb89OcqBC2-Lx-4NOYtqc1GWE"
      short-id: ""
  - name: "🇹🇼_6"
    type: vless
    server: "60.248.219.54"
    port: 443
    uuid: "06e177f7-240d-4687-bd85-235505801a5e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ty986gfazs.cainiaohub.xyz"
    network: ws
    ws-opts:
      path: "/81574b6b-c9d7-44a0-b83d-dad56e8cb530"
      headers:
        Host: "ty986gfazs.cainiaohub.xyz"
  - name: "🇹🇼_7"
    type: trojan
    server: "zhilegelian1.bpca2026.top"
    port: 443
    password: "c2cc86b4-4481-4807-ac9e-24e2d7041248"
    sni: "zhilegelian1.bpca2026.top"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/images"
      headers:
        Host: "zhilegelian1.bpca2026.top"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇹🇼_1"
      - "🇹🇼_2"
      - "🇹🇼_3"
      - "🇹🇼_4"
      - "🇹🇼_5"
      - "🇹🇼_6"
      - "🇹🇼_7"


rules:
  - MATCH,PROXY
