name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇹🇼_1"
    type: vless
    server: "35.187.156.27"
    port: 443
    uuid: "b8ca2900-3ed7-4b58-970e-060d0a6cbf99"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "HsoG0C19O-NY_EcFpK0ybZv9lFol0MjDJLzjDzWAGXs"
      short-id: "d79d3dc3816c329d"
  - name: "🇹🇼_2"
    type: vless
    server: "103.227.225.198"
    port: 32355
    uuid: "a2f6da81-64bd-4b86-b806-5658e161b7e4"
    udp: true
  - name: "🇹🇼_3"
    type: vless
    server: "59.125.69.20"
    port: 443
    uuid: "c1c04450-bf71-4049-ad0c-9cf6d94d9f1f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ty986gfazs.cainiaohub.xyz"
    network: ws
    ws-opts:
      path: "/81574b6b-c9d7-44a0-b83d-dad56e8cb530"
      headers:
        Host: "ty986gfazs.cainiaohub.xyz"
  - name: "🇹🇼_4"
    type: trojan
    server: "tw2.microsoft-orgwly.vip"
    port: 443
    password: "9229374b-8ed5-4e78-aba9-eb572c8a5f27"
    sni: "tls.microsoft-orgwly.vip"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_5"
    type: trojan
    server: "tw2.microsoft-orgwly.vip"
    port: 443
    password: "e8a49406-ac74-4b19-833b-04f736c03345"
    sni: "tls.microsoft-orgwly.vip"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_6"
    type: trojan
    server: "60.250.152.230"
    port: 3462
    password: "6e1b9a65-884f-3aa9-9469-bf6ec0f08610"
    sni: "a03.taipeicitygovernment.cn.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_7"
    type: trojan
    server: "60.250.152.208"
    port: 8443
    password: "96983eb4-c8f1-316e-ab00-500014ed3d8b"
    sni: "official.taipeicitygovernment.chernovtsy.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_8"
    type: trojan
    server: "211.20.156.191"
    port: 28157
    password: "i99Cef"
    sni: "download.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_9"
    type: trojan
    server: "60.250.152.229"
    port: 3462
    password: "6e1b9a65-884f-3aa9-9469-bf6ec0f08610"
    sni: "a03.taipeicitygovernment.cn.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_10"
    type: trojan
    server: "211.20.156.191"
    port: 28152
    password: "i99Cef"
    sni: "download.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_11"
    type: trojan
    server: "taifo03a.kbservice.club"
    port: 443
    password: "6e1b9a65-884f-3aa9-9469-bf6ec0f08610"
    sni: "taifo03a.kbservice.club"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_12"
    type: trojan
    server: "a12.taipeicitygovernment.org.ua"
    port: 3462
    password: "736cd94d-7b94-3e44-8106-3419f64eaf09"
    sni: "a12.taipeicitygovernment.org.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_13"
    type: trojan
    server: "60.250.152.209"
    port: 8443
    password: "96983eb4-c8f1-316e-ab00-500014ed3d8b"
    sni: "official.taipeicitygovernment.net.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_14"
    type: trojan
    server: "60.250.152.209"
    port: 3462
    password: "6e1b9a65-884f-3aa9-9469-bf6ec0f08610"
    sni: "a03.taipeicitygovernment.cn.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_15"
    type: trojan
    server: "61.228.75.128"
    port: 3462
    password: "6e1b9a65-884f-3aa9-9469-bf6ec0f08610"
    sni: "a03.taipeicitygovernment.cn.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_16"
    type: trojan
    server: "60.250.152.208"
    port: 3462
    password: "736cd94d-7b94-3e44-8106-3419f64eaf09"
    sni: "45.32.28.232"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_17"
    type: trojan
    server: "60.250.152.230"
    port: 8443
    password: "96983eb4-c8f1-316e-ab00-500014ed3d8b"
    sni: "official.taipeicitygovernment.ivano-frankivsk.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_18"
    type: trojan
    server: "85.237.206.249"
    port: 443
    password: "3ac6a6ca99f74941b1eaf892818e2ddb"
    sni: "85.237.206.249"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_19"
    type: trojan
    server: "211.20.156.191"
    port: 28158
    password: "i99Cef"
    sni: "download.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_20"
    type: trojan
    server: "60.250.152.208"
    port: 3462
    password: "6e1b9a65-884f-3aa9-9469-bf6ec0f08610"
    sni: "a03.taipeicitygovernment.cn.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_21"
    type: trojan
    server: "tw2.microsoft-orgwly.vip"
    port: 443
    password: "e863739f-a240-4eb5-9abd-780a8ad8ac10"
    sni: "tls.microsoft-orgwly.vip"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_22"
    type: trojan
    server: "official.taipeicitygovernment.cn.ua"
    port: 8443
    password: "96983eb4-c8f1-316e-ab00-500014ed3d8b"
    sni: "official.taipeicitygovernment.cn.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_23"
    type: trojan
    server: "twnode11.oportal.cc"
    port: 443
    password: "981db44e-9f07-49eb-9ba0-6ab4939919a2"
    sni: "twnode11.oportal.cc"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_24"
    type: trojan
    server: "85.237.207.189"
    port: 443
    password: "3ac6a6ca99f74941b1eaf892818e2ddb"
    sni: "85.237.207.189"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_25"
    type: trojan
    server: "210.203.60.190"
    port: 443
    password: "6e1b9a65-884f-3aa9-9469-bf6ec0f08610"
    sni: "45.32.28.232"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_26"
    type: trojan
    server: "203.69.207.175"
    port: 3462
    password: "6e1b9a65-884f-3aa9-9469-bf6ec0f08610"
    sni: "a03.taipeicitygovernment.cn.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_27"
    type: trojan
    server: "61.228.66.155"
    port: 3462
    password: "6e1b9a65-884f-3aa9-9469-bf6ec0f08610"
    sni: "a03.taipeicitygovernment.cn.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_28"
    type: trojan
    server: "a03.taipeicitygovernment.cn.ua"
    port: 3462
    password: "736cd94d-7b94-3e44-8106-3419f64eaf09"
    sni: "45.32.28.232"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_29"
    type: trojan
    server: "61.222.160.199"
    port: 3462
    password: "6e1b9a65-884f-3aa9-9469-bf6ec0f08610"
    sni: "a03.taipeicitygovernment.cn.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_30"
    type: trojan
    server: "61.228.67.106"
    port: 3462
    password: "6e1b9a65-884f-3aa9-9469-bf6ec0f08610"
    sni: "a03.taipeicitygovernment.cn.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_31"
    type: trojan
    server: "118.232.199.29"
    port: 443
    password: "c372c131-2396-44f8-a7db-3b9113468343"
    sni: "node2.yuntongclouds.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_32"
    type: trojan
    server: "official.taipeicitygovernment.cn.ua"
    port: 8443
    password: "96983eb4-cr8f1-316e-ab00-500014ed3d8b"
    sni: "official.taipeicitygovernment.cn.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_33"
    type: trojan
    server: "61.220.126.180"
    port: 443
    password: "981db44e-9f07-49eb-9ba0-6ab4939919a2"
    sni: "twnode11.oportal.cc"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_34"
    type: trojan
    server: "60.250.152.229"
    port: 8443
    password: "96983eb4-c8f1-316e-ab00-500014ed3d8b"
    sni: "official.taipeicitygovernment.chernovtsy.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_35"
    type: trojan
    server: "official.taipeicitygovernment.com.ua"
    port: 8443
    password: "96983eb4-c8f1-316e-ab00-500014ed3d8b"
    sni: "official.taipeicitygovernment.com.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_36"
    type: trojan
    server: "60.250.152.209"
    port: 3462
    password: "736cd94d-7b94-3e44-8106-3419f64eaf09"
    sni: "a12.taipeicitygovernment.org.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_37"
    type: trojan
    server: "official.taipeicitygovernment.ivano-frankivsk.ua"
    port: 8443
    password: "18d443f9-ad28-3c96-b13d-9127c46e06b7"
    sni: "45.32.28.232"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_38"
    type: trojan
    server: "211.22.180.227"
    port: 443
    password: "2613bb74-d727-4b4b-8e61-29bada971316"
    sni: "tls.microsoft-orgwly.vip"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_39"
    type: trojan
    server: "61.228.67.30"
    port: 3462
    password: "6e1b9a65-884f-3aa9-9469-bf6ec0f08610"
    sni: "a03.taipeicitygovernment.cn.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_40"
    type: trojan
    server: "211.20.156.191"
    port: 28155
    password: "i99Cef"
    sni: "download.windowsupdate.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_41"
    type: trojan
    server: "118.232.199.29"
    port: 443
    password: "40cc7c4f-4b86-4c8e-9aea-f1bfbc9e8314"
    sni: "node2.yuntongclouds.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_42"
    type: trojan
    server: "official.taipeicitygovernment.ivano-frankivsk.ua"
    port: 8443
    password: "96983eb4-c8f1-316e-ab00-500014ed3d8b"
    sni: "official.taipeicitygovernment.ivano-frankivsk.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_43"
    type: trojan
    server: "118.232.199.29"
    port: 443
    password: "681e1608-5a5f-48fd-add5-1bc17ebf56b2"
    sni: "node2.yuntongclouds.com"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_44"
    type: trojan
    server: "60.250.152.229"
    port: 3462
    password: "736cd94d-7b94-3e44-8106-3419f64eaf09"
    sni: "a12.taipeicitygovernment.org.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_45"
    type: trojan
    server: "125.227.152.109"
    port: 3462
    password: "6e1b9a65-884f-3aa9-9469-bf6ec0f08610"
    sni: "a03.taipeicitygovernment.cn.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_46"
    type: trojan
    server: "60.250.152.209"
    port: 8443
    password: "96983eb4-cr8f1-316e-ab00-500014ed3d8b"
    sni: "official.taipeicitygovernment.cn.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_47"
    type: trojan
    server: "60.250.152.234"
    port: 3462
    password: "6e1b9a65-884f-3aa9-9469-bf6ec0f08610"
    sni: "a03.taipeicitygovernment.cn.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_48"
    type: trojan
    server: "a03.taipeicitygovernment.cn.ua"
    port: 3462
    password: "6e1b9a65-884f-3aa9-9469-bf6ec0f08610"
    sni: "a03.taipeicitygovernment.cn.ua"
    skip-cert-verify: true
    udp: true
  - name: "🇹🇼_49"
    type: ss
    server: "r3mrcg001287h3p.cybervena.com"
    port: 50099
    cipher: "chacha20-ietf-poly1305"
    password: "7e731ec3-f8e1-43f6-92cf-3978d14705c4"
    udp: true
  - name: "🇹🇼_50"
    type: ss
    server: "r3mrcg001287h3p.cybervena.com"
    port: 50099
    cipher: "chacha20-ietf-poly1305"
    password: "b1ae0fce-9340-4f2e-882d-fdb2218e2e2b"
    udp: true
  - name: "🇹🇼_51"
    type: ss
    server: "36.224.177.236"
    port: 50099
    cipher: "chacha20-ietf-poly1305"
    password: "7e731ec3-f8e1-43f6-92cf-3978d14705c4"
    udp: true
  - name: "🇹🇼_52"
    type: ss
    server: "namrcg001640lrm.cybervena.com"
    port: 50099
    cipher: "chacha20-ietf-poly1305"
    password: "7b56aeaa-8e2d-4bdf-b1d7-233ecca15f56"
    udp: true
  - name: "🇹🇼_53"
    type: ss
    server: "R3MRCG001287H3P.cybervena.com"
    port: 50099
    cipher: "chacha20-ietf-poly1305"
    password: "b1ae0fce-9340-4f2e-882d-fdb2218e2e2b"
    udp: true
  - name: "🇹🇼_54"
    type: ss
    server: "r3mrcg001287h3p.cybervena.com"
    port: 50099
    cipher: "chacha20-ietf-poly1305"
    password: "b1ae0fce-9340-4f2e-882d-fdb2218e2e2b"
    udp: true
  - name: "🇹🇼_55"
    type: ss
    server: "36.224.147.65"
    port: 50099
    cipher: "chacha20-ietf-poly1305"
    password: "7e731ec3-f8e1-43f6-92cf-3978d14705c4"
    udp: true
  - name: "🇹🇼_56"
    type: ss
    server: "namrcg001640lrm.cybervena.com"
    port: 50099
    cipher: "chacha20-ietf-poly1305"
    password: "7b56aeaa-8e2d-4bdf-b1d7-233ecca15f56"
    udp: true
  - name: "🇹🇼_57"
    type: ss
    server: "36.224.177.236"
    port: 50099
    cipher: "chacha20-ietf-poly1305"
    password: "b1ae0fce-9340-4f2e-882d-fdb2218e2e2b"
    udp: true
  - name: "🇹🇼_58"
    type: ss
    server: "r3mrcg001287h3p.cybervena.com"
    port: 50099
    cipher: "chacha20-ietf-poly1305"
    password: "7e731ec3-f8e1-43f6-92cf-3978d14705c4"
    udp: true
  - name: "🇹🇼_59"
    type: ss
    server: "125.224.219.227"
    port: 50099
    cipher: "chacha20-ietf-poly1305"
    password: "a9a0d092-6f0e-4701-81ee-454643d6d506"
    udp: true
  - name: "🇹🇼_60"
    type: ss
    server: "36.224.177.236"
    port: 50099
    cipher: "chacha20-ietf-poly1305"
    password: "b1ae0fce-9340-4f2e-882d-fdb2218e2e2b"
    udp: true
  - name: "🇹🇼_61"
    type: ss
    server: "36.224.177.236"
    port: 50099
    cipher: "chacha20-ietf-poly1305"
    password: "7e731ec3-f8e1-43f6-92cf-3978d14705c4"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇹🇼_1"
      - "🇹🇼_2"
      - "🇹🇼_3"
      - "🇹🇼_4"
      - "🇹🇼_5"
      - "🇹🇼_6"
      - "🇹🇼_7"
      - "🇹🇼_8"
      - "🇹🇼_9"
      - "🇹🇼_10"
      - "🇹🇼_11"
      - "🇹🇼_12"
      - "🇹🇼_13"
      - "🇹🇼_14"
      - "🇹🇼_15"
      - "🇹🇼_16"
      - "🇹🇼_17"
      - "🇹🇼_18"
      - "🇹🇼_19"
      - "🇹🇼_20"
      - "🇹🇼_21"
      - "🇹🇼_22"
      - "🇹🇼_23"
      - "🇹🇼_24"
      - "🇹🇼_25"
      - "🇹🇼_26"
      - "🇹🇼_27"
      - "🇹🇼_28"
      - "🇹🇼_29"
      - "🇹🇼_30"
      - "🇹🇼_31"
      - "🇹🇼_32"
      - "🇹🇼_33"
      - "🇹🇼_34"
      - "🇹🇼_35"
      - "🇹🇼_36"
      - "🇹🇼_37"
      - "🇹🇼_38"
      - "🇹🇼_39"
      - "🇹🇼_40"
      - "🇹🇼_41"
      - "🇹🇼_42"
      - "🇹🇼_43"
      - "🇹🇼_44"
      - "🇹🇼_45"
      - "🇹🇼_46"
      - "🇹🇼_47"
      - "🇹🇼_48"
      - "🇹🇼_49"
      - "🇹🇼_50"
      - "🇹🇼_51"
      - "🇹🇼_52"
      - "🇹🇼_53"
      - "🇹🇼_54"
      - "🇹🇼_55"
      - "🇹🇼_56"
      - "🇹🇼_57"
      - "🇹🇼_58"
      - "🇹🇼_59"
      - "🇹🇼_60"
      - "🇹🇼_61"


rules:
  - MATCH,PROXY
