name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇺🇦_1"
    type: vless
    server: "91.224.86.107"
    port: 9830
    uuid: "2a650f3b-d95b-4bd6-aadf-16ccc0717155"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "bnRIb3Er1i-K6NGGByCO9UbGfOvu43ZoiK7ulPd1SzU"
      short-id: "aabb"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇺🇦_2"
    type: vless
    server: "91.224.86.107"
    port: 9830
    uuid: "553e3253-c454-431d-a7e6-42bc06ea5e14"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "bnRIb3Er1i-K6NGGByCO9UbGfOvu43ZoiK7ulPd1SzU"
      short-id: "aabbccdd"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇺🇦_3"
    type: vless
    server: "78.159.240.41"
    port: 443
    uuid: "39d927a4-b8c7-4dc7-91f1-8b2e05d8b6b6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "id.vk.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "vless-grpc-reality"
  - name: "🇺🇦_4"
    type: vless
    server: "91.224.86.107"
    port: 9830
    uuid: "14777bd9-56a5-46f6-a94f-826b4800dc05"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "bnRIb3Er1i-K6NGGByCO9UbGfOvu43ZoiK7ulPd1SzU"
      short-id: "aabbccdd"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇺🇦_5"
    type: vless
    server: "91.224.86.107"
    port: 9830
    uuid: "064a967e-0862-4cea-bdbd-9458cb7b6070"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "bnRIb3Er1i-K6NGGByCO9UbGfOvu43ZoiK7ulPd1SzU"
      short-id: "aa"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇺🇦_6"
    type: vless
    server: "91.224.86.107"
    port: 9830
    uuid: "fd94a343-cb11-45e6-9882-72352d0a2b8f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "bnRIb3Er1i-K6NGGByCO9UbGfOvu43ZoiK7ulPd1SzU"
      short-id: "aabbccdd"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇺🇦_7"
    type: vless
    server: "91.224.86.107"
    port: 9830
    uuid: "f4685d27-73e3-4588-9622-add50b84046a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "bnRIb3Er1i-K6NGGByCO9UbGfOvu43ZoiK7ulPd1SzU"
      short-id: "aabbccdd"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇺🇦_8"
    type: vless
    server: "91.218.212.223"
    port: 443
    uuid: "2eadb97f-bba4-4471-8d55-bd461525a2dc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eded-52n.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "eded-52n.pages.dev"
  - name: "🇺🇦_9"
    type: vless
    server: "45.135.235.123"
    port: 443
    uuid: "1d16c6e0-1bbe-435b-b661-90043fee999c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "notls.lukongtou.eu.org"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇺🇦_10"
    type: vless
    server: "91.224.86.107"
    port: 9830
    uuid: "86221972-81a1-41f4-a48c-c512af05777c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "bnRIb3Er1i-K6NGGByCO9UbGfOvu43ZoiK7ulPd1SzU"
      short-id: "aa"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇺🇦_11"
    type: vless
    server: "213.111.149.58"
    port: 8443
    uuid: "2eadb97f-bba4-4471-8d55-bd461525a2dc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eded-52n.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "eded-52n.pages.dev"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇺🇦_1"
      - "🇺🇦_2"
      - "🇺🇦_3"
      - "🇺🇦_4"
      - "🇺🇦_5"
      - "🇺🇦_6"
      - "🇺🇦_7"
      - "🇺🇦_8"
      - "🇺🇦_9"
      - "🇺🇦_10"
      - "🇺🇦_11"


rules:
  - MATCH,PROXY
