name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇺🇦_1"
    type: vless
    server: "45.135.235.7"
    port: 8443
    uuid: "7967bf59-57e3-4cde-9898-527b0fe60022"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "speed.dulacloud.store"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/dula?Telegram-WangCai2"
      headers:
        Host: "speed.dulacloud.store"
  - name: "🇺🇦_2"
    type: vless
    server: "5.34.182.23"
    port: 443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eu-central.cendora.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "b-Cm9hX-3UHsS1L_lnUB6AMjuKhlN1IDdBbZ506itjI"
      short-id: "00bca5982f82d083"
    flow: "xtls-rprx-vision"
  - name: "🇺🇦_3"
    type: vless
    server: "45.135.235.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "vms.lifetime07.workers.dev"
  - name: "🇺🇦_4"
    type: vless
    server: "5.34.182.23"
    port: 13443
    uuid: "5238521b-c5dd-42af-870e-c174a2aaaafe"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "auto.cendora.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "gc9oXe37KCCm3J1dJ03wdGsnxPBdeEkRPOvl_t-vfVM"
      short-id: "a7f3c91b2e6d84c0"
    flow: "xtls-rprx-vision"
  - name: "🇺🇦_5"
    type: vless
    server: "89.116.180.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime09.workers.dev"
  - name: "🇺🇦_6"
    type: vless
    server: "45.135.235.123"
    port: 443
    uuid: "1d16c6e0-1bbe-435b-b661-90043fee999c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "notls.lukongtou.eu.org"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/Telegram-WangCai2🇨🇳"
      headers:
        Host: "notls.lukongtou.eu.org"
  - name: "🇺🇦_7"
    type: vless
    server: "193.238.153.15"
    port: 443
    uuid: "40cfbd0a-f133-4174-8e03-ab0e587e1099"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "dzknsuwujuOacNHTXzdPxBLNUEJfEImiwLinPPNFmwU"
      short-id: "1ea21a140beaecc5"
    flow: "xtls-rprx-vision"
  - name: "🇺🇦_8"
    type: vless
    server: "176.103.113.118"
    port: 443
    uuid: "50414e45-4c5f-5a45-5553-fcd8aac6529c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ez-a9e0f2.l10086280.workers.dev"
    client-fingerprint: "ios"
    network: ws
    ws-opts:
      path: "/stream/PANEL_ZEUS/fcd8aac6529c"
      headers:
        Host: "ez-a9e0f2.l10086280.workers.dev"
  - name: "🇺🇦_9"
    type: vless
    server: "88.151.195.213"
    port: 443
    uuid: "41f4cb15-5a3f-3934-89fe-b4177146adf4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "u643766ubdb325a3s274.kukuss.top"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇺🇦_10"
    type: trojan
    server: "89.116.180.49"
    port: 443
    password: "f18d6149-e214-8554-e737-f7523c8b2eea"
    sni: "0403.infinityconfig4.workers.dev"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/sync"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇺🇦_1"
      - "🇺🇦_2"
      - "🇺🇦_3"
      - "🇺🇦_4"
      - "🇺🇦_5"
      - "🇺🇦_6"
      - "🇺🇦_7"
      - "🇺🇦_8"
      - "🇺🇦_9"
      - "🇺🇦_10"


rules:
  - MATCH,PROXY
